### ISSUE TITLE
 Could not register MSBuild exception on startup

### ISSUE THREAD

**Issue by andrewlock** [nuke-build/nuke#1011]
### Usage Information

Nuke 6.2.1/.NET SDK 7 preview 7 (runtime 6.0.8) / tfm net6.0/ OS Windows 10

### Description

I'm in the process of updating to the latest version of Nuke [here](https://github.com/DataDog/dd-trace-dotnet/tree/andrew/update-nuke). When building (e.g. with `./tracer/build.ps1 Clean`), a warning is produced every time related to Telemetry, and inability to load `System.Configuration.ConfigurationManager`:

```bash
NUKE Execution Engine version 6.2.1 (Windows,.NETCoreApp,Version=v6.0)
​
14:05:37 [WRN] Could not register MSBuild: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
14:05:37 [WRN] Exception was suppressed
System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Build.Locator.MSBuildLocator.<>c__DisplayClass15_0.<RegisterMSBuildPath>g__TryLoadAssembly|3(AssemblyName assemblyName)
   at Microsoft.Build.Locator.MSBuildLocator.<>c__DisplayClass15_0.<RegisterMSBuildPath>b__2(AssemblyLoadContext _, AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor()
   at Nuke.Common.ProjectModel.ProjectModelTasks.ParseProject(String projectFile, String configuration, String targetFramework) in /_/source/Nuke.Common/ProjectModel/ProjectModelTasks.cs:line 148
   at Nuke.Common.Execution.Telemetry.CheckAwareness() in /_/source/Nuke.Common/Execution/Telemetry.cs:line 70
​
╬══════════
║ Clean
╬══
```

### Reproduction Steps

Build any target in [the updated branch here](https://github.com/DataDog/dd-trace-dotnet/tree/andrew/update-nuke), e.g. `./tracer/build.ps1 Clean`

### Expected Behavior

Shouldn't see any errors

### Actual Behavior

```bash
[WRN] Could not register MSBuild: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
```

### Regression?

I was upgrading from `5.0.2`, and didn't see these errors

### Known Workarounds

Setting `NUKE_TELEMETRY_OPTOUT=1` solves the issue (though deprives you of telemetry!)

**Comment by andrewlock** [comment]
Realizing that this isn't restricted to Telemetry now [as `Nuke.Common.ProjectModel.ProjectExtensions.GetTargetFrameworks()` is throwing a similar exception](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=111851&view=logs&j=3a2d12d1-9a5a-574f-fb77-446ebedcf42d&t=262bb478-a15a-560a-70d2-bf403900c42c):

```
13:52:33 [WRN] Could not register MSBuild: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
13:52:33 [ERR] Target CopyNativeFilesForAppSecUnitTests has thrown an exception
System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Build.Locator.MSBuildLocator.<>c__DisplayClass15_0.<RegisterMSBuildPath>g__TryLoadAssembly|3(AssemblyName assemblyName)
   at Microsoft.Build.Locator.MSBuildLocator.<>c__DisplayClass15_0.<RegisterMSBuildPath>b__2(AssemblyLoadContext _, AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor()
   at Nuke.Common.ProjectModel.ProjectModelTasks.ParseProject(String projectFile, String configuration, String targetFramework) in /_/source/Nuke.Common/ProjectModel/ProjectModelTasks.cs:line 148
   at Nuke.Common.ProjectModel.ProjectExtensions.GetSplittedPropertyValue(Project project, String[] names) in /_/source/Nuke.Common/ProjectModel/ProjectExtensions.cs:line 104
   at Nuke.Common.ProjectModel.ProjectExtensions.GetTargetFrameworks(Project project) in /_/source/Nuke.Common/ProjectModel/ProjectExtensions.cs:line 90
```

**Comment by matkoch** [comment]
Can't reproduce. If you can in an isolated repository, please feel free to reopen.

**Comment by GeorgDangl** [comment]
I've encountered the same problem, recently GitHub Actions on `ubuntu-latest` started failing for us.

I solved it by manually adding `<PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />`.
