### ISSUE TITLE
Solution model fails if there is a nested solution folder with the same name

### ISSUE THREAD

**Issue by glconti** [nuke-build/nuke#1020]
### Usage Information

NUKE Execution Engine version 6.2.1 (Windows,.NETCoreApp,Version=v6.0)

### Description

If I have a solution with this kind of hierarchy where `MySolutionFolder` is present both at the root level and also in a nested solution folder
![image](https://user-images.githubusercontent.com/13535297/192616295-d491fd61-0cbe-4029-8fad-44086e09623b.png)
And use the typed solution model in a build target:
```csharp
[Solution(GenerateProjects = true)] readonly Solution Solution;

Target Compile => _ => _
    .Executes(() =>
    {
        Log.Information("The project name is: {Project}", Solution.Tests.MySolutionFolder.MyLibrary1_Tests);
        Log.Information("The project name is: {Project}", Solution.MySolutionFolder.MyLibrary1);
    });
```
 the compile step above fails at the second log line with 
```
╬════════════
║ Compile
╬═══
​
21:20:34 [INF] The project name is: [...]\NukeSolutionModelBug\Tests\MyLibrary1.Tests\MyLibrary1.Tests.csproj
21:20:34 [ERR] Target Compile has thrown an exception
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.ProjectModel.Solution.GetSolutionFolder(String name) in /_/source/Nuke.Common/ProjectModel/Solution.cs:line 68
   at Solution.get_MySolutionFolder() in [...]\NukeSolutionModelBug\build\Nuke.SourceGenerators\Nuke.SourceGenerators.StronglyTypedSolutionGenerator\StronglyTypedSolutionGenerator.cs:line 7
   at Build.<get_Compile>b__4_1() in [...]\NukeSolutionModelBug\build\Build.cs:line 34
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

### Reproduction Steps

You can find here a minimal solution to reproduce the issue:
[NukeSolutionModelBug.zip](https://github.com/nuke-build/nuke/files/9659039/NukeSolutionModelBug.zip)
- just unpack the zip file
- run `nuke` command from a cli in that folder

### Expected Behavior

The given example solution should build with Nuke successfully, not throwing any exception

### Actual Behavior

An exception in thrown
```
21:20:34 [ERR] Target Compile has thrown an exception
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.ProjectModel.Solution.GetSolutionFolder(String name) in /_/source/Nuke.Common/ProjectModel/Solution.cs:line 68
   at Solution.get_MySolutionFolder() in [...]\NukeSolutionModelBug\build\Nuke.SourceGenerators\Nuke.SourceGenerators.StronglyTypedSolutionGenerator\StronglyTypedSolutionGenerator.cs:line 7
   at Build.<get_Compile>b__4_1() in [...]\NukeSolutionModelBug\build\Build.cs:line 34
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

### Regression?

No Idea

### Known Workarounds

Don't use the typed solution model in this case and do something like
```csharp
[Solution(GenerateProjects = true)] readonly Solution Solution;

Target Compile => _ => _
    .Executes(() =>
    {
        var testProject = Solution.GetProject("MyLibrary1.Tests");
        var srcProject = Solution.GetProject("MyLibrary1");

        Log.Information("The project name is: {Project}", testProject);
        Log.Information("The project name is: {Project}", srcProject);
    });
```
Which produces the correct output
```
​
╬════════════
║ Compile
╬═══
​
21:31:33 [INF] The project name is: [...]\NukeSolutionModelBug\Tests\MyLibrary1.Tests\MyLibrary1.Tests.csproj
21:31:33 [INF] The project name is: [...]\Repos\NukeSolutionModelBug\MyLibrary1\MyLibrary1.csproj
```

**Comment by Oren14Dani** [comment]
Hi!!
I would like to jump in and try to solve this 🙌
Can I have a pin/starting point?
