### ISSUE TITLE
DeleteDirectory descends into symlinked directories

### ISSUE THREAD

**Issue by aloker** [nuke-build/nuke#1037]
### Usage Information

6.2.1 (Windows,.NETCoreApp,Version=v6.0)

### Description

`FileSystemTasks.DeleteDirectory` recursively deletes all files and directories. The recursion also descends into directories that are linked directories, deleting files and directories that are possibly unrelated to the current project or should not actually be deleted. 

For example:
In a project that makes use of npm workspaces, the top level node_modules folder will contain soft links to all defined workspace projects. Deleting node_modules with `FileSystemTasks.DeleteDirectory` will not only delete the node_modules folder **but also the actual source code of the workspace projects**.

I consider this a bug because the behavior is unexpected, dangerous and deviates from the behavior of other ways of deleting node_modules such as: 
- `rmdir /s /q node_modules` (Windows)
- `rm -rf node_modules` (Linux)
- `System.IO.Directory.Delete(path, recursive: true)`

These methods always only delete the links and do not recurse further.

### Reproduction Steps

See repo https://github.com/aloker/nuke-recursive-delete-directory

The project makes use of npm workspaces. 

`nuke`  will perform an `npm ci` followed by a npm run build in the packages/js-project directory.

'nuke Clean' (`RootDirectory.GlobDirectories("**/node_modules").ForEach(DeleteDirectory);`) is supposed to delete all node_modules folders in the project, but due to the bug it will completely empty the packages/js-project directory.

### Expected Behavior

DeleteDirectory should not descend into the linked directory but only delete the link itself.

Specifically, when the directory has the attribute `FileAttributes.ReparsePoint`, the recursion should stop. 

### Actual Behavior

DeleteDirectory recurses into linked directories and recursively deleted everything in there.

### Regression?

Not known

### Known Workarounds

Use `System.IO.Directory.Delete(path, true)` instead

**Comment by lahma** [comment]
Hey ran into this very same problem just yesterday, great minds break alike, huh?

I've created a repro for the problem: https://github.com/lahma/NukeNpmSymlinkProblem , which shows a different side for the problem on Windows and how directory delete fails. This is probably partially caused by NPM creating a bad symlink.

`npm install` and then `.\build.cmd` shows the problem:

```
╬══════════
║ Clean
╬══
​
08:49:09 [ERR] Target Clean has thrown an exception
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\marko.lahma\RiderProjects\NukeNpmSymlinkProblem\node_modules\materialize-css'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at GlobExpressions.TraverseOptions.GetDirectories(DirectoryInfo root)
   at GlobExpressions.PathTraverserEnumerable.JobsMatchingSegment(List`1 nextSegmentRoots, DirectoryInfo directoryInfo, Segment segment)
   at GlobExpressions.PathTraverserEnumerable.<>c__DisplayClass6_1.<GetEnumerator>b__1(DirectoryInfo job)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at GlobExpressions.PathTraverserEnumerable.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nuke.Common.IO.PathConstruction.GlobDirectories(String directory, String[] patterns) in /_/source/Nuke.Common/IO/PathConstruction.cs:line 148
   at Nuke.Common.IO.PathConstruction.GlobDirectories(AbsolutePath directory, String[] patterns) in /_/source/Nuke.Common/IO/PathConstruction.cs:line 153
   at Build.<>c.<get_Clean>b__2_1() in C:\Users\marko.lahma\RiderProjects\NukeNpmSymlinkProblem\build\Build.cs:line 18
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

Basically NPM has created symlinked directory which then NUKE fails to delete. I believe correct behavior would be to delete the directory and not try to recurse into it.
