### ISSUE TITLE
build.sh Could not find 'mono' via '/usr/bin/which'

### ISSUE THREAD

**Issue by RouR** [nuke-build/nuke#104]
I got this exception. I think there is a bug in this script.

```
$ ./build.sh
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Microsoft (R) .NET Core SDK version 2.0.2
_  _ _  _ _  _ ____ 
|\ | |  | |_/  |___ 
| \| |__| | \_ |___ 
Version: 0.5.3 [CommitSha: 0aff3c55]
Host: Travis
Assertion failed: Could not find 'mono' via '/usr/bin/which'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPathExecutable(String pathExecutable)
   at Nuke.Common.Tooling.ProcessManager.StartProcess(ToolSettings toolSettings, ProcessSettings processSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator, ProcessSettings processSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetStaticValue()
   at Nuke.Common.Execution.InjectionService.InjectValues(NukeBuild build)
   at Nuke.Common.Execution.BuildExecutor.Execute[T](Expression`1 defaultTargetExpression)
The command "./build.sh" exited with 7.
```

Full build log - https://travis-ci.org/RouR/ToDo-ToBuy/builds/409529136
Config file for Travis - https://github.com/RouR/ToDo-ToBuy/blob/413beb4b4f9e25f509d13fce0d74382c449fb0b9/.travis.yml#L35

**Comment by matkoch** [comment]
If you want to use GitVersion, you need to have Mono installed. Looks like you haven’t?

**Comment by RouR** [comment]
I don't see this requirement in documentation.
Is it possible to use GitVersion without Mono?
As you see in build log - .NET Core 2.0.2 work`s fine on ubuntu.14.04-x64 without any dependency to Mono

**Comment by matkoch** [comment]
It is not in the documentation, that’s true. I think we can improve the error message here to tell people that the particular tool requires Mono/NetFramework.

However, I don’t think we will add documentation for this, because this is a third party tool, that only integrates with Nuke. So any information we give about compatiblity could possibly run out of date.

**Comment by matkoch** [comment]
If you really want to to use GitVersion along with .NET Core, you must have Mono installed. If you like you can create an issue on the GitVersion repository.

**Comment by RouR** [comment]
Mono dependency was removed in GitVersion.

**Comment by matkoch** [comment]
good to hear
