### ISSUE TITLE
ReadReleaseNotes() method throws exception when changelog file contains empty lines

### ISSUE THREAD

**Issue by sandrofigo** [nuke-build/nuke#1094]
### Usage Information

6.3.0 / 7.0.101 / net6.0 / Windows

### Description

When trying to read the release notes with `ChangelogTasks.ReadReleaseNotes` from a changelog file that contains empty lines after a release header the exception `System.ArgumentException: Release Notes should not be empty` is thrown.

This is issue is probably related to #430

### Reproduction Steps

1. Setup new nuke project with all default values `nuke :setup`
2. Replace the code in `Build.cs` with the sample code below
```csharp
using Nuke.Common;
using Nuke.Common.ChangeLog;

class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.ChangelogTasksFailing);

    Target ChangelogTasksWorking => _ => _
        .Executes(() =>
        {
            var workingReleaseNotes = ChangelogTasks.ReadReleaseNotes(RootDirectory / "working_CHANGELOG.md");
        });

    Target ChangelogTasksFailing => _ => _
        .DependsOn(ChangelogTasksWorking)
        .Executes(() =>
        {
            var failingReleaseNotes = ChangelogTasks.ReadReleaseNotes(RootDirectory / "failing_CHANGELOG.md");
        });
}
```
3. Place the attached changelog files in the `RootDirectory`
[failing_CHANGELOG.md](https://github.com/nuke-build/nuke/files/10298392/failing_CHANGELOG.md)
[working_CHANGELOG.md](https://github.com/nuke-build/nuke/files/10298393/working_CHANGELOG.md)
4. Run build with `nuke` command

> [failing_CHANGELOG.md](https://github.com/nuke-build/nuke/files/10298392/failing_CHANGELOG.md) taken from https://keepachangelog.com/en/1.0.0/
> [working_CHANGELOG.md](https://github.com/nuke-build/nuke/files/10298393/working_CHANGELOG.md) was modified to not contain any empty lines

### Expected Behavior

All targets should succeed; `ChangelogTasks.ReadReleaseNotes` should not throw exception with the provided input.

### Actual Behavior

First target `ChangelogTasksWorking` succeeds, but second target `ChangelogTasksFailing` throws the following exception:
```
System.ArgumentException: Release Notes should not be empty
   at Nuke.Common.Assert.True(Boolean condition, String message, String argumentExpression) in /_/source/Nuke.Common/Assert.cs:line 34
   at Nuke.Common.ChangeLog.ReleaseNotes..ctor(NuGetVersion version, IReadOnlyList`1 notes, Int32 startIndex, Int32 endIndex) in /_/source/Nuke.Common/ChangeLog/ReleaseNotes.cs:line 56
   at Nuke.Common.ChangeLog.ChangelogTasks.<>c__DisplayClass1_0.<ReadReleaseNotes>g__Parse|0(ReleaseSection section) in /_/source/Nuke.Common/ChangeLog/ChangeLogTasks.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nuke.Common.ChangeLog.ChangelogTasks.ReadReleaseNotes(String changelogFile) in /_/source/Nuke.Common/ChangeLog/ChangeLogTasks.cs:line 53
   at Build.<>c.<get_ChangelogTasksFailing>b__4_1() in <redacted>\build\Build.cs:line 18
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

### Known Workarounds

Remove all empty lines from the changelog file before using it.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
@sandrofigo if you can, please send a pull-request. Please also do some manual testing, as there are no tests for this right now.

**Comment by sandrofigo** [comment]
@matkoch should I include some basic unit tests in this pull request or should I open a new one afterwards?

**Comment by sandrofigo** [comment]
While doing some testing, I also noticed that release sections containing list items that span multiple lines cause truncation to the rest of the release section. See #1099
