### ISSUE TITLE
ShutdownDotNetAfterServerBuildAttribute fails the build on Linux sometimes

### ISSUE THREAD

**Issue by aristotelos** [nuke-build/nuke#1096]
### Usage Information

6.2.1 / net6.0 / Centos 7

### Description

We are running a Docker build from Nuke. This is however randomly failing with the following exception: `Unhandled exception. System.ArgumentException: Expected condition to be true (Parameter 'process.WaitForExit()'`, with in the stack trace pointing out that it comes from `Nuke.Common.CI.ShutdownDotNetAfterServerBuildAttribute.OnBuildFinished(NukeBuild build) in /_/source/Nuke.Common/CI/ShutdownDotNetAfterServerBuildAttribute.cs:line 28`. This happens after the Docker build has exited successfully. The funny thing is that the `ShutdownDotNetAfterServerBuildAttribute` kicks in even when we are not running any `dotnet` tasks.

A snippet of the output of our CI server:
```
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 exporting to image
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 exporting layers
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 exporting layers 0.3s done
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 writing image sha256:ca7a019f9d9a8a2ad8fa46b1ca57220a7c279163f2782a8bc338b828691ccd30 done
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 naming to docker.io/library/api:0.0.0.0 done
build	05-Jan-2023 04:12:15	[ERR] DockerImage: #26 DONE 0.3s
build	05-Jan-2023 04:12:15	?
build	05-Jan-2023 04:12:15	???????????????????????????????????????
build	05-Jan-2023 04:12:15	Target?????????????Status??????Duration
build	05-Jan-2023 04:12:15	???????????????????????????????????????
build	05-Jan-2023 04:12:15	DockerImage????????Succeeded???????0:46
build	05-Jan-2023 04:12:15	???????????????????????????????????????
build	05-Jan-2023 04:12:15	Total??????????????????????????????0:46
build	05-Jan-2023 04:12:15	???????????????????????????????????????
build	05-Jan-2023 04:12:15	?
build	05-Jan-2023 04:12:15	Build succeeded on 1/5/2023 4:12:15 AM. ???????
error	05-Jan-2023 04:12:30	Unhandled exception. System.ArgumentException: Expected condition to be true (Parameter 'process.WaitForExit()')
error	05-Jan-2023 04:12:30	   at Nuke.Common.Assert.True(Boolean condition, String message, String argumentExpression) in /_/source/Nuke.Common/Assert.cs:line 34
error	05-Jan-2023 04:12:30	   at Nuke.Common.Tooling.ProcessExtensions.AssertWaitForExit(IProcess process) in /_/source/Nuke.Common/Tooling/ProcessExtensions.cs:line 27
error	05-Jan-2023 04:12:30	   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Common/Tooling/ProcessExtensions.cs:line 36
error	05-Jan-2023 04:12:30	   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNet(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Func`2 outputFilter) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 41
error	05-Jan-2023 04:12:30	   at Nuke.Common.CI.ShutdownDotNetAfterServerBuildAttribute.OnBuildFinished(NukeBuild build) in /_/source/Nuke.Common/CI/ShutdownDotNetAfterServerBuildAttribute.cs:line 28
error	05-Jan-2023 04:12:30	   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
error	05-Jan-2023 04:12:30	   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
error	05-Jan-2023 04:12:30	   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/Execution/BuildManager.cs:line 80
error	05-Jan-2023 04:12:30	   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/NukeBuild.cs:line 75
error	05-Jan-2023 04:12:30	   at Build.Main() in /var/lib/devops/bagent/vitaldev/VWORKFLOW-WORKLIST320-BUILDAPISERVICE/vitrea_workflow_worklist/delta.api.workflow/build/Build.cs:line 31
```

### Reproduction Steps

We are using the following command to run Docker build:

```
    Target DockerImage => _ => _
        .Executes(() =>
        {
            DockerBuild(x => x
                .SetFile("src/Api/Dockerfile")
                .SetPath("../")
                .SetProcessEnvironmentVariable("DOCKER_BUILDKIT", "1")
                .SetTag($"api:{_version}")
            );
        });
```

We are running Nuke by:
```
./build.sh DockerImage
```

### Expected Behavior

The build should succeed and not throw an exception. I would expect that the `ShutdownDotNetAfterServerBuildAttribute` would do nothing in our case, because we are not running any `dotnet` tasks.

### Actual Behavior

The build fails randomly with an unexpected exception.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
can't repro
