### ISSUE TITLE
ExitCode does not work because process is already exited

### ISSUE THREAD

**Issue by Rick-van-Dam** [nuke-build/nuke#1153]
### Usage Information

6.3.0

### Description

We are getting this error when we want to read the error code from nunit console:

### Reproduction Steps

Add this target and run it:
```
    Target NunitReproductionExample => _ => _
        .Executes(() =>
        {
            try
            {
                NUnit3(c => c
                    .SetInputFiles("foo.dll")
                    .SetWhereExpression("corrupted where"));
            }
            catch (ProcessException e)
            {
                Console.WriteLine(e.ExitCode.ToString());
            }
        });
```

### Expected Behavior

Looking at the decompiled ProcessException class I find this:
```
public int ExitCode => this.Process.ExitCode;
```

I think NUKE shouldn't retrieve the ExitCode from the process like this since by the time that happens that process might already have exited. I guess it better to just store the ExitCode in the ProcessException instance.

### Actual Behavior

```
10:46:17 [INF] > C:\Users\damric\.nuget\packages\nunit.consolerunner\3.11.1\tools\nunit3-console.exe foo.dll --where="corrupted where"
10:46:17 [DBG] NUnit Console Runner 3.11.1 (.NET 2.0)
10:46:17 [DBG] Copyright (c) 2020 Charlie Poole, Rob Prouse
10:46:17 [DBG] Monday, 24 April 2023 10:46:17
10:46:17 [DBG]
10:46:17 [DBG] Runtime Environment
10:46:17 [DBG]    OS Version: Microsoft Windows NT 6.2.9200.0
10:46:17 [DBG]    Runtime: .NET Framework CLR v4.0.30319.42000
10:46:17 [DBG]
10:46:17 [DBG] Test Files
10:46:17 [DBG]     foo.dll
10:46:17 [DBG]
10:46:17 [DBG] Test Filters
10:46:17 [DBG]     Where: corrupted where
10:46:17 [DBG]
10:46:17 [DBG] Unexpected token 'where' at position 10 in selection expression.
10:46:17 [ERR] Target NunitReproductionExample has thrown an exception
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at Nuke.Common.Tooling.Process2.get_ExitCode() in /_/source/Nuke.Common/Tooling/Process2.cs:line 34
   at Nuke.Common.Tooling.ProcessException.get_ExitCode() in /_/source/Nuke.Common/Tooling/ProcessException.cs:line 58
   at IUptrendsApp.<>c.<get_NunitReproductionExample>b__45_1() in C:\git\Uptrends\Tools\build\Components\IUptrendsApp.cs:line 120
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

### Regression?

This was a new feature in 6.3.0 that was introduced in this PR: https://github.com/nuke-build/nuke/pull/1068 by @Baune8D 

### Could you help with a pull-request?

Yes

**Comment by Baune8D** [comment]
Yes, this has already been fixed in develop for some time: https://github.com/nuke-build/nuke/pull/1086 just awaiting a new release 🙂
