### ISSUE TITLE
Can't filter invocation

### ISSUE THREAD

**Issue by gabrielweyer** [nuke-build/nuke#1169]
### Usage Information

NUKE 7.0.0

### Description

In NUKE 6.3.0 I used to be able to use the `outputFilter` to redact **both** the invocation and the output for a `DotNet` command. In NUKE 7.0.0, this parameter is gone and `logger` is only capturing the output.

### Reproduction Steps

In NUKE 6.3.0:

```csharp
DotNet(
    $"user-secrets set {secretName} {secretValue} --id {UserSecretsId}",
    outputFilter: o => o.Replace(secretValue, "*****", StringComparison.Ordinal));
```

In NUKE 7.0.0:

```csharp
DotNet($"user-secrets set {secretName} {secretValue} --id {UserSecretsId}", logger: RedactLog, logInvocation: false);

void RedactLog(OutputType type, string s)
{
    var redactedLog = s.Replace(secretValue, "*****", StringComparison.Ordinal);
    Serilog.Log.Write(type == OutputType.Err ? LogEventLevel.Error : LogEventLevel.Information, redactedLog);
}
```

### Expected Behavior

These are the logs I used to get in NUKE 6.3.0:

```plaintext
07:10:57 [INF] > /usr/share/dotnet/dotnet user-secrets set ServiceBusConnection ***** --id 074ca336-270b-4832-9a1a-60baf152b727
07:10:57 [DBG] Successfully saved ServiceBusConnection = ***** to the secret store.
```

### Actual Behavior

These are the logs I'm getting in NUKE 7.0.0 with my workaround:

```plaintext
22:05:16 [INF] Successfully saved ServiceBusConnection = ***** to the secret store.
```

### Regression?

The parameter `outputFilter` used to be present in NUKE 6.3.0. I don't know if this is regression as the name of the parameter suggests it should only have been filtering the output. But I came to rely on this behaviour.

### Known Workarounds

As a partial workaround, I can use the `logger` parameter but it doesn't give me the opportunity to redact the invocation.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
You don't need the output filter anymore. `$"--key {secretKey:r}"` will automatically redact from log output.

**Comment by gabrielweyer** [comment]
I've updated my code to be:

```csharp
DotNet($"user-secrets set {secretName} {secretValue:r} --id {UserSecretsId}");
```
But the secret still appears in clear-text **when running locally**:

![image](https://github.com/nuke-build/nuke/assets/2101647/90d4ebe9-e504-40d3-934f-e59f5439b8ae)

Does the redaction only happen on a build server?

**Comment by matkoch** [comment]
Should happen always. Try to debug it

![JetBrains Rider-ConsoleApp1 – Build cs-2023-05-15-37gmJECg@2x](https://github.com/nuke-build/nuke/assets/5005566/53e08a1a-e1cc-4103-bd32-1838b0ee0697)

**Comment by gabrielweyer** [comment]
Apologies, I haven't had the time to debug through it yet but I did manage to build a minimal repro case:

```csharp
DotNet($"{"a+b":r}");
```
Note how _executable_ has been redacted in the output. This indicates the secret has been interpreted as a regular expression:

![image](https://github.com/nuke-build/nuke/assets/2101647/63da6e94-597f-441d-bcb4-ce21c59a1646)

Which is confirmed by using:

```csharp
DotNet($"{"+b":r}");
```

```plaintext
07:59:43 [ERR] Target Restore has thrown an exception
System.Text.RegularExpressions.RegexParseException: Invalid pattern '+b' at offset 1. Quantifier {x,y} following nothing.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
   at System.Text.RegularExpressions.Regex.Init(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern, RegexOptions options, TimeSpan matchTimeout)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, MatchEvaluator evaluator, RegexOptions options)
   at Nuke.Common.Utilities.StringExtensions.ReplaceRegex(String str, String pattern, MatchEvaluator matchEvaluator, RegexOptions options) in /_/source/Nuke.Utilities/Text/String.Replace.cs:line 25
   at Nuke.Common.Tooling.ProcessTasks.<>c.<StartProcess>b__6_2(String arguments, String value) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 82
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Nuke.Common.Tooling.ProcessTasks.<>c__DisplayClass6_0.<StartProcess>b__1(String x) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 82
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(String toolPath, String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 customLogger, Func`2 outputFilter) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 126
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(String toolPath, ArgumentStringHandler& arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 customLogger) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 85
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNet(ArgumentStringHandler& arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 logger, Action`1 exitHandler) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 43
   at Build.<>c.<get_Restore>b__11_1() in E:\code\me\nuke\build\Build.cs:line 43
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
```
