### ISSUE TITLE
Unable to run build published as an exe

### ISSUE THREAD

**Issue by xumix** [nuke-build/nuke#1206]
### Usage Information

nuke 6.2.1 / sdk 6.0.4 / net6 / win-x64

### Description

Since .net tools do not in fact suport private nuget feeds, I had to resort to .exe publishing.
But when I try to run the published exe it can't find the required sdk(or tries to install it anyway)
```
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RootNamespace></RootNamespace>
        <NoWarn>CS0649;CS0169</NoWarn>
        <NukeTelemetryVersion>1</NukeTelemetryVersion>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>pp3-build</ToolCommandName>
        <PackageId>Pp3.BuildTool</PackageId>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>
```
```
PS D:\Projects\Pp3\artifacts\pp3-build> dotnet --list-sdks
6.0.410 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
```
```
PS D:\Projects\Pp3\artifacts\pp3-build> .\_build.exe DeployArtifacts
15:11:49 [INF] > C:\Windows\System32\cmd.exe /c "powershell C:\Users\123\.nuke\dotnet-install.ps1 -InstallDir C:\Users\123\.nuke\dotnet-runtime\6.0.4 -NoPath -Runtime dotnet -Version 6.0.4"
Process 'cmd.exe' exited with code 1.
   > C:\Windows\System32\cmd.exe /c "powershell C:\Users\123\.nuke\dotnet-install.ps1 -InstallDir C:\Users\123\.nuke\dotnet-runtime\6.0.4 -NoPath -Runtime dotnet -Version 6.0.4"
   @ D:\Projects\Pp3\artifacts\pp3-build
Error output:
   C:\Users\123\.nuke\dotnet-install.ps1 : File C:\Users\123\.nuke\dotnet-install.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```

### Reproduction Steps

1) create a build project and a target
2) set global.json
```
{
  "sdk": {
    "version": "6.0.410",
    "rollForward": "latestFeature"
  }
}
```
3) dotnet publish -r win-x64 --self-contained -o ./artifacts/build
4) run the resulting file `PS D:\Projects\Pp3\artifacts\pp3-build> .\_build.exe DeployArtifacts`
5) get the error

### Expected Behavior

Running as expected

### Actual Behavior

```
15:11:49 [INF] > C:\Windows\System32\cmd.exe /c "powershell C:\Users\123\.nuke\dotnet-install.ps1 -InstallDir C:\Users\123\.nuke\dotnet-runtime\6.0.4 -NoPath -Runtime dotnet -Version 6.0.4"
Process 'cmd.exe' exited with code 1.
   > C:\Windows\System32\cmd.exe /c "powershell C:\Users\123\.nuke\dotnet-install.ps1 -InstallDir C:\Users\123\.nuke\dotnet-runtime\6.0.4 -NoPath -Runtime dotnet -Version 6.0.4"
   @ D:\Projects\Pp3\artifacts\pp3-build
Error output:
   C:\Users\123\.nuke\dotnet-install.ps1 : File C:\Users\123\.nuke\dotnet-install.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```

### Could you help with a pull-request?

No

**Comment by xumix** [comment]
Ok, so I updated to Nuke 7.0.2 and the exe now runs, but now it can't get GitVersion package.
I tried all the variations of `PackageDownload` and `PackageReference` in the build project file.
```
<ItemGroup>
      <PackageDownload Include="GitVersion.CommandLine" Version="[5.12.0]" />
      <PackageDownload Include="GitVersion.Tool" Version="[5.12.0]" />
    </ItemGroup>
```

```
PS D:\Projects\Pp3\artifacts\pp3-build> .\_build.exe DeployArtifacts
​
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
​
NUKE Execution Engine version 7.0.2 (Windows,.NETCoreApp,Version=v6.0)
​
15:33:22 [WRN] Could not inject value for Build.GitVersion
System.Exception: Missing package reference/download.
Run one of the following commands:
  - nuke :add-package GitVersion.Tool --version 5.12.0
  - nuke :add-package GitVersion.CommandLine --version 5.12.0
 ---> System.ArgumentException: Could not find package 'GitVersion.Tool' or 'GitVersion.CommandLine' using:
 - Embedded packages directory at 'C:\Users\123\.nuke\packages'
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Utilities/Assert.cs:line 73
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 85
   --- End of inner exception stack trace ---
   at Nuke.Common.Assert.Fail(String message, Exception exception) in /_/source/Nuke.Utilities/Assert.cs:line 28
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 145
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 29
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework) in /_/source/Nuke.Common/Tools/GitVersion/GitVersionTasks.cs:line 28
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ProcessToolPath() in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 176
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 55
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 85
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 124
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tools/GitVersion/GitVersionAttribute.cs:line 47
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/Execution/Extensibility/ValueInjectionAttributeBase.cs:line 26
```

**Comment by matkoch** [comment]
Please check if `EmbedPackagesForSelfContainedTask` is executed or if it's not, then why.

**Comment by xumix** [comment]
> Please check if `EmbedPackagesForSelfContainedTask` is executed or if it's not, then why.

Could you please tell me how to do this?

**Comment by matkoch** [comment]
With binary logs and MSBuild Structured Log Viewer for instance.

**Comment by xumix** [comment]
> With binary logs and MSBuild Structured Log Viewer for instance.

Do you maybe have a troubleshooting docs or some links to get started? I'm kinda new to MSBuild internals

**Comment by matkoch** [comment]
I'd recommend this: https://www.youtube.com/watch?v=CNkGEBmZ1yo
