### ISSUE TITLE
Invalid CLI Parameters should fail the build

### ISSUE THREAD

**Issue by MartinSGill** [nuke-build/nuke#1212]
### Usage Information

NUKE Execution Engine version 7.0.2 (Windows,.NETCoreApp,Version=v6.0)

### Description

When running a build placing "target" names in the wrong location on the CLI causes the build to fail but not return an error code.

When running this in a pipeline this means the build step appears to succeed, even though it failed it the help message.

### Reproduction Steps

Place the "target" (b) after parameter value (a) on the command line:

```powershell
PS> ./build.ps1 --target-environment a b
PowerShell Core version 7.3.6
Microsoft (R) .NET SDK version 7.0.306
14:01:40 [WRN] Could not inject value for Build.TargetEnvironment
System.Exception: Resolving argument 'TargetEnvironment' failed.
Value 'a' could not be converted to 'TargetEnvironment'
Arguments were:
  [0] = --target-environment
  [1] = a
  [2] = b
at Nuke.Common.Assert.Fail(String message, Exception exception) in /_/source/Nuke.Utilities/Assert.cs:line 28
   at Nuke.Common.ArgumentParser.ConvertArgument(String argumentName, String[] values, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Utilities/ArgumentParser.cs:line 140
# ...
PS> $LASTEXITCODE
0
```

### Expected Behavior

Build must fail.

Also.. usage instructions should probably contain a "usage" line, instead of only listing target names and parameters.

e.g.

```powershell
PS> ./build.ps1 --help
#  ...
NUKE Execution Engine version 7.0.2 (Windows,.NETCoreApp,Version=v6.0)
​
Usage: ./build.ps1 [[--target ]Target [Target2]] [Parameters]

Targets (with their direct dependencies):
# ...
``` 

That way people will know to place the targets first.

### Actual Behavior

Build issues warning and continues

### Known Workarounds

explicity use `--target b` for targets to invoke.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
I don't think this behavior is going to be changed. You should be able to make `TargetEnvironment` a required parameter (via attribute or target definition). That should fail the build.

**Comment by Otiel** [comment]
Any chance you would reconsider this?

When the parameter has a default value defined, like:
```
[Parameters]
readonly Configuration Configuration = Configuration.Debug;
```

making the parameter required has no consequence since Nuke will use the default value if it cannot parse the argument:

```
> nuke build --configuration foo
18:04:43 [WRN] Could not inject value for MyNukeBuild._configurationParameter
System.Exception: Resolving argument 'Configuration' failed.
Value 'foo' could not be converted to 'Configuration'
Arguments were:
  [0] = build
  [1] = --configuration
  [2] = foo
   at Nuke.Common.Assert.Fail(String message, Exception exception) in /_/source/Nuke.Utilities/Assert.cs:line 28
   at Nuke.Common.ArgumentParser.ConvertArgument(String argumentName, String[] values, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Utilities/ArgumentParser.cs:line 140
   at Nuke.Common.ArgumentParser.GetNamedArgument(String argumentName, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Utilities/ArgumentParser.cs:line 81
   at Nuke.Common.ParameterService.GetCommandLineArgument(String argumentName, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 172
   at Nuke.Common.ParameterService.<GetParameter>g__TryFromCommandLineArguments|18_0(<>c__DisplayClass18_0&) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 143
   at Nuke.Common.ParameterService.GetParameter(String parameterName, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 162
   at Nuke.Common.ParameterService.GetFromMemberInfo(MemberInfo member, Type destinationType, Func`4 provider) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 136
   at Nuke.Common.ParameterService.GetParameter[T](MemberInfo member, Type destinationType) in /_/source/Nuke.Build/Execution/ParameterService.Statics.cs:line 41
   at Nuke.Common.ParameterAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/ParameterAttribute.cs:line 61
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/Execution/Extensibility/ValueInjectionAttributeBase.cs:line 26
​
╬══════════
║ Build
╬══
​
18:04:43 [INF] > "C:\Program Files\dotnet\dotnet.exe" build C:\Test.sln --configuration Debug --no-restore --verbosity quiet
18:04:43 [DBG] MSBuild version 17.8.3+195e7f5a3 for .NET
18:04:45 [DBG]
18:04:45 [DBG] Build succeeded.
18:04:45 [DBG]     0 Warning(s)
18:04:45 [DBG]     0 Error(s)
18:04:45 [DBG]
18:04:45 [DBG] Time Elapsed 00:00:02.69
​
╬══════════════════════
║ Errors & Warnings
╬═════════════
​
[WRN] : Could not inject value for MyNukeBuild._configurationParameter
​
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Build              Succeeded       0:02
───────────────────────────────────────
Total                              0:02
═══════════════════════════════════════
​
Build succeeded on 22/05/2024 18:04:45. ＼（＾ᴗ＾）／
```

**Comment by paralaxsd** [comment]
I'd agree that the inability to detect or fail on param conversion failures is a weakness of the current API.  
For reference to others, since I've just worked on a generic mechanism to tackle optional enumeration arguments, here's my approach:  

1.) Assuming we have a custom Nuke enumeration type such as:
```csharp
[TypeConverter(typeof(TypeConverter<PackageSource>))]
class PackageSource : Enumeration { /* ... */ }
```
2.) In your Build class, define the enum parameter via a nullable string and access the real enum value by converting it. The conversion method can be put into a shared library.
```csharp
    [Parameter("Some param description")]
    readonly string? PackageSource;

    PackageSource PackageSourceValue => PackageSource is { } ? 
        ConvertToNukeEnumOrThrow<PackageSource>(PackageSource) : global::PackageSource.SomeDefaultValue;

    static TNukeEnum ConvertToNukeEnumOrThrow<TNukeEnum>(
        string text, [CallerArgumentExpression(nameof(text))] string paramName = "")
        where TNukeEnum : Enumeration
    {
        var converter = TypeDescriptor.GetConverter(typeof(TNukeEnum));
        var exMsg = $"Parameter {paramName}: unable to convert '{text}' into enum type '{typeof(TNukeEnum).Name}'.";

        try
        {
            if (converter.ConvertFrom(text) is TNukeEnum res)
            {
                return res;
            }
        }
        catch (Exception e)
        {
            throw new ArgumentException(exMsg, e);
        }

        throw new ArgumentException(exMsg);
    }
```
3.) In your build class override `OnBuildInitialized` and trigger param conversion if the parameter was set by endusers. This approach could of course also be generalized and put into a shared library.
```csharp
    protected override void OnBuildInitialized()
    {
        if (PackageSource is { })
        {
            _ = PackageSourceValue;  
        }

        base.OnBuildInitialized();
    }
```
