### ISSUE TITLE
Clean nuke :setup fails on macOS w. version 7.03

### ISSUE THREAD

**Issue by veggerby** [nuke-build/nuke#1237]
### Usage Information

Nuke 7.0.3, .net sdk 7.0.306

### Description

When doing a clean solution with console application using .net 7 (on macOS Ventura 13.5) using Nuke 7.0.3 it fails with `Object reference not set to an instance of an object`

### Reproduction Steps

When doing a clean project:

```sh
dotnet new sln
dotnet new console --name test-nuke
dotnet sln add test-nuke
nuke :setup #use defaults
nuke
```

it fails with:

```
nuke-test> nuke
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
Microsoft (R) .NET SDK version 7.0.306
Object reference not set to an instance of an object.
```

Downgrade to v. 7.0.2 in `_build.csproj`, output:

```
nuke-test> nuke
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
Microsoft (R) .NET SDK version 7.0.306

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 7.0.2 (OSX,.NETCoreApp,Version=v6.0)


╬════════════
║ Restore
╬═══


╬════════════
║ Compile
╬═══


═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Succeeded     < 1sec
Compile            Succeeded     < 1sec
───────────────────────────────────────
Total                            < 1sec
═══════════════════════════════════════

Build succeeded on 8/25/2023 10:33:50 AM. ＼（＾ᴗ＾）／
```

### Expected Behavior

Same as with 7.0.2

### Actual Behavior

Fails with `Object reference not set to an instance of an object`, and not possible to hit any breakpoints if trying to debug in VS Code, and does not trip on Exception if Breakpoints: All exceptions is enabled

### Regression?

Yes, works with 7.0.2 and also 6.*

### Known Workarounds

Downgrade to 7.0.2

### Could you help with a pull-request?

No

**Comment by ffMathy** [comment]
I can reproduce this as well 😄 

I am using dotnet version `7.0.100` on Mac Ventura 13.5.1.

**Comment by matkoch** [comment]
Ah, Lego people! I'm missing two parts on my Millennium Falcon, could you help me out?
![Microsoft Edge-lego millennium falcon - Google Search-2023-08-25-wkhzFnjj@2x](https://github.com/nuke-build/nuke/assets/5005566/70c6872e-106d-4b96-b205-ea84dd92a2e3)

**Comment by veggerby** [comment]
> Ah, Lego people! I'm missing two parts on my Millennium Falcon, could you help me out? ![Microsoft Edge-lego millennium falcon - Google Search-2023-08-25-wkhzFnjj@2x](https://user-images.githubusercontent.com/5005566/263240536-70c6872e-106d-4b96-b205-ea84dd92a2e3.png)

Sure (at least indirectly) https://www.lego.com/en-us/service/replacementparts/missing/location

**Comment by matkoch** [comment]
Checked that, but the pieces are not listed :)

**Comment by BusHero** [comment]
It occurs on Windows as well

**Comment by butterworld** [comment]
Stack trace when trying to execute with --verbosity verbose (I'm also on Windows).
`
12:56:05.114 | V |                      | ArgumentsFromParametersFile.OnBuildCreated (150)
12:56:05.165 | V |                      | Target-unrelated exception was thrown
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nuke.Common.Execution.ArgumentsFromParametersFileAttribute.<>c__DisplayClass0_0.<OnBuildCreated>g__ConvertValue|2(Type scalarType, String value) in /_/source/Nuke.Build/Execution/Extensions/ArgumentsFromParametersFileAttribute.cs:line 52
   at Nuke.Common.Execution.ArgumentsFromParametersFileAttribute.<>c__DisplayClass0_1.<OnBuildCreated>b__6(String x) in /_/source/Nuke.Build/Execution/Extensions/ArgumentsFromParametersFileAttribute.cs:line 37
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Nuke.Common.Execution.ArgumentsFromParametersFileAttribute.<>c__DisplayClass0_0.<OnBuildCreated>g__ConvertToArguments|0(String profile, String name, String[] values) in /_/source/Nuke.Build/Execution/Extensions/ArgumentsFromParametersFileAttribute.cs:line 37
   at Nuke.Common.Execution.ArgumentsFromParametersFileAttribute.<>c__DisplayClass0_0.<OnBuildCreated>b__3(ValueTuple`3 x) in /_/source/Nuke.Build/Execution/Extensions/ArgumentsFromParametersFileAttribute.cs:line 58
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Nuke.Common.Execution.ArgumentsFromParametersFileAttribute.OnBuildCreated(IReadOnlyCollection`1 executableTargets) in /_/source/Nuke.Build/Execution/Extensions/ArgumentsFromParametersFileAttribute.cs:line 58
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Utilities/Collections/Enumerable.ForEach.cs:line 20
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Build/Execution/BuildManager.cs:line 55
`

**Comment by matkoch** [comment]
it's alright, lets focus on the missing lego pieces

**Comment by BusHero** [comment]
the bug appears only when the default solution is set up(aka. the field `Solution` inside `.nuke\parameters.json` has a value)
![image](https://github.com/nuke-build/nuke/assets/24370515/990991b0-671d-45bf-b6f3-545d7c912357)

**Comment by BusHero** [comment]
I've found the offender:
![image](https://github.com/nuke-build/nuke/assets/24370515/d3b4492f-9e75-45a7-958f-d79b45cb025a)
File is located under `source\Nuke.Build\Execution\Extensions\ArgumentsFromParametersFileAttribute.cs`.
`ConvertValue` will throw when `scalarType` is `null`. `scalarType` will be null when the default solution is set up
