### ISSUE TITLE
DotNetTest with testcontainers.net throws IOException

### ISSUE THREAD

**Issue by jeisenbach-schulzst** [nuke-build/nuke#1258]
### Usage Information

NUKE version 7.0.5 / .NET SDK Version 7.0.306 / net7.0 / Windows 10

### Description

First of all: Thanks for NUKE, so far it is an great dev experience!

I am working on an ASP.NET Core application that uses xUnit and testcontainers.net to create an Docker image and then build and run a container of that image. Everythings works fine from the command line and also in an Azure Pipeline.

Now I'm trying to convert the azure pipeline yaml to a NUKE build, but I keep getting the follow IOException when trying to execute DotNetTest

### Reproduction Steps

The target:

```
    Target Test => _ => _
        .DependsOn(Compile)
        .Executes(() =>
        {
            DotNetTest(s => s
                .EnableNoRestore()
                .SetProcessWorkingDirectory(RootDirectory)
                .SetConfiguration(Configuration)
                .SetProjectFile(Solution));
        });
```
The log says:

```
D | Test                 |    System.IO.IOException : Cannot create Docker image tar archive.
D | Test                 | ---- System.IO.IOException : The process cannot access the file 'path\to\repo\.nuke\temp\build.2023-09-12_10-14-25.log' because it is being used by another process.
D | Test                 |   Stapelverfolgung:
D | Test                 |      at DotNet.Testcontainers.Images.DockerfileArchive.Tar(CancellationToken ct)
D | Test                 |    at DotNet.Testcontainers.Clients.DockerImageOperations.BuildAsync(IImageFromDockerfileConfiguration configuration, ITarArchive dockerfileArchive, CancellationToken ct)
D | Test                 |    at DotNet.Testcontainers.Clients.TestcontainersClient.BuildAsync(IImageFromDockerfileConfiguration configuration, CancellationToken ct)
D | Test                 |    at DotNet.Testcontainers.Images.FutureDockerImage.UnsafeCreateAsync(CancellationToken ct)
D | Test                 |    at DotNet.Testcontainers.Images.FutureDockerImage.CreateAsync(CancellationToken ct)
D | Test                 | ----- Inner Stack Trace -----
D | Test                 |    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
D | Test                 |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
D | Test                 |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
D | Test                 |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
D | Test                 |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
D | Test                 |    at DotNet.Testcontainers.Images.DockerfileArchive.Tar(CancellationToken ct)
```

I also tried to call the dotnet command manually (using CliWrap), but the problem remains
```
            await Cli.Wrap("dotnet")
                .WithWorkingDirectory(RootDirectory)
                .WithArguments(args =>
                {
                    args
                        .Add("test")
                        .Add(Solution)
                        .Add("-c")
                        .Add("Debug");
                })
                .ExecuteAsync();
```

It seems that the DockerfileArchive class from testcontainers.net tries to access the log file (through the logger)? But I have no ideas why. Any ideas?

Thanks and BR
Jens

### Expected Behavior

DotNetTest succeeds (like from the CMD)

### Actual Behavior

DotNetTest fails

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Doesn't seem like an issue for this repo, but rather for testcontainers.
