### ISSUE TITLE
NET8 Binary Formatter deprecation

### ISSUE THREAD

**Issue by xevilmaxx** [nuke-build/nuke#1278]
### Usage Information

Nuke.Common 7.0.6, Windows 11, NET8.0 RC2

### Description

```
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Nuke.Common.Tooling.SettingsEntityExtensions.NewInstance[T](T settingsEntity) in /_/source/Nuke.Tooling/SettingsEntity.NewInstance.cs:line 23
   at Nuke.Common.Tools.DotNet.DotNetRestoreSettingsExtensions.SetProjectFile[T](T toolSettings, String projectFile) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 6715
   at Build.<get_Restore>b__66_2(DotNetRestoreSettings _) in C:\Users\Maxym.Oboyshev\source\repos\ParkO_V3\branches\dev\Net8Porting\DEPLOY\Nuke\NukeDeploy\NukeDeploy\Build.cs:line 297
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetRestore(Configure`1 configurator) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 364
   at Build.<get_Restore>b__66_1() in C:\Users\Maxym.Oboyshev\source\repos\ParkO_V3\branches\dev\Net8Porting\DEPLOY\Nuke\NukeDeploy\NukeDeploy\Build.cs:line 297
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
```

### Reproduction Steps

```csharp
Target Restore => _ => _
    .DependsOn(Clean)
    .Executes(() =>
    {

        if (IsLegacyWindowsFramework == true)
        {
            Log.Warning("We wont do separate restore for Windows Framework");
            return;
        }

        //Implicit Else condition

        Log.Information("Creating folder if not exists in: " + PublishDir);
        EnsureExistingDirectory(PublishDir);

        DotNetRestore(_ => _
            .SetProjectFile(ProjectFileFullPath)
            //should help prevent errors in Offline mode
            .SetIgnoreFailedSources(true)
        );

    });
```

### Expected Behavior

Run

### Actual Behavior

Can't run

### Known Workarounds

Replace BinaryFormatter with an alternative as stated here:
[https://aka.ms/binaryformatter](https://aka.ms/binaryformatter)

### Could you help with a pull-request?

No

**Comment by ITaluone** [comment]
Dup: #818
