### ISSUE TITLE
DotNetTasks.DotNetPublish fails with NRE when upgrading Nuke.Common from 7.0.0 to 7.0.1

### ISSUE THREAD

**Issue by sunilshahi** [nuke-build/nuke#1283]
### Usage Information

NUKE version 7.0.1/ dotnet sdk 7.0.403 / TargetFramework net7.0/OS windows

### Description

I have this build target. 

```
Target Publish => _ => _
    .DependsOn(Clean, Compile)
    .Executes(() =>
    {
        DotNetPublish(_ => _
            .SetProject(WebUIProject)
            .EnableNoRestore()
            .EnableNoBuild()
            .SetConfiguration(Configuration));
    });
```

This code works until Nuke.Common version 7.0.0 but if I update to version 7.0.1 to 7.0.6, I am seeing following error. 

```
10:15:32 [ERR] Target Publish has thrown an exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nuke.Common.ProjectModel.Project.op_Implicit(Project project) in /_/source/Nuke.SolutionModel/Project.cs:line 41
   at Build.<get_Publish>b__16_2(DotNetPublishSettings _) in C:\Users\SunilShahi\source\repos\Locometer\build\Build.cs:line 90
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetPublish(Configure`1 configurator) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 929
   at Build.<get_Publish>b__16_1() in C:\Users\SunilShahi\source\repos\Locometer\build\Build.cs:line 90
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
```

![image](https://github.com/nuke-build/nuke/assets/14316938/4138aa1d-18a6-4771-ba29-fcfc7b7a8722)

### Reproduction Steps

mentioned in description.

### Expected Behavior

build should succeed, or perhaps display better error message. 

### Actual Behavior

Build fails with error mentioned in description.

### Regression?

worked until Nuke.Common 7.0.0

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Unclear if you've tried the latest version.

**Comment by sunilshahi** [comment]
The issue is happening in 7.0.6 as well. I did not put that in heading but its in description.

**Comment by sunilshahi** [comment]
@matkoch This is happening in 7.0.6.
