### ISSUE TITLE
Package 'Paket' is referenced with multiple versions. Use NuGetPackageResolver and SetToolPath

### ISSUE THREAD

**Issue by mkay-sh** [nuke-build/nuke#1301]
### Usage Information

Nuke 7.0.6 / .NET SDK 8.0.11 / net8.0 / Windows 11 23H2

### Description

After installing the .NET 8 SDK nuke fails to resolve Paket. It might be the same for other packages, but I did not test that.
It fails too for projects targeting other .NET versions after the installation of the new .NET SDK.
For some reason the new SDK creates an additional file in global packages folder.
In my `globalPackagesFolder(USER/.nuget/packages)/paket/8.0.0` there is a `paket.8.0.0.nupkg` and a `Paket.nupkg` file. Nuke fails because it is not able to resolve to the correct nupkg file. The two files have the same content except for the name.

### Reproduction Steps

1. Delete all paket versions from your global packages folder.

2. Create a new tool manifiest `dotnet new tool-manifest`

3. Install paket `dotnet tool install paket`
4. Create a new nuke build with the default settings `nuke :setup`
5. Add paket to the build project `nuke :add-package Paket --version 8.0.0`
6. Add a paket restore to the restore target

```cs
    Target Restore => _ => _
        .Executes(() =>
        {
            PaketTasks.PaketRestore();
        });
```
7. Run `nuke restore`

### Expected Behavior

Nuke should be able to resolve a correct paket version.

### Actual Behavior

Nuke fails with an exception.
```
System.Exception: Missing package reference/download.
Run one of the following commands:
  - nuke :add-package Paket --version 8.0.0
 ---> System.InvalidOperationException: Package 'Paket' is referenced with multiple versions. Use NuGetPackageResolver and SetToolPath.
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Tooling.NuGetPackageResolver.GetGlobalInstalledPackage(String packageId, VersionRange versionRange, AbsolutePath packagesConfigFile, Nullable`1 includePrereleases) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 217
   at Nuke.Common.Tooling.NuGetPackageResolver.GetGlobalInstalledPackage(String packageId, String version, AbsolutePath packagesConfigFile) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 182
   at Nuke.Common.Tooling.NuGetPackageResolver.<>c__DisplayClass3_0.<GetLocalInstalledPackagesFromAssetsFile>b__1(ValueTuple`2 x) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 100
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.SingleOrDefaultOrError[T](IEnumerable`1 enumerable, Func`2 predicate, String message) in /_/source/Nuke.Utilities/Collections/Enumerable.SingleOrDefaultOrError.cs:line 19
   --- End of inner exception stack trace ---
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.SingleOrDefaultOrError[T](IEnumerable`1 enumerable, Func`2 predicate, String message) in /_/source/Nuke.Utilities/Collections/Enumerable.SingleOrDefaultOrError.cs:line 23
   at Nuke.Common.Tooling.NuGetPackageResolver.GetLocalInstalledPackage(String packageId, AbsolutePath packagesConfigFile, String version, Boolean resolveDependencies) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 30
   at Nuke.Common.Tooling.NuGetToolPathResolver.<>c__DisplayClass5_1.<GetPackageDirectory>b__5() in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 92
   at Nuke.Common.Tooling.NuGetToolPathResolver.<>c.<GetPackageDirectory>b__5_1(Func`1 x) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 102
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 85
   --- End of inner exception stack trace ---
   at Nuke.Common.Assert.Fail(String message, Exception exception) in /_/source/Nuke.Utilities/Assert.cs:line 28
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 145
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 29
   at Nuke.Common.Tools.Paket.PaketTasks.get_PaketPath() in /_/source/Nuke.Common/Tools/Paket/Paket.Generated.cs:line 35
   at Nuke.Common.Tools.Paket.PaketRestoreSettings.get_ProcessToolPath() in /_/source/Nuke.Common/Tools/Paket/Paket.Generated.cs:line 506
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 58
   at Nuke.Common.Tools.Paket.PaketTasks.PaketRestore(PaketRestoreSettings toolSettings) in /_/source/Nuke.Common/Tools/Paket/Paket.Generated.cs:line 167
   at Build.<>c.<get_Restore>b__5_1() in C:\projects\mkay\nuke-repro\build\Build.cs:line 37
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
```

### Known Workarounds

It works again if you delete the `Paket.nupkg` file in your global packages folder. And I found no other side effects after deleting the file. Paket still works fine and if I run `dotnet tool restore` again the file ist not created again. It is only created again after I completely delete the paket folder in the global packages folder.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Sounds more like a bug in Paket.

**Comment by mkay-sh** [comment]
For me it looks like the two nupkg files in the global packages folder are created for all dotnet tools I install. For example in dotnet-ef there is a `dotnet-ef.8.0.0.nupkg` and a `dotnet.nupkg` file as well. Maybe there are some changes in the handling of dotnet tools with the new sdk?

**Comment by PascalSenn** [comment]
i run into the same issue. 

I believe the problem is in this bit:

https://github.com/nuke-build/nuke/blob/b94f4c110095b84e0173f44af5d2dc0579e9b2db/source/Nuke.Tooling/NuGetPackageResolver.cs#L200-L219

the discovered packages are
```
[0] = {string} "/Users/p/.nuget/packages/barista/1.0.0-preview.16/barista.1.0.0-preview.16.nupkg"
[1] = {string} "/Users/p/.nuget/packages/barista/7.10.1/barista.7.10.1.nupkg"
[2] = {string} "/Users/p/.nuget/packages/barista/7.10.1/Barista.nupkg"
[3] = {string} "/Users/p/.nuget/packages/barista/7.3.5/barista.7.3.5.nupkg"
[4] = {string} "/Users/p/.nuget/packages/barista/8.0.0/barista.8.0.0.nupkg"
[5] = {string} "/Users/p/.nuget/packages/barista/8.0.0/Barista.nupkg"
[6] = {string} "/Users/p/.nuget/packages/barista/1.0.0-preview.8/barista.1.0.0-preview.8.nupkg"
[7] = {string} "/Users/p/.nuget/packages/barista/1.4.2/barista.1.4.2.nupkg"
[8] = {string} "/Users/p/.nuget/packages/barista/1.4.4/barista.1.4.4.nupkg"
[9] = {string} "/Users/p/.nuget/packages/barista/1.0.0-preview.25/barista.1.0.0-preview.25.nupkg"
```
So it discovered the .net 8 one twice:
```
[4] = {string} "/Users/p/.nuget/packages/barista/8.0.0/barista.8.0.0.nupkg"
[5] = {string} "/Users/p/.nuget/packages/barista/8.0.0/Barista.nupkg"
```

Which leads to the following `candidatePackages`:
```
[0] = {NuGetPackageResolver.InstalledPackage} Barista.8.0.0
[1] = {NuGetPackageResolver.InstalledPackage} Barista.8.0.0
[2] = {NuGetPackageResolver.InstalledPackage} Barista.7.10.1
[3] = {NuGetPackageResolver.InstalledPackage} Barista.7.10.1
[4] = {NuGetPackageResolver.InstalledPackage} Barista.7.3.5
[5] = {NuGetPackageResolver.InstalledPackage} Barista.1.4.4
[6] = {NuGetPackageResolver.InstalledPackage} Barista.1.4.2
[7] = {NuGetPackageResolver.InstalledPackage} Barista.1.0.0-preview.25
[8] = {NuGetPackageResolver.InstalledPackage} Barista.1.0.0-preview.16
[9] = {NuGetPackageResolver.InstalledPackage} Barista.1.0.0-preview.8
```

which then leads to the execption here, because there are two canidates that match:

https://github.com/nuke-build/nuke/blob/b94f4c110095b84e0173f44af5d2dc0579e9b2db/source/Nuke.Tooling/NuGetPackageResolver.cs#L219


@matkoch  would just switching to `FirstOrDefault` there be an option?

**Comment by DWIAltonaAnalytics** [comment]
It does not matter which nuget-package is involved, if for some reason the global package folder contains a file without version info in the name `some-nuget.nupkg` *and* one with it `some-nuget.X.Y.Z.nupkg` and `X.Y.Z` is the same version for both, nuke will fail with the above mentioned error.
One could argue this is a bug in NuGet, but I think this behavior is to be expected?

(I have the same issue with MinVer, because I installed the CLI once with a specific version and once without, which downloaded it twice with different file names as it seems)
