### ISSUE TITLE
Nuke Global Tool Fails To Run

### ISSUE THREAD

**Issue by pfesenmeier** [nuke-build/nuke#1339]
### Usage Information

8.0.0 / 8.0.200 / net8.0 / Ubuntu 22.04.4 LTS

### Description

Nuke global tool errors when invoked

### Reproduction Steps

```
cd empydirectory
dotnet tool install nuke.globaltool --global
nuke --help
> Sequence contains more than one matching element
```

### Expected Behavior

Tool to run successfully

### Actual Behavior

See error above. 
Also, I can get this exception when running a `build.sh` file from an existing project (that was created and works on Windows).
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Microsoft (R) .NET SDK version 8.0.200
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Nuke.Common.EnvironmentInfo' threw an exception.
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.EnvironmentInfo..cctor() in /_/source/Nuke.Utilities/EnvironmentInfo.Variables.cs:line 34
   --- End of inner exception stack trace ---
   at Nuke.Common.ParameterService.<>c.<.cctor>b__41_0() in /_/source/Nuke.Build/Execution/ParameterService.Statics.cs:line 17
   at Nuke.Common.ParameterService.get_ArgumentsParser() in /_/source/Nuke.Build/Execution/ParameterService.cs:line 34
   at Nuke.Common.ParameterService.HasCommandLineArgument(String argumentName) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 189
   at Nuke.Common.ParameterService.<GetParameter>g__TryFromCommandLineArguments|18_0(<>c__DisplayClass18_0&) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 143
   at Nuke.Common.ParameterService.GetParameter(String parameterName, Type destinationType, Nullable`1 separator) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 162
   at Nuke.Common.ParameterService.GetFromMemberInfo(MemberInfo member, Type destinationType, Func`4 provider) in /_/source/Nuke.Build/Execution/ParameterService.cs:line 136
   at Nuke.Common.ParameterService.GetParameter[T](MemberInfo member, Type destinationType) in /_/source/Nuke.Build/Execution/ParameterService.Statics.cs:line 41
   at Nuke.Common.ParameterService.GetParameter[T](Expression`1 expression) in /_/source/Nuke.Build/Execution/ParameterService.Statics.cs:line 29
   at Nuke.Common.NukeBuild.GetRootDirectory() in /_/source/Nuke.Build/NukeBuild.Statics.cs:line 96
   at Nuke.Common.NukeBuild..cctor() in /_/source/Nuke.Build/NukeBuild.Statics.cs:line 23
   --- End of inner exception stack trace ---
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Build/NukeBuild.cs:line 78
   at Build.MyBuild.Main() in /home/me/myproject/build/Build.cs:line 29
```

### Regression?

I am not sure.

### Known Workarounds

none yet.

### Could you help with a pull-request?

Yes

**Comment by willsmith9182** [comment]
Do you perhaps have duplicate ENV variables defined in your workflow?

**Comment by willsmith9182** [comment]
[based on the exception stack](https://github.com/nuke-build/nuke/blob/f76db123ceb2a76bb02a5598c701ec7d336a390d/source/Nuke.Utilities/EnvironmentInfo.Variables.cs#L34C5-L34C122), it would appear you have multiple PATH variables?

the code in question would be:
```
private static readonly string s_pathVariableName = Variables.Single(x => x.Key.EqualsOrdinalIgnoreCase("PATH")).Key;
```
Note that this is a case-insensitive check so casing could be the issue here.

**Comment by pfesenmeier** [comment]
@willsmith9182 bingo. thank you.
