### ISSUE TITLE
Exception in Rider for Plugin 2024.1

### ISSUE THREAD

**Issue by MartinSGill** [nuke-build/nuke#1364]
### Usage Information

Rider 2024.1

### Description

Exception thrown when plugin loaded.

### Reproduction Steps

Start Rider

### Expected Behavior

No Exceptions

### Actual Behavior

com.intellij.diagnostic.PluginException: Please, do not use constructor injection: it slows down initialization and may lead to performance problems (parameterType=com.intellij.execution.RunManager, instanceClass=com.jetbrains.rider.plugins.nuke.professional.runConfigurations.NukeRunConfigurationManager). See https://plugins.jetbrains.com/docs/intellij/plugin-services.html for details. [Plugin: com.intellij.rider.plugins.nuke]
	at com.intellij.serviceContainer.ComponentManagerResolver.resolveDependency(ComponentManagerResolver.kt:40)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.resolveArguments(instantiate.kt:256)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.doFindConstructorAndArguments(instantiate.kt:200)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.findConstructorAndArguments(instantiate.kt:133)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.findConstructorAndArguments(instantiate.kt:91)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:80)
	at com.intellij.serviceContainer.InstantiateKt.instantiateWithContainer(instantiate.kt:19)
	at com.intellij.serviceContainer.ComponentInstanceInitializer.createInstance$suspendImpl(ComponentInstanceInitializer.kt:19)
	at com.intellij.serviceContainer.ComponentInstanceInitializer.createInstance(ComponentInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.UtilKt.preloadAllInstances(util.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:520)
	at com.intellij.openapi.project.impl.ProjectManagerImplKt$initProject$2$2.invokeSuspend(ProjectManagerImpl.kt:1233)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

### Known Workarounds

Does not appear to have any functional impact

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
2024.1.1 (currently deploying)
