### ISSUE TITLE
On .NET 9, Nuke crashes with PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed

### ISSUE THREAD

**Issue by borland** [nuke-build/nuke#1435]
### Usage Information

8.1.2

### Description

I am preparing for an update of a project from .NET 8 to 9. I am using .NET 9 Release Candidate 2 to prepare for the final release arriving on November 12.

I have updated the `global.json` in my source root to reference .NET 9, and adjusted the TargetFramework in my csproj files.

The software itself works perfectly, but upon attempting to run my nuke build script, it fails with this error

```
07:39:43 [ERR] Target RestoreNugetPackagesForServer has thrown an exception
System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Nuke.Common.Tooling.SettingsEntityExtensions.NewInstance[T](T settingsEntity) in /_/source/Nuke.Tooling/SettingsEntity.NewInstance.cs:line 26
   at Nuke.Common.Tools.DotNet.DotNetRestoreSettingsExtensions.SetProjectFile[T](T toolSettings, String projectFile) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 7573
   at Redacted.Build.<RestoreNugetPackagesForServer>b__168_0(DotNetRestoreSettings s) in C:\Dev\Redacted\build\Build.cs:line 266
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetRestore(Configure`1 configurator) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 364
   at Redacted.Build.RestoreNugetPackagesForServer() in C:\Dev\Redacted\build\Build.cs:line 266
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
```

The failing task is simple:

```csharp
DotNetTasks.DotNetRestore(s => s
    .SetProjectFile(Solution)
    .SetRuntime(Runtime)
    .SetProperty("DisableImplicitNuGetFallbackFolder", true));
```

### Reproduction Steps

As above, it is pretty simple. I will loop back and provide more specific steps to reproduce shortly.

### Expected Behavior

Nuke should not fail with the BinaryFormatter exception

### Actual Behavior

Nuke build should work

### Could you help with a pull-request?

Yes

**Comment by borland** [comment]
Closing as duplicate of https://github.com/nuke-build/nuke/issues/818
