### ISSUE TITLE
BinaryFormatter still in use - .NET 9 failing

### ISSUE THREAD

**Issue by nabeelio** [nuke-build/nuke#1450]
### Usage Information

NUKE 8.1.4, dotnet 9.0.100, Target FW: net9.0, OS: Win 11

### Description

I see #818 is closed.

```
15:49:31 [WRN] Could not inject value for Build.NerdbankVersioning
System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Nuke.Common.Tooling.SettingsEntityExtensions.NewInstance[T](T settingsEntity) in /_/source/Nuke.Tooling/SettingsEntity.NewInstance.cs:line 26
   at Nuke.Common.Tooling.ToolSettingsExtensions.DisableProcessLogOutput[T](T toolSettings) in /_/source/Nuke.Tooling/ToolSettings.Standard.cs:line 103
   at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningAttribute.<>c.<GetValue>b__4_0(NerdbankGitVersioningGetVersionSettings s) in /_/source/Nuke.Common/Tools/NerdbankGitVersioning/NerdbankGitVersioningAttribute.cs:line 27
   at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningTasks.NerdbankGitVersioningGetVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/NerdbankGitVersioning/NerdbankGitVersioning.Generated.cs:line 135
   at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tools/NerdbankGitVersioning/NerdbankGitVersioningAttribute.cs:line 27
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/Execution/Extensibility/ValueInjectionAttributeBase.cs:line 26
```

### Reproduction Steps

I'm calling `dotnet publish` on a project file - publish single file enabled. Using NUKE, the command is:

```
DotNetPublish(
    s => s.SetProject(RootDirectory / "path/to.csproj")
           .SetConfiguration(Configuration)
           .EnablePublishSingleFile()
           .SetVersion(Version)
           .SetAssemblyVersion(Version)
);
```

### Expected Behavior

Binary formatter not used

### Actual Behavior

Shouldn't give an error

### Known Workarounds

Under .NET 8, you could use `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`, but now that's completely removed

### Could you help with a pull-request?

Maybe - just trying to understand the point of the code. Can it be swapped with the System Json?

**Comment by ScarletKuro** [comment]
> Under .NET 8, you could use `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`, but now that's completely removed

add also `<PackageReference Include="System.Runtime.Serialization.Formatters" Version="9.0.0" />` to the `build.csproj`.

**Comment by nabeelio** [comment]
@matkoch what does completed mean in this case? If I submit a PR, will it get merged?

**Comment by matkoch** [comment]
it means it's "completed" and will be shipped in the release with the same version number as the milestone it's been assigned to

**Comment by nabeelio** [comment]
But there's no code changes accompanying it... Like the alternative package hasn't been included or anything, so I'm just curious as to what exactly that means? When someone runs into it, will they also need to search and find this bug and figure out if they need to include the additional package? That is just not the optimal UX
