### ISSUE TITLE
Could not inject value for `GitVersion`

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1453]
### Usage Information

NUKE 9.0.0 / .NET9

### Description

Injecting `GitVersion` via attribute doesn't work anymore in NUKE 9.0.0

### Reproduction Steps

`[GitVersion(NoFetch = true, Framework = "net6.0")] readonly GitVersion GitVersion;`

### Expected Behavior

Injects the value correctly

### Actual Behavior

```txt
10:21:12 [WRN] Could not inject value for Build.GitVersion
System.ArgumentException: Expected object of type 'System.Reflection.PropertyInfo' to be not null (Parameter 'GetType().GetProperty(x.Name)')
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Utilities/Assert.cs:line 73
   at Nuke.Common.Tooling.ToolOptions.<GetSecrets>b__8_0(JProperty x) in /_/source/Nuke.Tooling/ToolOptions.Secrets.cs:line 19
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.IteratorSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereSelectIterator`2.ToList()
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 17
   at Nuke.Common.Tooling.ToolTasks.Run[TResult](ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 39
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 37
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tools/GitVersion/GitVersionAttribute.cs:line 48
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/Execution/Extensibility/ValueInjectionAttributeBase.cs:line 26
```

### Regression?

Yes

### Could you help with a pull-request?

No

**Comment by DemoBytom** [comment]
It also doesn't work if called directly through `GitVersionTasks`
```csharp
_gitVersion = GitVersionTasks
            .GitVersion(s => s
                .SetNoFetch(false)
                .SetNoCache(true)
                .SetFramework("net9.0")
                .DisableProcessOutputLogging())
            .Result;
```
Same exception:
```
System.ArgumentException: Expected object of type 'System.Reflection.PropertyInfo' to be not null (Parameter 'GetType().GetProperty(x.Name)')
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Utilities/Assert.cs:line 73
   at Nuke.Common.Tooling.ToolOptions.<GetSecrets>b__8_0(JProperty x) in /_/source/Nuke.Tooling/ToolOptions.Secrets.cs:line 19
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.IteratorSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereSelectIterator`2.ToList()
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 17
   at Nuke.Common.Tooling.ToolTasks.Run[TResult](ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 39
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 37
   at BuildScript.Build.OnBuildInitialized() in D:\GIT\DemoEngine\build\Build.cs:line 123
   at Nuke.Common.Execution.EventInvoker.OnBuildInitialized(IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan) in /_/source/Nuke.Build/Execution/Extensions/EventInvoker.cs:line 29
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Utilities/Collections/Enumerable.ForEach.cs:line 20
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

Omitting `.SetFramework()` seems to work though:
```csharp
_gitVersion = GitVersionTasks
            .GitVersion(s => s
                .SetNoFetch(false)
                .SetNoCache(true)
                //.SetFramework("net9.0")
                .DisableProcessOutputLogging()
                )
            .Result;
```
Works no problem and seems to produce proper GitVersion.

The problem seems to be general to `SetFramework()` method, as I now get the same error in different tasks that I've been using it, namely - ReportGenerator also now ends in the reported exception:
```chsarp
ReportGenerator(_ => _
                .SetFramework("net5.0")
                [...]
// ArgumentException: Expected object of type 'System.Reflection.PropertyInfo' to be not null (Parameter 'GetType().GetProperty(x.Name)')
```

**Comment by ITaluone** [comment]
Thanks for this workaround. Seems that not every `.SetFramework` is affected, since `DotNetPublish(s => s.SetFramework("xxx"))` is not throwing

**Comment by ITaluone** [comment]
When I have to guess what the problem is, I'd call out this line: `Nuke.Tooling.ToolOptions.Secrets L#19`. I think this `GetType()....` should actually be `x.GetType()..` since we cannot get a property from type `object` with a name of some `JProperty`.

Am I wrong?

**Comment by ITaluone** [comment]
Thank you @matkoch ! 🎉
