### ISSUE TITLE
Dotnet Tasks throw for `TreatWarningsAsErrors` property

### ISSUE THREAD

**Issue by klemmchr** [nuke-build/nuke#1458]
### Usage Information

9.0.1

### Description

```csharp
DotNetBuild(_ =>
    _.SetProjectFile("foo")
        .EnableTreatWarningsAsErrors()
);
```

throws exception

```
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: PropertyName. Path 'Properties.TreatWarningsAsErrors'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Nuke.Common.Tooling.ToolOptions.<>c__DisplayClass2_0.<GetArgument>g__Parse|0(JToken token, Type type) in /_/source/Nuke.Tooling/ToolOptions.Arguments.cs:line 122
   at Nuke.Common.Tooling.ToolOptions.<>c__DisplayClass2_3.<GetArgument>b__10(JProperty x) in /_/source/Nuke.Tooling/ToolOptions.Arguments.cs:line 178
   at System.Linq.Enumerable.IteratorSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereIterator`1.MoveNext()
   at Nuke.Common.Tooling.ToolOptions.<GetArguments>d__8.MoveNext() in /_/source/Nuke.Tooling/ToolOptions.Arguments.cs:line 71
   at System.String.Join(String separator, IEnumerable`1 values)
   at Nuke.Common.Utilities.StringExtensions.JoinSpace(IEnumerable`1 values) in /_/source/Nuke.Utilities/Text/String.Join.cs:line 38
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 21
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetBuild(Configure`1 configurator) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 72
   at Build.<get_Service_Build>b__159_2() in X:\foo\build\Build.Service.cs:line 83
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
```

### Reproduction Steps

Create a target and invoke `DotNetBuild` with `EnableTreatWarningsAsErrors()`.

```csharp
DotNetBuild(_ =>
    _.SetProjectFile("foo")
        .EnableTreatWarningsAsErrors()
);
```

### Expected Behavior

Property `TreatWarningsAsErrors` is set.

### Actual Behavior

Invocation throws exception

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
![2024-11-24-JetBrains Rider-nuke-common – buildBuild cs-005977](https://github.com/user-attachments/assets/a2e08829-8afd-4af6-a477-20e9f26bc3ae)

**Comment by klemmchr** [comment]
After doing some debugging I found out that this is caused when overriding the default serializer options of Newtonsoft.Json. I had this snipped in my Build constructor.

```csharp
JsonConvert.DefaultSettings = () =>
            new JsonSerializerSettings
            {
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy(),
                },
            };
```

Maybe it's worth considering to have dedicated serializer options for Nuke to avoid such issues. IMO it's a bad idea to rely on global options that can be changed by the user causing negative side effects.

**Comment by matkoch** [comment]
feel free to create a pr

**Comment by klemmchr** [comment]
I tried looking into it but I was unable to find any place where the default settings are modified. When passing the Serializer defined in `Options` inside the Parse method for the Tool Arguments a couple of tests fail with the exact stack trace I posted here.

https://github.com/nuke-build/nuke/blob/ecb0cd779dcc5e2e115e17e154934167167228f0/source/Nuke.Tooling/ToolOptions.Arguments.cs#L110-L129
