### ISSUE TITLE
InnoSetupTasks: Custom ProcessToolPath is not taken into account

### ISSUE THREAD

**Issue by christian-heckelmann-np4** [nuke-build/nuke#1467]
### Usage Information

Nuke.Common 9.0.1, .NET8, Windows11

### Description

We are using InnoSetupTasks with a custom Inno Setup Command-Line Compiler (ISCC.exe) path. But the custom path is ignored and the default behaviour (find ISCC.exe with where.exe) is applied - that in our case leads to an error as expected.

```
System.ArgumentException: Could not find 'iscc' via 'C:\Windows\System32\where.exe'.
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Utilities/Assert.cs:line 73
   at Nuke.Common.Tooling.ToolPathResolver.GetPathExecutable(String pathExecutable) in /_/source/Nuke.Tooling/ToolPathResolver.cs:line 57
   at Nuke.Common.Tooling.PathToolAttribute.GetToolPath(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 47
   at Nuke.Common.Tooling.ToolTasks.GetToolPath(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 36
   at Nuke.Common.Tooling.ToolTasks.GetToolPathInternal(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 31
   at Nuke.Common.Tooling.ToolTasks.StartProcess(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 executionTimeout, Nullable`1 outputLogging, Nullable`1 invocationLogging, Action`2 logger, Func`2 outputFilter) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 90
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 21
   at Nuke.Common.Tools.InnoSetup.InnoSetupTasks.InnoSetup(Configure`1 configurator) in /_/source/Nuke.Common/Tools/InnoSetup/InnoSetup.Generated.cs:line 36
   at Build.Build.<get_CreateInstaller>b__46_3() in C:\Projects\Repos\Foo\Build\Build.cs:line 262
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120

```

### Reproduction Steps

```
Target CreateInstaller => _ => _
    Executes(() =>
    {
        InnoSetup(__ => __
            .SetProcessToolPath(@"C:\Foo\ISCC.exe")
            .SetScriptFile(InnoSetupScriptFile)
            .SetKeyDefinitions($"InputDir=\"{InputDirectory}\"")
            .SetOutputDir(BuildTmpDirectory)
        );
    };
```

### Expected Behavior

Use custom path (C:\Foo\ISCC.exe)

### Actual Behavior

Custom path is ignored

### Regression?

Yes

### Known Workarounds

None

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
#1465
