### ISSUE TITLE
`NullReferenceException` in `ReSharperTasks.PreProcess`

### ISSUE THREAD

**Issue by IT-VBFK** [nuke-build/nuke#1473]
### Usage Information

9.0.1 / 8.0.404 / .net8 / Win

### Description

Since 9.0.0 I get a NRE when running code cleanup via ReSharper cli tools.

I added JetBrains.ReSharper.GlobalTools via `nuke :add-package ...`.

When I run this simple `Target`:

```csharp
Target CleanupCode => _ => _ 
  .Executes(() =>     {         
    ReSharperCleanupCode(s => s             
       .SetInclude(SourceGenerateDirectory / "*.cs"));     
  });

```

a NRE is thrown.

Message + Stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nuke.Common.Tools.ReSharper.ReSharperTasks.PreProcess(ToolOptions options) in /_/source/Nuke.Common/Tools/ReSharper/ReSharperTasks.cs:line 24
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 20
   at Nuke.Common.Tools.ReSharper.ReSharperTasks.ReSharperCleanupCode(Configure`1 configurator) in /_/source/Nuke.Common/Tools/ReSharper/ReSharper.Generated.cs:line 46
```

From Rider de-compile and debugging I got that on line 24 the `resharperOptions.Plugins` is actually null.

### Reproduction Steps

```csharp
Target CleanupCode => _ => _ 
  .Executes(() =>     {         
    ReSharperCleanupCode(s => s             
       .SetInclude(SourceGenerateDirectory / "*.cs"));     
  });

```

### Expected Behavior

Completes successfully

### Actual Behavior

Does not

### Regression?

Yes

### Could you help with a pull-request?

No

**Comment by IT-VBFK** [comment]
Thank you!
