### ISSUE TITLE
System.MissingMethodException: Constructor on type 'Nuke.Common.Tooling.ToolOptions' not found.

### ISSUE THREAD

**Issue by klemmchr** [nuke-build/nuke#1479]
### Usage Information

9.0.1

### Description

I have created some custom tasks for the az CLI which yield an error when setting process environment variables during pre process. I am not sure if my approach is correct in the first place but I didn't find a different way to set process env vars.

### Reproduction Steps

```csharp
[PathTool(Executable = "az")]
[UsedImplicitly(ImplicitUseTargetFlags.Members)]
class AzTasks : ToolTasks, IRequirePathTool
{
    public static IReadOnlyCollection<Output> AzLogin(AzLoginSettings toolSettings) =>
        new AzTasks().Run(toolSettings);

    protected override ToolOptions PreProcess(ToolOptions options)
    {
        return options
            .SetProcessEnvironmentVariable("AZURE_CORE_DISABLE_CONFIRM_PROMPT", "true")
            .SetProcessEnvironmentVariable("AZURE_CORE_COLLECT_TELEMETRY", "false")
            .SetProcessEnvironmentVariable("AZURE_CORE_ONLY_SHOW_ERRORS", "true")
            .SetProcessEnvironmentVariable("AZURE_CORE_OUTPUT", "json");
    }
}
```

```csharp
[PublicAPI]
[Command(
    Type = typeof(AzTasks),
    Command = nameof(AzLogin),
    Arguments = "login --service-principal"
)]
class AzLoginSettings : ToolOptions
{
    public AzLoginSettings(string username, string password, string tenant)
    {
        Set(() => Username, username);
        Set(() => Password, password);
        Set(() => Tenant, tenant);
    }

    [Argument(Format = "--username {value}", Secret = true)]
    public string Username => Get<string>(() => Username);

    [Argument(Format = "--password {value}", Secret = true)]
    public string Password => Get<string>(() => Password);

    [Argument(Format = "--tenant {value}", Secret = true)]
    public string Tenant => Get<string>(() => Tenant);
}
```

### Expected Behavior

Environment variables are set without any exception.

### Actual Behavior

```
20:59:20 [ERR] Target AzureLogin has thrown an exception
System.MissingMethodException: Constructor on type 'Nuke.Common.Tooling.ToolOptions' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Nuke.Common.Utilities.ReflectionUtility.CreateInstance(Type type, Object[] args) in /_/source/Nuke.Utilities/Reflection/ReflectionUtility.Invocation.cs:line 22
   at Nuke.Common.Tooling.Options.TypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/source/Nuke.Tooling/Options.cs:line 60
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Nuke.Common.Tooling.OptionsExtensions.Modify[T](T options, Action`1 modification) in /_/source/Nuke.Tooling/Options.Modify.cs:line 16
   at Nuke.Common.Tooling.ToolOptionsExtensions.SetProcessEnvironmentVariable[T](T o, String key, String value) in /_/source/Nuke.Tooling/ToolOptions.Properties.cs:line 95
   at Tools.Az.AzTasks.PreProcess(ToolOptions options) in /builds/acodia-care/infrastructure/build/Tools/Az/AzTasks.cs:line 53
   at Nuke.Common.Tooling.ToolTasks.Run(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 20
   at Tools.Az.AzTasks.AzLogin(AzLoginSettings toolSettings) in /builds/acodia-care/infrastructure/build/Tools/Az/AzTasks.cs:line 8
   at Build.<get_AzureLogin>b__26_4() in /builds/acodia-care/infrastructure/build/Build.cs:line 44
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass79_0`1.<Executes>b__0() in /_/source/Nuke.Build/Execution/TargetDefinition.cs:line 68
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 120
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
you need a default ctor

**Comment by klemmchr** [comment]
I did try that out, it did not help. Neither a public nor a protected one. The exception is not complaining about my derived class missing a default ctor but about the base class missing one. I suspect this is because of the `TypeConverter` creating an instance of the base class rather than the derived class.

```csharp
[PublicAPI]
[Command(
    Type = typeof(AzTasks),
    Command = nameof(AzLogin),
    Arguments = "login --service-principal"
)]
class AzLoginSettings : ToolOptions
{
    public AzLoginSettings() { }

    public AzLoginSettings(string username, string password, string tenant)
    {
        Set(() => Username, username);
        Set(() => Password, password);
        Set(() => Tenant, tenant);
    }

    [Argument(Format = "--username {value}", Secret = true)]
    public string Username => Get<string>(() => Username);

    [Argument(Format = "--password {value}", Secret = true)]
    public string Password => Get<string>(() => Password);

    [Argument(Format = "--tenant {value}", Secret = true)]
    public string Tenant => Get<string>(() => Tenant);
}
```

**Comment by matkoch** [comment]
I tried in a custom class, but cannot reproduce this. In any case, this is not meant to have constructors with parameters. You should rather generate all the classes + extensions through a JSON file, similar to all other tools.

**Comment by matkoch** [comment]
Calling `SetProcessEnvironmentVariable` passes `ToolOptions` as the generic parameter. The inner cloning therefore doesn't know the actual type to create. You need to set additional environment variables like so:

```
public AzLoginSettings()
{
    Set(() => ProcessEnvironmentVariables, EnvironmentInfo.Variables.ToDictionary()
        .SetKeyValue("AZURE_CORE_DISABLE_CONFIRM_PROMPT", "true")
        .SetKeyValue("AZURE_CORE_COLLECT_TELEMETRY", "false")
        .SetKeyValue("AZURE_CORE_ONLY_SHOW_ERRORS", "true")
        .SetKeyValue("AZURE_CORE_OUTPUT", "json"));
}
```

**Comment by klemmchr** [comment]
How would I do this when using the tool generator? Is there any possibility to set env vars for every task? Or would I need to use the method you described in combination with a base class for all options?
