### ISSUE TITLE
Error when using netcoreapp3.0 target framework

### ISSUE THREAD

**Issue by wieslawsoltes** [nuke-build/nuke#193]
I know that `netcoreapp3.0` is in preview but would be nice to have fix for this issue:

```PowerShell
PS C:\DOWNLOADS\GitHub\PanAndZoom> ./build.ps1 --target Test
Windows PowerShell 5.1.17134.407
Microsoft (R) .NET Core SDK version 3.0.100-preview-009812
NUKE Execution Engine version 0.12.3 (Windows, .NETStandard,Version=v2.0)

_  _ _  _ _  _ ____
|\ | |  | |_/  |___
| \| |__| | \_ |___

> "C:\Program Files\Git\cmd\git.exe" rev-parse --abbrev-ref HEAD

Cannot set initonly static field '<InvokedTargets>k__BackingField' after type 'Nuke.Common.NukeBuild' is initialized.
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at Nuke.Common.Execution.ReflectionService.SetValue(Object instance, MemberInfo member, Object value)
   at Nuke.Common.Execution.ReflectionService.SetValue(Type type, String memberName, Object value)
   at Nuke.Common.Execution.TargetDefinitionLoader.GetExecutingTargets(NukeBuild build, String[] invokedTargetNames, String[] skippedTargetNames)
   at Nuke.Common.Execution.BuildExecutor.Execute[T](Expression`1 defaultTargetExpression)

Repeating warnings and errors:
Cannot set initonly static field '<InvokedTargets>k__BackingField' after type 'Nuke.Common.NukeBuild' is initialized.
```

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace></RootNamespace>
    <IsPackable>False</IsPackable>
    <NoWarn>CS0649;CS0169</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nuke.Common" Version="0.12.3" />
  </ItemGroup>

  <ItemGroup>
    <NukeMetadata Include="**\*.json" Exclude="bin\**;obj\**" />
    <NukeExternalFiles Include="**\*.*.ext" Exclude="bin\**;obj\**" />
    <None Remove="*.ref;*.txt" />
  </ItemGroup>

</Project>
```

```C#
using System;
using System.Linq;
using Nuke.Common;
using Nuke.Common.Git;
using Nuke.Common.ProjectModel;
using Nuke.Common.Tools.DotNet;
using static Nuke.Common.EnvironmentInfo;
using static Nuke.Common.IO.FileSystemTasks;
using static Nuke.Common.IO.PathConstruction;
using static Nuke.Common.Tools.DotNet.DotNetTasks;

class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.Compile);

    [Solution("PanAndZoom.sln")]
    readonly Solution Solution;

    [GitRepository]
    readonly GitRepository GitRepository;

    [Parameter("configuration")]
    public string Configuration { get; set; }

    [Parameter("version-suffix")]
    public string VersionSuffix { get; set; }

    [Parameter("publish-framework")]
    public string PublishFramework { get; set; }

    [Parameter("publish-runtime")]
    public string PublishRuntime { get; set; }

    [Parameter("publish-project")]
    public string PublishProject { get; set; }

    AbsolutePath SourceDirectory => RootDirectory / "src";

    AbsolutePath TestsDirectory => RootDirectory / "tests";

    AbsolutePath ArtifactsDirectory => RootDirectory / "artifacts";

    protected override void OnBuildInitialized()
    {
        Configuration = Configuration ?? "Release";
        VersionSuffix = VersionSuffix ?? "";
    }

    Target Clean => _ => _
        .Executes(() =>
        {
            DeleteDirectories(GlobDirectories(SourceDirectory, "**/bin", "**/obj"));
            DeleteDirectories(GlobDirectories(TestsDirectory, "**/bin", "**/obj"));
            EnsureCleanDirectory(ArtifactsDirectory);
        });

    Target Restore => _ => _
        .DependsOn(Clean)
        .Executes(() =>
        {
            DotNetRestore(s => s
                .SetProjectFile(Solution));
        });

    Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            DotNetBuild(s => s
                .SetProjectFile(Solution)
                .SetConfiguration(Configuration)
                .SetVersionSuffix(VersionSuffix)
                .EnableNoRestore());
        });

    Target Test => _ => _
        .DependsOn(Compile)
        .Executes(() =>
        {
            DotNetTest(s => s
                .SetProjectFile(Solution)
                .SetConfiguration(Configuration)
                .SetLogger("trx")
                .SetResultsDirectory(ArtifactsDirectory / "TestResults")
                .EnableNoBuild()
                .EnableNoRestore());
        });

    Target Pack => _ => _
        .DependsOn(Test)
        .Executes(() =>
        {
            DotNetPack(s => s
                .SetProject(Solution)
                .SetConfiguration(Configuration)
                .SetVersionSuffix(VersionSuffix)
                .SetOutputDirectory(ArtifactsDirectory / "NuGet")
                .EnableNoBuild()
                .EnableNoRestore());
        });

    Target Publish => _ => _
        .DependsOn(Test)
        .Requires(() => PublishRuntime)
        .Requires(() => PublishFramework)
        .Requires(() => PublishProject)
        .Executes(() =>
        {
            DotNetPublish(s => s
                .SetProject(Solution.GetProject(PublishProject))
                .SetConfiguration(Configuration)
                .SetVersionSuffix(VersionSuffix)
                .SetFramework(PublishFramework)
                .SetRuntime(PublishRuntime)
                .SetOutput(ArtifactsDirectory / "Publish" / PublishProject + "-" + PublishRuntime));
        });
}
```

**Comment by wieslawsoltes** [comment]
@matkoch Thanks for quick fix. I can confirm v0.13.0 has fixed the issue.
