### ISSUE TITLE
gitversion issue?

### ISSUE THREAD

**Issue by bonesoul** [nuke-build/nuke#200]
```
Process 'msbuild.exe' exited with code 1.
Invocation:
   "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\msbuild.exe" D:\source\psnbooster\PSNBooster.sln /p:Configuration=Debug
Working directory:


   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(Configure`1 configurator)
   at Build.<get_Compile>b__14_1()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IEnumerable`1 executionList)
   at Nuke.Common.Execution.BuildExecutor.Execute[T](Expression`1 defaultTargetExpression)

Repeating warnings and errors:
Process 'GitVersion.dll' exited with code -532462766.
Invocation:
   C:\Users\shala\.nuget\packages\gitversion.commandline.dotnetcore\4.0.1-beta1-49\tools\GitVersion.dll
Working directory:
   D:\source\psnbooster
Error output:

   Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.<>c.<GetValue>b__4_0()
Process 'msbuild.exe' exited with code 1.
Invocation:
   "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\msbuild.exe" D:\source\psnbooster\PSNBooster.sln /p:Configuration=Debug
Working directory:

```

**Comment by matkoch** [comment]
These are two distinct invocations. Please don’t create issues with just stacktraces pasted (see contribution guidelines). This needs at least a few sentences of explanation, and a note whether the pure invocations (without nuke involved) work or not.

**Comment by markusamshove** [comment]
I had the same problem today @matkoch 

I've created a new build project within an existing project which targets `netfx461`.

Within the `nuke :setup` wizzard I've said that I want GitVersion and that I'm targeting the full framework (not core).

The `PackageReference` generated in the build project is `GitVersion.CommandLine.DotnetCore` which leads to this error.
Changing it to `GitVersion.CommandLine` fixes it

@bonesoul can you confirm that changing 
`<PackageReference Include="GitVersion.CommandLine.DotNetCore" Version="4.0.1-beta1-49" />`
to 
`<PackageReference Include="GitVersion.CommandLine" Version="4.0.0" />`

inside your `_build.csproj` works?
