### ISSUE TITLE
XUnit -parallel argument is incorrect.

### ISSUE THREAD

**Issue by SlowLogicBoy** [nuke-build/nuke#221]
**Command that has been ran:**
`Path/Redacted/xunit.console.exe Path/Redacted/MyTests.dll  -parallel None -Verbose -NUnit Path/Redacted/MyTest.xml`

**Exception from xunit:**
```
Unhandled Exception: System.ArgumentException: incorrect argument value for -parallel
   at Xunit.ConsoleClient.CommandLine.Parse(Predicate`1 fileExists) in C:\Dev\xunit\xunit\src\xunit.console\CommandLine.cs:line 309
   at Xunit.ConsoleClient.CommandLine..ctor(String[] args, Predicate`1 fileExists) in C:\Dev\xunit\xunit\src\xunit.console\CommandLine.cs:line 21
   at Xunit.ConsoleClient.ConsoleRunner.EntryPoint(String[] args) in C:\Dev\xunit\xunit\src\xunit.console\ConsoleRunner.cs:line 31
   at Xunit.ConsoleClient.Program.Main(String[] args) in C:\Dev\xunit\xunit\src\xunit.console\Program.cs:line 17
Specified method is not supported.
```

**Workaround/Solution:**
`-parallel` arguments should be lowercase, when I change it to `none` it works.
Workaround:
instead of `.SetParallel(Xunit2ParallelOption.None)`
use:
`.SetArgumentConfigurator(a => a.Add("-parallel {value}", "none"))`

**Comment by matkoch** [comment]
https://github.com/xunit/xunit/blob/master/src/xunit.console/CommandLine.cs#L274

**Comment by matkoch** [comment]
https://github.com/xunit/xunit/issues/1884
