### ISSUE TITLE
Illegal characters in path unless I specify --solution argument

### ISSUE THREAD

**Issue by andygjp** [nuke-build/nuke#230]
Hi,

I get the following error when I run the build.ps1 file within Azure DevOps Pipeline

```
2019-02-03T18:46:38.5697523Z _  _ _  _ _  _ ____ 
2019-02-03T18:46:38.5697882Z |\ | |  | |_/  |___ 
2019-02-03T18:46:38.5698216Z | \| |__| | \_ |___ 
2019-02-03T18:46:38.5698504Z 
2019-02-03T18:46:39.4534338Z ##[error]Illegal characters in path.
2019-02-03T18:46:39.4542488Z Parameter name: path
2019-02-03T18:46:39.4543444Z    at System.IO.Path.GetFullPath(String path)
2019-02-03T18:46:39.4543992Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2019-02-03T18:46:39.4544537Z    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
2019-02-03T18:46:39.4544909Z    at System.IO.StreamReader..ctor(String path, Encoding encoding)
2019-02-03T18:46:39.4545406Z    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
2019-02-03T18:46:39.4545741Z    at System.IO.File.ReadAllLines(String path)
2019-02-03T18:46:39.4546372Z    at Nuke.Common.ProjectModel.SolutionAttribute.GetValue(MemberInfo member, Object instance)
2019-02-03T18:46:39.4546469Z    at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance)
2019-02-03T18:46:39.4546740Z    at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)
```

To get around the error, I can specify the name of the solution file, like so:

```
- task: PowerShell@2
  displayName: Execute Build Script
  inputs:
    targetType: filePath
    filePath: .\build.ps1
    arguments: --configuration Release --verbosity Verbose --solution "$(Build.SourcesDirectory)\DotNet.Project.LaunchSettings.sln"
    workingDirectory: $(Build.SourcesDirectory)
```

My understanding is that I shouldn't need to specify the solution argument.

I think its blowing up here:

```
private string GetSolutionFileFromConfigurationFile()
{
    var nukeFile = Path.Combine(NukeBuild.RootDirectory, Constants.ConfigurationFileName);
    ControlFlow.Assert(File.Exists(nukeFile), $"File.Exists({nukeFile})");

    var solutionFileRelative = File.ReadAllLines(nukeFile).ElementAtOrDefault(0);
    // other lines removed for the sake of brevity
```

Not sure if it helps, but you can take a look at my pipeline file here: https://github.com/andygjp/DotNet.Project.LaunchSettings/blob/master/azure-pipelines.yml

And the build.cs file here:
https://github.com/andygjp/DotNet.Project.LaunchSettings/blob/master/build/Build.cs

I can't recreate this issue locally, I just call `> .\build.ps1`. Any ideas?

Cheers,
Andy

**Comment by matkoch** [comment]
What is the output of your `Main`?

**Comment by andygjp** [comment]
Hi,

`Main` looks like this currently:

```
public static int Main ()
{
    string path = System.IO.Path.Combine(RootDirectory, ".nuke");
    Console.Write("Path to .nuke file: ");
    Console.WriteLine(path);

    Console.Write("Contents of .nuke file: ");
    try
    {
        string str = File.ReadAllLines(path).First();
        Console.WriteLine(str);
    }
    catch (Exception ex)
    {
        Console.WriteLine("Failed to read content of .nuke file:");
        Console.WriteLine(ex.ToString());
    }
    
    return Execute<Build>(x => x.Publish);
}
```

I added the `Console.WriteLine` to help diagnose the error, but strangely, they never did throw an exception, even though that attempts to recreate the behaviour of `GetSolutionFileFromConfigurationFile()`.

Cheers,
Andy

**Comment by matkoch** [comment]
Could you make a visit in our slack channel? I think it’s easier to troubleshoot. I don’t have any ideas off hand.

**Comment by andygjp** [comment]
The default YAML file that Azure Pipelines gives you contains an environmental variable called "solution" and, presumably, Nuke uses the value of that to check the solution is valid. Unfortunately, the value is set to `**/*.sln'` and hence the illegal characters error.

``` yaml
variables:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
```

Removing the variable fixed the issue.

Thanks for your help diagnosing the issue.
