### ISSUE TITLE
Error locating MSBuild with vs2019

### ISSUE THREAD

**Issue by EMostafaAli** [nuke-build/nuke#266]
When I try to run the nuke from powershell, it gives the following error.

> Assertion failed: Could not find a suitable MSBuild instance.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.Resolve(Nullable`1 msBuildVersion, Nullable`1 msBuildPlatform)
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(MSBuildSettings toolSettings)
   at Build.<get_Restore>b__14_1() in C:\Users\maali\source\repos\Simusharp.AutoBuilder\build\Build.cs:line 51
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)

I tracked it down to the class "MSBuildToolPathResolver.cs" as it doesn't have an entry for VS2019 (which is the only version installed in my machine).

Not sure if it will help, MSbuild path in 2019 is 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin

**Comment by prom3theu5** [comment]
It seems like there was some work committed a few days back regarding this issue

Any chance we can get an alpha up?
All my build agent containers have been updated to msbuild 16, and my development machine has been cleaned also

**Comment by matkoch** [comment]
@prom3theu5 those are different parts which are a bit clumsy to generalize.

I'll try to look into this later this week. What you all can do is to use `SetToolPath` manually.

**Comment by prom3theu5** [comment]
Ahh awesome. Thanks
I knew there’d be a way to do that I’ve been looking for it

**Comment by matkoch** [comment]
It's mentioned here: http://www.nuke.build/docs/authoring-builds/cli-tools.html#fluent-apis

**Comment by prom3theu5** [comment]
Excellent. Thanks again :)

**Comment by alexshyba** [comment]
In case if it helps anyone, I had a similar issue, MSBuild as installed on another drive and I was getting this error. Fixed by reading the MSBuild path from the env variable:

```
  MSBuild(s => s
   .SetToolPath(Environment.GetEnvironmentVariable("MSBuild"))
    ..
```
