### ISSUE TITLE
Loading MSBuild 16 projects fails because of default tool version.

### ISSUE THREAD

**Issue by david-driscoll** [nuke-build/nuke#295]
Currently when using the latest dotnet core 3 preview 6, loading project with `GetMSBuildProject`/`ParseProject` fails due to the tools version being incorrect (which is probably to be expected to be honest).

The current "version" for msbuild 16 seems to be `Current` instead of a version number like it has been in the past (eg `15.0`).  

It's possible that if we had the ability to define the tools version either as a static or as an additional argument on the method, everything else would work, but I'm not 100% certain on that.

The lines I found that are related are below:

https://github.com/nuke-build/common/blob/f62ad09ab81921c96401a1d0935448345a5cac7f/source/Nuke.Common/ProjectModel/ProjectModelTasks.cs#L49-L54

An example of the error message is 

```
The imported project "C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\15.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in /_/src/Shared/ProjectErrorUtilities.cs:line 412
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports) in /_/src/Build/Evaluation/Evaluator.cs:line 2418
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError) in /_/src/Build/Evaluation/Evaluator.cs:line 2173
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult) in /_/src/Build/Evaluation/Evaluator.cs:line 1935
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1813  
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 986
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1815  
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 929
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in /_/src/Build/Evaluation/Evaluator.cs:line 717
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2728
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2683
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2799
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 502
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection) in /_/src/Build/Definition/Project.cs:line 434
   at Nuke.Common.ProjectModel.ProjectModelTasks.ParseProject(String projectFile, String configuration, String targetFramework)
   at Nuke.Common.ProjectModel.ProjectExtensions.GetMSBuildProject(Project project, String configuration, String targetFramework)
   at Program.<>c.<get_GenerateReadme>b__4_4(Project x) in D:\Development\ReadySelect\rocketsurgery\Build\.build\Build.cs:line 48
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Program.<get_GenerateReadme>b__4_1() in D:\Development\ReadySelect\rocketsurgery\Build\.build\Build.cs:line 46
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass69_0.<Executes>b__0()
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__3_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Execution.BuildExecutor.<>c__DisplayClass2_0.<Execute>b__0(ExecutableTarget x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)
```

Thanks!

**Comment by matkoch** [comment]
I wonder if `DefaultToolsVersion` should return `Current` then..

**Comment by david-driscoll** [comment]
I think with the newer `Microsoft.Build` package it would, but I think with the old 15 version it won't.  I tried to run a custom build locally but ran out of time.

**Comment by arodus** [comment]
I already tried upgrading the version in Nuke but right now, due to major changes in the `Microsoft.Build` package, it's just not possible without rewriting the core of nuke and therefore breaking everything. 
Nevertheless I'm sure there is a possibility to parse a netcore 3.0 project with Microsoft.Build 15 and also there is still some time until the release so things may change until then and Nuke does not aim for supporting the latest previews. 
If you do any more local tests I'd be happy to get the results.
