### ISSUE TITLE
Could not find package 'Nuget.Commandline'

### ISSUE THREAD

**Issue by DanScottNI** [nuke-build/nuke#302]
I have a classic .NET Framework project that I'm trying to build.

I'm using the following code:

`
Target Restore => _ => _
        .Executes(() =>
        {
            NuGetTasks.NuGetRestore(new NuGetRestoreSettings() { });
        });

    Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            MSBuild(o => o
                .SetTargetPath(Solution)
                .SetTargets("Build")
                .SetConfiguration(Configuration)
                .EnableNodeReuse());
        });`

Unfortunately I get the build error when I run build --target Compile:

`Assertion failed: Could not find package 'NuGet.CommandLine' via 'C:\Users\danscott\Documents\Visual Studio 2017\Projects\test\build\_build.csproj'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.Tooling.ToolPathResolver.<GetPackageExecutable>g__GetNuGetPackagesDirectory|3_1(String singlePackageId)
   at Nuke.Common.Tooling.ToolPathResolver.<>c.<GetPackageExecutable>b__3_3(String x)
   at System.Linq.Enumerable.SelectArrayIterator`2.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String framework)
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.NuGet.NuGetTasks.NuGetRestore(NuGetRestoreSettings toolSettings)
   at Build.<>c.<get_Restore>b__6_1() in C:\Users\1228955\Documents\Visual Studio 2017\Projects\mdras\build\Build.cs:line 34
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)`

This is probably something really obvious that I'm missing.

**Comment by GeorgDangl** [comment]
You just need to add a reference to the `NuGet.CommandLine` package in your build project, since that's used by the `NuGetTasks`, since NUKE uses the NuGet tool contained in this package .

**Comment by matkoch** [comment]
http://www.nuke.build/docs/authoring-builds/cli-tools.html

First note box.
