### ISSUE TITLE
Update Glob version

### ISSUE THREAD

**Issue by Odirb** [nuke-build/nuke#317]
Hello,
When the glob pattern contains a space (such as $"bin/Release macOS/**/*.pdb"), nuke hang with the exception below.
This problem is already fixed in glob repository https://github.com/kthompson/glob/issues/43.

Is it possible to update the nuget package to fix this issues?
Thanks

`Unable` to scan for next token. Stuck on ' '
   at GlobExpressions.Scanner.ScanToken()
   at GlobExpressions.Scanner.Scan()
   at GlobExpressions.Parser.AcceptIt()
   at GlobExpressions.Parser.ParseIdentifier()
   at GlobExpressions.Parser.ParseSegment()
   at GlobExpressions.Parser.ParseTree()
   at GlobExpressions.PathTraverser.Traverse(DirectoryInfo root, String pattern, Boolean caseSensitive, Boolean emitFiles, Boolean emitDirectories)
   at GlobExpressions.Glob.Files(DirectoryInfo workingDirectory, String pattern, GlobOptions options)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nuke.Common.IO.PathConstruction.GlobFiles(AbsolutePath directory, String[] patterns)
   at Common.BuildBase.<>c.<get_PackageSymbols>b__79_2(String x) in /Users/christophe/Projects/websynchro/Common/build/Common/BuildBase.cs:line 335
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Common.BuildBase.<get_PackageSymbols>b__79_1() in /Users/christophe/Projects/websynchro/Common/build/Common/BuildBase.cs:line 335
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] `defaultTargetExpressions)
`

**Comment by matkoch** [comment]
Sure it's possible to update. You can even make a PR for it! And don't forget to star the project :)

**Comment by Odirb** [comment]
Here it is
https://github.com/nuke-build/common/pull/48
