### ISSUE TITLE
Resource name for Build.cs

### ISSUE THREAD

**Issue by Techcadia** [nuke-build/nuke#329]
After running
```
dotnet tool install --global Nuke.GlobalTool --version 0.23.0-alpha0142
```

Which is https://github.com/nuke-build/common/commit/4adeb02908b4dbb2e7c040fc80dc09c58f751cc7

I run
```bash
bash-4.4# /root/.dotnet/tools/nuke :setup
How should the build project be named?
¬  _build
Where should the build project be located?
¬  ./build
Which NUKE version should be used?
¬  0.23.0-alpha0142 (latest prerelease)
Which solution should be the default?
¬  Merchant.sln
Do you need help getting started with a basic build?
¬  Yes, get me started!
Restore, compile, pack using ...
¬  dotnet CLI
Source files are located in ...
¬  ./source
Move packages to ...
¬  ./output
Where do test projects go?
¬  ./tests
Do you use GitVersion?
¬  Yes, just not setup yet
Creating directory '/repo/./build'...
Assertion failed: Resource 'Nuke.GlobalTool.templates.Build.cs' not found. Available resources are:
  - Nuke.GlobalTool.templates..editorconfig
  - Build
  - Nuke.GlobalTool.templates.build.netcore.ps1
  - Nuke.GlobalTool.templates.build.netfx.ps1
  - Nuke.GlobalTool.templates.build.netcore.sh
  - Nuke.GlobalTool.templates.build.netfx.sh
  - Nuke.GlobalTool.templates.CHANGELOG.md
  - Nuke.GlobalTool.templates.README.md
  - Nuke.GlobalTool.templates.global.json
  - Nuke.GlobalTool.templates.LICENSE
  - Nuke.GlobalTool.templates.nuget.config
  - Nuke.GlobalTool.templates._build.legacy.packages.config
  - Nuke.GlobalTool.templates._build.csproj.DotSettings
  - Nuke.GlobalTool.templates._build.legacy.csproj
  - Nuke.GlobalTool.templates._build.sdk.csproj
   at Nuke.Common.ControlFlow.Fail(String text) in /bitrise/src/source/Nuke.Common/ControlFlow.cs:line 48
   at Nuke.Common.Utilities.ResourceUtility.GetResource(Type typeForNamespace, String postfix) in /bitrise/src/source/Nuke.Common/Utilities/ResourceUtility.cs:line 44
   at Nuke.Common.Utilities.ResourceUtility.GetResource[T](String postfix) in /bitrise/src/source/Nuke.Common/Utilities/ResourceUtility.cs:line 37
   at Nuke.Common.Utilities.ResourceUtility.GetResourceAllLines[T](String postfix) in /bitrise/src/source/Nuke.Common/Utilities/ResourceUtility.cs:line 24
   at Nuke.GlobalTool.Program.GetTemplate(String templateName) in /bitrise/src/source/Nuke.GlobalTool/Program.Setup.cs:line 380
   at Nuke.GlobalTool.Program.Setup(String[] args, String rootDirectory, String buildScript) in /bitrise/src/source/Nuke.GlobalTool/Program.Setup.cs:line 228```
```
The application just crashes. 

My assumption is that https://github.com/nuke-build/common/blob/develop/source/Nuke.GlobalTool/templates/Build.cs does not get compiled into the system.

**Comment by matkoch** [comment]
https://github.com/microsoft/msbuild/issues/4852

**Comment by Techcadia** [comment]
Confirmed the beta works correctly.

**Comment by lars-nielsen** [comment]
@matkoch Looks like this issue can be closed now
