### ISSUE TITLE
launchSettings.json is included in NukeSpecificationFiles

### ISSUE THREAD

**Issue by JoshClose** [nuke-build/nuke#348]
I set up a parameter for `--project` so I could easly specify which project to build.

```cs
[Parameter]
readonly string Project;
```

```cs
Target Compile => _ => _
    .DependsOn(Restore)
    .Executes(() =>
    {
		var project = Solution.GetProject(Project)?.Path ?? Solution.Path;
        DotNetBuild(_ => _
            .SetProjectFile(project)
            .SetConfiguration(Configuration)
            .SetAssemblyVersion(GitVersion.AssemblySemVer)
            .SetFileVersion(GitVersion.AssemblySemFileVer)
            .SetInformationalVersion(GitVersion.InformationalVersion)
            .EnableNoRestore());
    });
```

The first build works, and all subsequent builds give an error.

```
narsh@LAPTOP-VUCCV505 MINGW64 ~/Projects/InfinitWifi (nuke-setup)
$ nuke Compile --project RadiusServer
NUKE Global Tool version 0.23.4 (Windows,.NETStandard,Version=v2.0)
PowerShell Desktop version 5.1.18362.145
Microsoft (R) .NET Core SDK version 3.0.100
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 29.24 ms for C:\Users\narsh\Projects\InfinitWifi\build\_build.csproj.
  Couldn't load metadata file 'launchSettings.json'.
EXEC : error : Required property 'Name' not found in JSON. Path '', line 7, position 1. [C:\Users\narsh\Projects\InfinitWifi\build\_build.csproj]
  Required property 'Name' not found in JSON. Path '', line 7, position 1.
C:\Users\narsh\.nuget\packages\nuke.common\0.23.4\build\Nuke.MSBuildTaskRunner.targets(16,5): error MSB3073: The command "dotnet exec "C:\Users\narsh\.nuget\packages\nuke.common\0.23.4\build\Nuke.MSBuildTaskRunner.dll" -- --action CodeGeneration --files Properties\launchSettings.json" exited with code -1. [C:\Users\narsh\Projects\InfinitWifi\build\_build.csproj]

Build FAILED.

EXEC : error : Required property 'Name' not found in JSON. Path '', line 7, position 1. [C:\Users\narsh\Projects\InfinitWifi\build\_build.csproj]
C:\Users\narsh\.nuget\packages\nuke.common\0.23.4\build\Nuke.MSBuildTaskRunner.targets(16,5): error MSB3073: The command "dotnet exec "C:\Users\narsh\.nuget\packages\nuke.common\0.23.4\build\Nuke.MSBuildTaskRunner.dll" -- --action CodeGeneration --files Properties\launchSettings.json" exited with code -1. [C:\Users\narsh\Projects\InfinitWifi\build\_build.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.72
```

There is a workaround by either commenting out
```xml
<NukeSpecificationFiles Include="**\*.json" Exclude="bin\**;obj\**" />
```
from the `_build.csproj` file, or by adding `launchSettings.json` to the `Exclude`.

**Comment by robsonj** [comment]
I believe I am experiencing the same issue, the workaround does not seem to help my situation. Hopefully of help, here is the stack trace...
```
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018: The "CodeGenerationTask" task failed unexpectedly.
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018: Newtonsoft.Json.JsonSerializationException: Required property 'Name' not found in JSON. Path '', line 8, position 1.
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.CodeGeneration.ToolSerializer.Load(String file) in /bitrise/src/source/Nuke.CodeGeneration/ToolSerializer.cs:line 33
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.CodeGeneration.CodeGenerator.GenerateCode(String specificationFile, Func`2 outputFileProvider, Func`2 namespaceProvider, Func`2 sourceFileProvider) in /bitrise/src/source/Nuke.CodeGeneration/CodeGenerator.cs:line 40
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>b__6(String x) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 59
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /bitrise/src/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.ExecuteInner() in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 57
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.ContextAwareTask.Execute() in /bitrise/src/source/Nuke.MSBuildTasks/ContextAwareTask.cs:line 76
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
