### ISSUE TITLE
 GetProperty<T>(..) throws an exception if CoreSdk 3.1.100 is installed 

### ISSUE THREAD

**Issue by ymalich** [nuke-build/nuke#357]
The extention method ProjectExtensions.GetProperty<T>(this Project project, String propertyName) throws the Exception "The expression ""..\GlobalAssemblyInfo.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated", by opening an old format project file contains the linked item. 

```
The expression ""..\GlobalAssemblyInfo.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. System.String.GetPathsOfAllDirectoriesAbove  C:\Program Files\dotnet\sdk\3.1.100\Roslyn\Microsoft.Managed.Core.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in /_/src/Shared/ProjectErrorUtilities.cs:line 412
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation) in /_/src/Build/Evaluation/Expander.cs:line 3396
   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.IntrinsicItemFunctions`1.<ExecuteStringFunction>d__13.MoveNext() in /_/src/Build/Evaluation/Expander.cs:line 2451
   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.<Transform>d__0`1.MoveNext() in /_/src/Build/Evaluation/Expander.cs:line 1629
   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.<Transform>d__0`1.MoveNext() in /_/src/Build/Evaluation/Expander.cs:line 1620
   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandExpressionCapture[S](Expander`2 expander, ItemExpressionCapture expressionCapture, IItemProvider`1 evaluatedItems, IElementLocation elementLocation, ExpanderOptions options, Boolean includeNullEntries, Boolean& isTransformExpression, List`1& itemsFromCapture) in /_/src/Build/Evaluation/Expander.cs:line 1880
   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandExpressionCaptureIntoItems[S,T](ItemExpressionCapture expressionCapture, Expander`2 expander, IItemProvider`1 items, IItemFactory`2 itemFactory, ExpanderOptions options, Boolean includeNullEntries, Boolean& isTransformExpression, IElementLocation elementLocation) in /_/src/Build/Evaluation/Expander.cs:line 1766
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.IncludeOperation.SelectItems(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs:line 70
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:line 56
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.MemoizedOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 197
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.ComputeItems(LazyItemList lazyItemList, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 324
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.GetItemData(ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 316
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in /_/src/Build/Evaluation/Evaluator.cs:line 774
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2728
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2688
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2799
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 516
   at Nuke.Common.ProjectModel.ProjectModelTasks.ParseProject(String projectFile, String configuration, String targetFramework)
   at Nuke.Common.ProjectModel.ProjectExtensions.GetProperty(Project project, String propertyName)
   at Nuke.Common.ProjectModel.ProjectExtensions.GetProperty[T](Project project, String propertyName)
   at Build.<get_CopyBinariesToTempFolder>b__32_1() in \build\Build.cs:line 209
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
Repeating warnings and errors:
The expression ""..\GlobalAssemblyInfo.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. System.String.GetPathsOfAllDirectoriesAbove  C:\Program Files\dotnet\sdk\3.1.100\Roslyn\Microsoft.Managed.Core.targets
```
The exception is being thrown only if the core sdk 3.1.100 is installed. 
If only core sdk 3.0.100 is installed (or selected via global.json), the NUKE script runs well.
It seems core sdk 3.1.100 has a bug (or a breaking change). 
I've attached very small test project, so you can reproduce the problem yourself.

[ConsoleApp1.zip](https://github.com/nuke-build/nuke/files/3956927/ConsoleApp1.zip)

**Comment by matkoch** [comment]
You can fix this yourself by adding overwriting `Microsoft.Build` package versions. Just explicitly reference them in your build.

See https://github.com/nuke-build/nuke/commit/fbf101546b47cff54d6e5fbf4a7a8c34b10f248b
