### ISSUE TITLE
Nuke doesn't work with GitVersion 5.1.3

### ISSUE THREAD

**Issue by Thealexbarney** [nuke-build/nuke#365]
### Description
Nuke 0.23.4 fails when trying to use GitVersion 5.1.3. Nuke specifies framework netcoreapp3.0 when launching the tool, but GitVersion uses netcoreapp3.1.

### Steps to reproduce

- Add GitVersionAttribute to a field in the Build class.
- Run build
### Relevant log output

```
Assertion failed: Package executable GitVersion.dll, or GitVersion.exe [GitVersion.Tool|GitVersion.CommandLine] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.1
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by matkoch** [comment]
Relevant log output should include versions and stacktraces.

**Comment by Thealexbarney** [comment]
Updated with more details

**Comment by dennisdoomen** [comment]
I can confirm this as well for Nuke 0.23.4 and GitVersion.Tool 5.1.3.

**Comment by BlowaXD** [comment]
Same here
log :
```
root@9ef54ac53963:/app# dotnet nuke compile
NUKE Global Tool version 0.23.4 (Linux,.NETStandard,Version=v2.0)
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Microsoft (R) .NET Core SDK version 3.1.100
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 10.89 sec for /app/build/_build.csproj.
  _build -> /app/build/bin/Debug/_build.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:13.90

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 0.23.4 (Linux,.NETStandard,Version=v2.0)

> /usr/bin/git rev-parse --abbrev-ref HEAD
> /usr/bin/dotnet /root/.nuget/packages/gitversion.tool/5.1.1/tools/netcoreapp3.0/any/GitVersion.dll
Error parsing Infinity value. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetResult(IProcess process, GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)


Repeating warnings and errors:
Error parsing Infinity value. Path '', line 1, position 1.

═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            NotRun          0:00
Compile            NotRun          0:00
───────────────────────────────────────
Total                              0:00
═══════════════════════════════════════

Build failed on 01/05/2020 14:16:56.
```

**Comment by matkoch** [comment]
@BlowaXD this is a completely different error?

**Comment by BlowaXD** [comment]
> 
> 
> @BlowaXD this is a completely different error?

I don't think so, it's also linked to GitVersion 5.1.3 on .NET core 3.1 with Nuke 0.23.4

**Comment by matkoch** [comment]
@BlowaXD and the error is a different one.

**Comment by BlowaXD** [comment]
> 
> 
> @BlowaXD and the error is a different one.

You want me to create a special issue for that ? I thought It would be better to regroup it with issue linked to GitVersion, .net core 3.1 & nuke 0.23.4

**Comment by matkoch** [comment]
If you would search for the specific exception message, you’d have found https://github.com/nuke-build/nuke/issues/367, which will be resolved with 0.24.0

**Comment by BlowaXD** [comment]
my bad. :(

**Comment by matkoch** [comment]
Please vote everyone: https://github.com/GitTools/GitVersion/issues/2024

**Comment by chrisdmacrae** [comment]
This can be resolved currently by giving a framework to the attribute:

```
    [GitVersion(Framework = "netcoreapp3.1")]
    protected readonly GitVersion GitVersion;
```

**Comment by matkoch** [comment]
I'm closing this as there is a workaround and I don't want to implement anything else in particular to resolve external issues.
