### ISSUE TITLE
java.util.NoSuchElementException raised when attempting to run through Rider

### ISSUE THREAD

**Issue by schappel** [nuke-build/nuke#372]
Fresh install of NUKE Support 2019.3.0 in Rider 2019.3.1.  When I attempt to execute a target I get the following error:
```
Catch

java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.jetbrains.rider.plugins.nuke.NukeConfigurationUtilKt.createAndAddConfiguration(NukeConfigurationUtil.kt:67)
	at com.jetbrains.rider.plugins.nuke.NukeConfigurationUtilKt.findOrCreateConfiguration(NukeConfigurationUtil.kt:21)
	at com.jetbrains.rider.plugins.nuke.RunConfigurationManager$1.invoke(RunConfigurationManager.kt:17)
	at com.jetbrains.rider.plugins.nuke.RunConfigurationManager$1.invoke(RunConfigurationManager.kt:13)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:30)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:39)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:28)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:67)
	at com.jetbrains.rider.protocol.EarlyBackendStarter$switchingScheduler$1.pumpProtocolQueue(EarlyBackendStarter.kt:87)
	at com.jetbrains.rdclient.util.idea.ExtensionsKt.callSynchronously(Extensions.kt:128)
	at com.jetbrains.rider.util.idea.ExtensionsKt.syncFromBackend(Extensions.kt:78)
	at com.jetbrains.rider.intentions.altEnter.ReSharperPopupModel.executeItem(ReSharperPopupModel.kt:110)
	at com.jetbrains.rider.intentions.altEnter.PopupModel$attachTo$2.invoke(PopupModel.kt:23)
	at com.jetbrains.rider.intentions.altEnter.PopupModel$attachTo$2.invoke(PopupModel.kt:9)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:30)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$initViewModel$3.invoke(DefaultPopupViewModel.kt:76)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$initViewModel$3.invoke(DefaultPopupViewModel.kt:15)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:30)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel$executeSelectedItem$executeDelegate$1.invoke(DefaultPopupListModel.kt:136)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel$executeSelectedItem$executeDelegate$1.invoke(DefaultPopupListModel.kt:14)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$sam$java_lang_Runnable$0.run(PopupListView.kt)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1434)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2413)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1430)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:104)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:133)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:123)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:735)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl.cancel(PopupViewImpl.kt:81)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:681)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1375)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl$2.invoke(PopupViewImpl.kt:58)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl$2.invoke(PopupViewImpl.kt:32)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:266)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:252)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate$default(RLifetime.kt:226)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewHierarchy.a(PopupViewHierarchy.kt:152)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewHierarchy.closeAllViews(PopupViewHierarchy.kt:164)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$executeSelectedItem$1.invoke(PopupListView.kt:283)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$executeSelectedItem$1.invoke(PopupListView.kt:33)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel.executeSelectedItem(DefaultPopupListModel.kt:143)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.c(PopupListView.kt:277)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.handleReleased(PopupListView.kt:269)
	at com.jetbrains.rider.services.popups.nova.ui.MouseListenerEx$DefaultImpls.mouseReleased(MouseListenerEx.kt:13)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.mouseReleased(PopupListView.kt:33)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:687)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:188)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$ModalContext.dispose(RiderModalPopupCookie.kt:47)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
	at com.intellij.openapi.util.ObjectTree.executeUnregistered(ObjectTree.java:196)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:127)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:123)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:119)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$Companion.using(RiderModalPopupCookie.kt:76)
	at com.jetbrains.rider.services.popups.RiderPopupModelHost.showPopup(RiderPopupModelHost.kt:49)
	at com.jetbrains.rdclient.services.popups.FrontendPopupModelHost$1$1.invoke(FrontendPopupModelHost.kt:35)
	at com.jetbrains.rdclient.services.popups.FrontendPopupModelHost$1$1.invoke(FrontendPopupModelHost.kt:29)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:146)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:108)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:126)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:30)
	at com.jetbrains.rd.util.reactive.ViewableMap.put(ViewableMap.kt:29)
	at com.jetbrains.rd.framework.impl.RdMap.onWireReceived(RdMap.kt:129)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:28)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:83)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:14)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by matkoch** [comment]
I need a repro project and would like to ask you to star the project.

**Comment by schappel** [comment]
[https://github.com/schappel/NukeBuildIssue] Simple repo project

**Comment by matkoch** [comment]
please try with the sdk-based project format
