### ISSUE TITLE
Teamcity implementation tries to add existing Project configuration parameter

### ISSUE THREAD

**Issue by metalfork** [nuke-build/nuke#373]
### Description
When running a nuke target nuke's Teamcity implementation attempts to `Add` and existing configuration parameter that already has been defined at the Teamcity Project level as a parameter and therefore exists. This implementation just attempts to Add the key instead of trying to add and then updating value if key already exists 
https://github.com/nuke-build/nuke/blob/3a2873864686781c216e4b71ebbaab2036da3c67/source/Nuke.Common/CI/TeamCity/TeamCity.cs#L74

### Steps to reproduce

1. Define `environment` configuration parameter for TC project.
2. Run `./buiild.sh` with default nuke `Build` target (`Restore` + `Compile`)

### Relevant log output
[17:23:59][Step 2/3] dotnet-install: Installation finished successfully.
[17:23:59][Step 2/3] Microsoft (R) .NET Core SDK version 3.0.100
[17:24:00][Step 2/3] Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
...
[17:24:02][Step 2/3] NUKE Execution Engine version 0.23.4 (Linux,.NETStandard,Version=v2.0)
[17:24:02][Step 2/3] 
[17:24:02][Step 2/3] An item with the same key has already been added. Key: environment
[17:24:02][Step 2/3]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[17:24:02][Step 2/3]    at Nuke.Common.CI.TeamCity.TeamCity.ParseDictionary(String file)
[17:24:02][Step 2/3]    at Nuke.Common.CI.TeamCity.TeamCity.<.ctor>b__14_1()
[17:24:02][Step 2/3]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[17:24:02][Step 2/3]    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[17:24:02][Step 2/3]    at System.Lazy`1.CreateValue()
[17:24:02][Step 2/3]    at System.Lazy`1.get_Value()
[17:24:02][Step 2/3]    at Nuke.Common.CI.TeamCity.TeamCity.get_ConfigurationProperties()
[17:24:02][Step 2/3]    at Nuke.Common.CI.TeamCity.TeamCity.get_BranchName()
[17:24:02][Step 2/3]    at Nuke.Common.Git.GitRepositoryAttribute.GetBranch()
[17:24:02][Step 2/3]    at Nuke.Common.Git.GitRepositoryAttribute.GetValue(MemberInfo member, Object instance)
[17:24:02][Step 2/3]    at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
[17:24:02][Step 2/3]    at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
[17:24:02][Step 2/3]    at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

**Comment by matkoch** [comment]
Can't reproduce.

**Comment by metalfork** [comment]
Forgot to mention `environment` is set to `readOnly='false'` as well.

You should be able to reproduce by setting a build `Configuration Parameter` for `environment`

We can agree that if the `key` exists then the Dictionary<TKey,TValue>.Add(TKey, TValue) Method will throw an `ArgumentException`. [ref](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.add?view=netcore-3.0)

**Comment by matkoch** [comment]
Still can’t reproduce: https://teamcity.jetbrains.com/buildConfiguration/matkoch_Nuke_Compile/2712490?buildTab=buildParameters

<blockquote></blockquote>

**Comment by metalfork** [comment]
@matkoch how do I see your configuration parameters for the build definition used by Compile in your tests?

**Comment by metalfork** [comment]
I see this change with the parameter as `readOnly='true'`. https://github.com/nuke-build/nuke/commit/634b61207329abb9117ee7a2fa8540475ccc2b9a

I am inheriting this configuration parameter during my tests? Is that the possible cause? 

Based on the nuke implementation we can agree that if the key exists then the Dictionary<TKey,TValue>.Add(TKey, TValue) Method will throw an ArgumentException? If so, then in your test is the `environment` configuration parameter not in the nuke dictionary during compile the compile step? It is during my tests so it throws?
