### ISSUE TITLE
SonarScannerTasks with dotnet-sonarscanner 4.8.0 fails with "Package executable ... requires a framework" error

### ISSUE THREAD

**Issue by vincevriend** [nuke-build/nuke#377]
# Error when referencing dotnet-sonarscanner 4.8.0

```xml
<ItemGroup>
    <PackageReference Include="dotnet-sonarscanner" Version="4.8.0">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
```
Nuke will fail with an error about "Package executable ... requires a framework".
```
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
NUKE Execution Engine version 0.23.6 (Windows,.NETStandard,Version=v2.0)


╬═══════════════════════
║ InvokeSonarScanner
╬══════════════

Assertion failed: Package executable SonarScanner.MSBuild.dll, or SonarScanner.MSBuild.exe [dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.0
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.get_SonarScannerPath()
   at Nuke.Common.Tools.SonarScanner.SonarScannerBeginSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.SonarScannerBegin(SonarScannerBeginSettings toolSettings)
   at Build.<>c.<get_InvokeSonarScanner>b__4_1() in C:\Dev\nuke-dotnet-sonarscanner-repro\build\Build.cs:line 21
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)

Repeating warnings and errors:
Assertion failed: Package executable SonarScanner.MSBuild.dll, or SonarScanner.MSBuild.exe [dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.0

══════════════════════════════════════════
Target                Status      Duration
──────────────────────────────────────────
InvokeSonarScanner    Failed          0:00
──────────────────────────────────────────
Total                                 0:00
══════════════════════════════════════════
```

# Success when referencing dotnet-sonarscanner 4.7.1
```xml
<ItemGroup>
    <PackageReference Include="dotnet-sonarscanner" Version="4.7.1">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
```
The following log shows the desired behaviour. Because i made a minimal reproduction repo sonar fails with an error but that's okay because the error is actually from the sonarscanner tool itself.
```
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
NUKE Execution Engine version 0.23.6 (Windows,.NETStandard,Version=v2.0)


╬═══════════════════════
║ InvokeSonarScanner
╬══════════════

> "C:\Program Files\dotnet\dotnet.exe" C:\Users\myuser\.nuget\packages\dotnet-sonarscanner\4.7.1\tools\netcoreapp2.1\any\SonarScanner.MSBuild.dll begin
SonarScanner for MSBuild 4.7.1
Using the .NET Core version of the Scanner for MSBuild
Pre-processing started.
Preparing working directories...
14:51:45.636  14:51:45.632  A required argument is missing: /key:[SonarQube project key]
14:51:45.636  Expecting at least the following command line argument:
- SonarQube project key
When connecting to a SonarQube server earlier than version 6.1, the following command line arguments are also required:
- SonarQube project name
- SonarQube project version
The full path to a settings file can also be supplied. If it is not supplied, the exe will attempt to locate a default settings file in the same directory as the SonarQube Scanner for MSBuild.
Use '/?' or '/h' to see the help message.
14:51:45.637  Pre-processing failed. Exit code: 1
Process 'dotnet.exe' exited with code 1.
```

# Differences in NuGet package contents between versions
It might have something to do with `ToolPathResolver.GetPackageExecutable` and how it handles NuGet packages with multiple frameworks included.

## dotnet-sonarscanner 4.7.1 NuGet package contents
![dotnet-sonarscanner 4 7 1 NuGet package contents](https://user-images.githubusercontent.com/7148530/72664891-52ff5700-3a03-11ea-86c5-dadfbe8f0479.PNG)

## dotnet-sonarscanner 4.8.0 NuGet package contents
![dotnet-sonarscanner 4 8 0 NuGet package contents](https://user-images.githubusercontent.com/7148530/72664893-5a266500-3a03-11ea-8ba0-73610097e814.PNG)

# Repro project download
[nuke-dotnet-sonarscanner-repro.zip](https://github.com/nuke-build/nuke/files/4080779/nuke-dotnet-sonarscanner-repro.zip)
You can change the reference in the repro to 4.7.1 to see the desired behaviour.

**Comment by roshek** [comment]
I didn't find the actual fix anywhere so if anybody runs into this, what solved it for me is that I needed to invoke the SonarScanner tasks like this:

`SonarScannerBegin(settings => settings.SetFramework("netcoreapp3.0") /*other settings*/);`

You might also need to update to v0.24.2.

**Comment by matkoch** [comment]
The fix is that you can call `SetFramework`. There is no other way of
fixing this.
