### ISSUE TITLE
ToolPathResolver does not take dependencies into account

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#396]
### Description

I've like to create a [shared nuke nuget](http://www.nuke.build/docs/sharing-builds/fundamentals.html) that have some targets and the neccessary dotnet tools like GitVersion.tools as dependencies.

### Steps to reproduce

1. Create project "A" that creates NuGet with `Nuke.Common` and `GitVersion.Tool` as dependency in the `.nuspec`
1. Pack project "A" -> Push to Package-Feed 
1. Create project "B" normal C# project and use nuke to build project "B".
1. The `_build` project from project "B" references now the nuget from step 2.
1. Running `build.ps1` for project "B"
1. Failed to resolve "GitVersion.Tool" xXx

### Site note
When building the _build project with VS2019 instead of command line `dotnet build` the tools gets resolve. But this a bug in VS2019:

- https://github.com/dotnet/project-system/issues/3734
- https://github.com/NuGet/Home/issues/9132#issuecomment-581740452

### Reproduced 

[issue.zip](https://github.com/nuke-build/nuke/files/4162013/issue.zip)

Just run `build.ps1` in the root.

### Relevant log output

```
Assertion failed: Could not find package 'GitVersion.Tool', or 'GitVersion.CommandLine' using:
 - Project assets file 'D:\github\nuke\issue\consumer\build\obj\project.assets.json'
 - NuGet packages config 'D:\github\nuke\issue\consumer\build\_build.csproj'
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)`
```

**Comment by matkoch** [comment]
Would have been great to have a little warning that you're clearing the whole nuget cache.

**Comment by cmenzi** [comment]
Sorry!! I thought about that. I had caching issue during writing the reproduction.

I hope you have fast internet to fill up again.
