### ISSUE TITLE
Requirement of 'build.cmd' file GitHubActions AutoGeneration

### ISSUE THREAD

**Issue by mariohines** [nuke-build/nuke#402]
### Description
Unable to get configuration generation with `GitHubActions` attribute without a `build.cmd` file, even if it's just a blank file.

### Steps to reproduce
1. Setup a new nuke build project.
2. Add attribute for `GitHubActions`, set the name, image and an InvokedTarget.
3. Run the invoked target.

### Relevant log output
```
Standard output:
   Assertion failed: BuildCmdPath != null
      at Nuke.Common.ControlFlow.Fail(String text)
      at Nuke.Common.CI.ConfigurationAttributeBase.get_BuildCmdPath()
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetSteps(GitHubActionsImage image, IReadOnlyCollection`1 relevantTargets)+MoveNext()
      at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
      at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetJobs(GitHubActionsImage image, IReadOnlyCollection`1 relevantTargets)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.<>c__DisplayClass66_0.<GetConfiguration>b__0(GitHubActionsImage x)
      at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetConfiguration(NukeBuild build, IReadOnlyCollection`1 relevantTargets)
      at Nuke.Common.CI.ConfigurationAttributeBase.OnBeforeLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets)
      at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>b__3(IOnBeforeLogo x)
      at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
      at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Action`1 action)
      at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

```

### Recommendation
Allow setting that value in the attribute for `GitHubActions`. Would allow greater versatility and allow the use of `build.sh` or `build.ps1` to be used. Although defaulting it to `build.ps1` would work as well.

**Comment by matkoch** [comment]
You need to update the global tool and execute `nuke :setup` again.
