### ISSUE TITLE
Requirement of 'build.cmd' file GitHubActions AutoGeneration with no alternative

### ISSUE THREAD

**Issue by mariohines** [nuke-build/nuke#404]
### Description
Unable to get configuration generation with `GitHubActions` attribute without a `build.cmd` file. Workaround to this is using a blank `build.cmd` file but that only works on the `WindowsLatest` image for `GitHubActions`.

### Steps to reproduce
1. Setup a new nuke build project.
2. Add attribute for `GitHubActions`, set the name, image and an InvokedTarget.
3. Ensure that a `build.cmd` file doesn't exist anywhere in the solution folder hierarchy
4. Run the invoked target.

### Relevant log output
```
Standard output:
   Assertion failed: BuildCmdPath != null
      at Nuke.Common.ControlFlow.Fail(String text)
      at Nuke.Common.CI.ConfigurationAttributeBase.get_BuildCmdPath()
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetSteps(GitHubActionsImage image, IReadOnlyCollection`1 relevantTargets)+MoveNext()
      at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
      at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetJobs(GitHubActionsImage image, IReadOnlyCollection`1 relevantTargets)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.<>c__DisplayClass66_0.<GetConfiguration>b__0(GitHubActionsImage x)
      at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
      at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetConfiguration(NukeBuild build, IReadOnlyCollection`1 relevantTargets)
      at Nuke.Common.CI.ConfigurationAttributeBase.OnBeforeLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets)
      at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>b__3(IOnBeforeLogo x)
      at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
      at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Action`1 action)
      at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

```

### Current master branch references to issue:
- [ConfigurationAttributeBase.BuildCmdPath](https://github.com/nuke-build/nuke/blob/master/source/Nuke.Common/CI/ConfigurationAttributeBase.cs#L37-L40) property that shows the default of `build.cmd`.
- [GitHubActionsAttribute](https://github.com/nuke-build/nuke/blob/master/source/Nuke.Common/CI/GitHubActions/GitHubActionsAttribute.cs) class that does not override the virtual `BuildCmdPath` property

#### Note:
This exists in the `develop` branch as well. I'm running nuke 0.24.1 for the global tool.

### Recommendation
Allow setting that value in the attribute for `GitHubActions`. Would allow greater versatility and allow the use of `build.sh` or `build.ps1` to be used. Although defaulting it to `build.ps1` would work as well.

**Comment by matkoch** [comment]
Why?

**Comment by mariohines** [comment]
This is a bug. I've updated the tool and re-setup the project before I even submitted this as an issue originally. I pointed to the code as well this time in hopes that it will at least get looked at. As this is...it doesn't work for anything other than windows images out-of-the-box.

**Comment by matkoch** [comment]
Funnily it works for nuke itself. Besides, I have no idea why you’re talking about creating an empty build.cmd file. That’s why I don’t look at it. Because the latest global tool creates one.

**Comment by matkoch** [comment]
Also if you think an issue was closed unjustified, please din’t create a new one with almost the same content. Leave another comment and ask for reopening.

**Comment by mariohines** [comment]
> Also if you think an issue was closed unjustified, please din’t create a new one with almost the same content. Leave another comment and ask for reopening.

Thanks. I'll do that next time. But it didn't create the file in the latest tool. Which is why I still had the error.

**Comment by mariohines** [comment]
Are you doing just `nuke` in the terminal/CL?

**Comment by matkoch** [comment]
I’m sure it will create it. In the same folder as you call `nuke :setup`.

**Comment by mariohines** [comment]
Apologies. I'm sure I did it properly, but obviously not. I'll test again with other than the Windows images....to see if it will work in GitHubActions. Like using Obuntu or Mac.
