### ISSUE TITLE
The handle is invalid.

### ISSUE THREAD

**Issue by grounzero** [nuke-build/nuke#423]
### Description

Get an error `The handle is invalid.`  when invoking `nuke :setup`

### Steps to reproduce

In the root of a new project I ran ```dotnet tool install Nuke.GlobalTool --global```
then 
```
 nuke :setup
```

then got

```

NUKE Global Tool version 0.24.3 (Windows,.NETCoreApp,Version=v3.0)
Could not find root directory. Falling back to working directory.
How should the build project be named?
The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.set_CursorLeft(Int32 value)
   at Colorful.Console.set_CursorLeft(Int32 value)
   at Nuke.Common.Utilities.ConsoleUtility.PromptForInput(String question, String defaultValue) in /bitrise/src/source/Nuke.Common/Utilities/ConsoleUtility.cs:line 40
   at Nuke.GlobalTool.Program.Setup(String[] args, String rootDirectory, String buildScript) in /bitrise/src/source/Nuke.GlobalTool/Program.Setup.cs:line 59
```

**Comment by matkoch** [comment]
Please raise a bug at the Colorful Console repo.
