### ISSUE TITLE
Access to the path 'R:\System Volume Information' is denied.

### ISSUE THREAD

**Issue by steven5clu884** [nuke-build/nuke#429]
### Description
I am trying to use nuke to create a decent build system for Visual Studio 2019 project that evolved from Studio 2010 initially.  I am starting with a single sln that incorporates 3 other csproj, and everything compiles in the Studio 2019 on the build machine that I am trying to automate

### Steps to reproduce
See log below.  That is my command window output for the nuke command into the Administraotr privealeged cmd
R: is a VHD, if that makes any difference

### Relevant log output
R:\Artisan\Source\Connectors\Forever>nuke
NUKE Global Tool version 0.24.2 (Windows,.NETCoreApp,Version=v3.0)
Could not find .nuke file. Do you want to setup a build? [y/n]
How should the build project be named?
¬  _build
Where should the build project be located?
¬  ./build
Which NUKE version should be used?
¬  0.24.4 (latest release)
Access to the path 'R:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.Concat[T](IEnumerable`1 enumerable, T[] others)+MoveNext() in /bitrise/src/source/Nuke.Common/Utilities/Collections/Enumerable.Concat.cs:line 30
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nuke.GlobalTool.Program.Setup(String[] args, String rootDirectory, String buildScript) in /bitrise/src/source/Nuke.GlobalTool/Program.Setup.cs:line 90
   at Nuke.GlobalTool.Program.Handle(String[] args, String rootDirectory, String buildScript) in /bitrise/src/source/Nuke.GlobalTool/Program.cs:line 78
   at Nuke.GlobalTool.Program.Main(String[] args) in /bitrise/src/source/Nuke.GlobalTool/Program.cs:line 35

```
output including version and stacktraces
```

**Comment by matkoch** [comment]
Sorry, can't reproduce.
