### ISSUE TITLE
Visual Studio 2019 open while building with Nuke from the command line causes IOException

### ISSUE THREAD

**Issue by ayfie-frank-gynnild** [nuke-build/nuke#438]
### Description
When our solution in Visual Studio 2019 is open, while we build with `build.ps1` from the command line, we always get `The process cannot access the file` issues. This has been observed on all our dev machines.

### Steps to reproduce

1. Open solution in VS2019 (ours has ~140 projects).
2. Build from command line with Nuke using `build.ps1`.
3. Experience this symptom (some parts have been anonymized):

```
The process cannot access the file '************\obj\Debug\net472\******.assets.cache' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Nuke.Common.IO.FileSystemTasks.CopyRecursivelyInternal(String source, String target, DirectoryExistsPolicy directoryPolicy, FileExistsPolicy filePolicy, Func`2 excludeDirectory, Func`2 excludeFile)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.CopyDirectoryRecursively(String source, String target, DirectoryExistsPolicy directoryPolicy, FileExistsPolicy filePolicy, Func`2 excludeDirectory, Func`2 excludeFile)
   at Build.<get_CopyContext>b__13_1() in *********************\build_nuke\Build.cs:line 135
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)

**Comment by ayfie-frank-gynnild** [comment]
Update:
We've identified the reason why this happens. It is due to a Visual Studio Extension named "Wix Toolset Visual Studio 2019 Extension". As soon as we disable it, it works. I'll create a ticket there instead. Sorry for the inconvenience.
