### ISSUE TITLE
InvalidProjectFileException during package installation in VS2017

### ISSUE THREAD

**Issue by paolofulgoni** [nuke-build/nuke#442]
### Description

It's not possible to install the `Nuke.Common` package in a legacy .NET project.

It seems there is an issue with this line:

https://github.com/nuke-build/nuke/blob/aa101837848cc062f03970a50c70fdb6469bdf44/source/Nuke.Common/Nuke.Common.props#L11

### Steps to reproduce

1. Create a standard project in VS2017, targeting .NET Framework 4.8
2. Install the `Nuke.Common` package, version 0.24.4
3. The package installation fails with the following error:

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The attribute "Visible" in element <PackageDownload> is unrecognized.  C:\git\vis-ftvision\packages\Nuke.Common.0.24.4\build\Nuke.Common.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Internal.ProjectXmlUtilities.ThrowProjectInvalidAttribute(XmlAttributeWithLocation attribute)
   at Microsoft.Build.Internal.ProjectXmlUtilities.VerifyThrowProjectAttributes(XmlElementWithLocation element, HashSet`1 validAttributes)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectItemDefinitionXml(XmlElementWithLocation element, ProjectItemDefinitionGroupElement parent)
   at Microsoft.Build.Construction.ProjectParser.ParseProjectItemDefinitionGroupElement(XmlElementWithLocation element)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, ProjectRootElementCache projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.<>c.<OpenProjectOrSolution>b__201_0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCache projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Evaluator`4.<>c__DisplayClass62_1.<ExpandAndLoadImportsFromUnescapedImportExpression>b__0(String p, ProjectRootElementCache c)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.AddImportStatement(Project msBuildProject, String targetsPath, ImportLocation location)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.AddImportStatement(String targetsPath, ImportLocation location)
   at NuGet.PackageManagement.VisualStudio.VsMSBuildProjectSystem.<>c__DisplayClass35_0.<<AddImport>b__0>d.MoveNext()
```

**Comment by matkoch** [comment]
Why legacy project?

**Comment by paolofulgoni** [comment]
Because the new one doesn't work on VS2017, so I tried the legacy and found this other issue
(I would definitely prefer to use the new project type)

**Comment by paolofulgoni** [comment]
Sorry, ignore my previous comment, the issue doesn't seem to be related to the project type.

Even with the new project type, using VS2017, I get the following error:
```
------ Build started: Project: _build, Configuration: Debug x64 ------
C:\Users\PFulgoni\.nuget\packages\nuke.common\0.24.4\build\Nuke.Common.props(11,22): error MSB4066: The attribute "Visible" in element <PackageDownload> is unrecognized.
Done building project "_build.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
