### ISSUE TITLE
Sequence contains no elements error while try start nuke with inheritance

### ISSUE THREAD

**Issue by VladyslavLishchyna** [nuke-build/nuke#542]
### Description
Hi i am using nuke and everything was fine, this time i am trying to split targets into different classes while i try to start build have exception

### Steps to reproduce

```
  public abstract class NukeNotificationDeploy : NukeBuild
  {
    public static int Main()
    {
      return 0;
    }
  }

 public abstract class BaseDeployStrategy : NukeNotificationDeploy
  {
    public new static int Main()
    {
      return NukeBuild.Execute(new Expression<Func<BaseDeployStrategy, Target>>[1]
      {
        (BaseDeployStrategy x) => new Target(x.Start)
      });
    }

 public class SingleInstanceDeployStrategy : BaseDeployStrategy
  {
    public new static int Main()
    {
      return NukeBuild.Execute(new Expression<Func<SingleInstanceDeployStrategy, Target>>[1]
      {
        (SingleInstanceDeployStrategy x) => new Target(x.Start)
      });
    }
```

**Targets looks like**
```
    public ITargetDefinition StopSingleApplication(ITargetDefinition definition)
```

**Call strategy:**
```
    public static void Run(DeployType deployType)
    {
      switch (deployType)
      {
        case DeployType.ManyInstancesOrderUse:
          ManyInstancesOrderUseDeployStrategy.Main();
          break;
        case DeployType.OneOfManyInstances:
          OneOfManyInstancesDeployStrategy.Main();
          break;
        case DeployType.SingleInstance:
          SingleInstanceDeployStrategy.Main();
          break;
        default:
          throw new ArgumentException($"Unknow type of deploy type {deployType}");
      }
    }
```

### Relevant log output

```
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Nuke.Common.Execution.HelpTextService.GetTargetsText(IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.Execution.HandleHelpRequestsAttribute.OnAfterLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by VladyslavLishchyna** [comment]
also i try make test and also have exception

```
class Build: SingleInstanceDeployStrategy
{
  public static void Main()
  {
    Environment = "test";
    var builder = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile(DeploySettings.ResolveSettingsFileName(Environment), optional: true);

    var settings = builder.Build().Get<DeploySettings>();

    DeployDependecies.Register(settings);


    Execute<Build>(x => x.Test);
  }

  public ITargetDefinition Test(ITargetDefinition definition)
  {
    return definition.Before(base.Start)
                              .Description("Stop application (kill IIS pool)")
                              .Executes(() => Console.WriteLine("Test"));
  } 

  [Parameter("Environment")]
  static string Environment;

}
```

**Comment by matkoch** [comment]
Just because you can, doesn't mean you should. The Main method should only delegate, and targets should be properties.

**Comment by VladyslavLishchyna** [comment]
> Just because you can, doesn't mean you should. The Main method should only delegate, and targets should be properties.

thx, I see that and close issue)
