### ISSUE TITLE
Allow manual MSBuild selection

### ISSUE THREAD

**Issue by nick-morhun** [nuke-build/nuke#566]
### Description
Since Nuke cannot build for .Net Core 3 if either no Visual Studio is installed on a Windows machine or there are a few older VS installs besides VS 2019, it would be very helpful to be able to just set the MSBuild path manually.

### Alternatives

- https://github.com/nuke-build/nuke/issues/301 could solve this but it looks like a more radical change since it is not done yet.
- Search also for an MSBuild from Jetbrains Rider

**Comment by matkoch** [comment]
I'm not sure I know what you mean? Which MSBuild invocation?

**Comment by nick-morhun** [comment]
We have some .NET Core projects and some .NET 4.7 in the solution. 

This is what I see failing (when I set MSBuildSettings.SetMSBuildVersion(MSBuildVersion.VS2019)):

```
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.Resolve(Nullable`1 msBuildVersion, Nullable`1 msBuildPlatform)
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.GetToolPath()
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(MSBuildSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(Configure`1 configurator)
```

Without setting VS2019 explicitly, it tries to use the other MSBuild and fails:

```
Process 'msbuild.exe' exited with code 1.
   > "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" J:\Source\MySolution.sln
```

Nuke.Common.Tools.DotNet.DotNetTasks.DotNetRestore() works.

**Comment by matkoch** [comment]
Tool path can be set via `SetToolPath`
