### ISSUE TITLE
GitRepository class does not work with Git worktrees

### ISSUE THREAD

**Issue by gnuechtel** [nuke-build/nuke#572]
### Expected behavior

`Given` a nuke build script in a Git worktree folder
`When` the script uses a `GitRepository` object
`Then` it can access all properties

### Actual behavior

```
Assertion failed: Could not find git directory for '/path/to/my/worktree'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Git.GitRepository.FromLocalDirectory(String directory, String branch, String remote)
   at Nuke.Common.Git.GitRepositoryAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### Meta information

Used Nuke version: 0.24.11

It seems, the code is still the same on current `master` regarding this issue.

### What is a Gitwork tree?

It is another local working copy of the repository. Instead of `.git` _directory_, it contains a `.git` __file__ like this:

```
gitdir: /path/to/my/local_git_directory/.git/worktrees/directory-name-of-worktree
```

By the way: I am a software developer too and could contribute...

### Work around

Use Git with the `Git` class like this:

```c#
var gitBranch = Nuke.Common.Tools.Git.GitTasks.Git("branch --show-current")?.First().Text.Trim()
```
In my case it was sufficient because I wanted to access the current branch of the Git repository/working tree.

**Comment by matkoch** [comment]
PR / draft is welcome

**Comment by gnuechtel** [comment]
Okay! Great! I will start soon :-)

**Comment by ArchyInf** [comment]
What made this obsolete? GitRepository is still failing when current worktree isn't including the .git directory. (Nuke 5.1.2)

using `git rev-parse --git-common-dir` instead of `.git` should fix users of `separate-git-dir` too.

**Comment by ArchyInf** [comment]
I pushed a fix here: https://github.com/ArchyInf/nuke/commit/735ab40858f00569f467f6a15131f9a199b9f99e
PR was discouraged by template text.
