### ISSUE TITLE
PaketPackageResolver.GetLocalInstalledPackageDirectory does not handle groups correctly.

### ISSUE THREAD

**Issue by willsmith9182** [nuke-build/nuke#583]
### Description

Paket is capable of splitting depedecies into groups, not just using the default "main" group, each group is restored to a seperate folder under the `./packages` folder. PaketPackageResolver.GetLocalInstalledPackageDirectory does not return a valid directory path to search for tools under. 

When including external tools via Paket in a group the tools are unable to be resolved. 

The path construction, assumes that the folder structure will be `/packages/packageid/...` when really it's `/packages/<group>/packageid/...`  where `<group>` is optional.

It might be a suggestion to parse the paket deps file to look up groups for package ids before making the folder structure, but trust me parsing paket files isn't as much fun as it sounds :)

### Fear not, there is a work-around!
but it pins the tools to the same group in paket for all places we use our shared build tools!  😢 

specifying the group the tool comes from inserts the right folder name into the path so the tool can hapily be resolved. 

However, if like us, you share build tools via nuget you must ensure that you reference your build tools package under the SAME group as was used to resolve the tool (i.e. the hard coded bit before the package id)
```
[PackageExecutable(@"external\RoundhousE", "rh.exe")]
Tool RoundhousE;
```

### Steps to reproduce

consider the following paket.dependecies file:
```
group external
    framework: >= netcoreapp3.1
    source https://api.nuget.org/v3/index.json    
    nuget RoundhousE
```

You end up with the following packages folder strcuture:
![image](https://user-images.githubusercontent.com/11752440/96941513-8909c400-14ca-11eb-878a-3368c01948ec.png)

The following tool decleration:

```
[PackageExecutable("RoundhousE", "rh.exe")]
Tool RoundhousE;
```

When the tool is invoked:
```
Assertion failed: Could not find package 'RoundhousE' (1.2.3) using:
 - Embedded packages directory at ''
 - Paket packages config 'C:\Git\BuildTools\paket.lock'
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.ToolResolver.GetPackageTool(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.PackageExecutableAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

changing to (as above) resolves the tool correctly
```
[PackageExecutable(@"external\RoundhousE", "rh.exe")]
Tool RoundhousE;
```

i traced this back to `PaketPackageResolver.GetLocalInstalledPackageDirectory` and put the following call in my bootstrapping:

```
Logger.Info(PaketPackageResolver.GetLocalInstalledPackageDirectory("RoundhousE", RootDirectory / "paket.lock"));
```

which allowed me to verify pre-fixing the group "works" for now. :)

### Relevant log output

```
# nuke
NUKE Global Tool version LOCAL (Windows,.NETStandard,Version=v2.0)
Windows PowerShell 5.1.18362.752
Microsoft (R) .NET Core SDK version 3.1.402
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  BuildTools -> C:\Git\BuildTools\src\bin\Debug\BuildTools.dll
  Build -> C:\Git\BuildTools\.build\bin\Debug\Build.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.65
C:\Git\BuildTools\packages\external\RoundhousE

NUKE Execution Engine version 0.24.11 (Windows,.NETCoreApp,Version=v2.1)

Assertion failed: Could not find package 'RoundhousE' (1.2.3) using:
 - Embedded packages directory at ''
 - Paket packages config 'C:\Git\BuildTools\paket.lock'
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.ToolResolver.GetPackageTool(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.PackageExecutableAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

Repeating warnings and errors:
Assertion failed: Could not find package 'RoundhousE' (1.2.3) using:
 - Embedded packages directory at ''
 - Paket packages config 'C:\Git\BuildTools\paket.lock'
```

stack trace with the "fixed" tool (yes the call to RoundhousE fails, but at least it's calling it!)

```
# nuke
NUKE Global Tool version LOCAL (Windows,.NETStandard,Version=v2.0)
Windows PowerShell 5.1.18362.752
Microsoft (R) .NET Core SDK version 3.1.402
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  BuildTools -> C:\Git\BuildTools\src\bin\Debug\BuildTools.dll
  Build -> C:\Git\BuildTools\.build\bin\Debug\Build.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.65
C:\Git\BuildTools\packages\external\RoundhousE

NUKE Execution Engine version 0.24.11 (Windows,.NETCoreApp,Version=v2.1)


╬═══════════════════
║ SetBuildNumber
╬══════════

Calculated Semantic Version for: (0.0.0-local) C:\Git\BuildTools\master.buildversion

╬══════════════
║ StartItUp
╬═════

Loaded config file: C:\Git\BuildTools\dev.build.config
> C:\Git\BuildTools\packages\external\RoundhousE\tools\rh.exe
Error: You must specify Database Name (/d) OR Connection String (/cs) at a minimum to use RoundhousE.
```

**Comment by matkoch** [comment]
Thanks for the detailed report. I'm not using Paket anywhere and have a long backlog of other things, but if you're interested I think this is a good candidate for a PR. Just let me know in Slack or here maybe.

**Comment by willsmith9182** [comment]
Well i have a work around for now, but it would be nice if the search took into account groups when searching so i'll knock something up :)
