### ISSUE TITLE
Build project published as tool does not find embedded packages

### ISSUE THREAD

**Issue by Nefarion** [nuke-build/nuke#585]
### Description
When distributing the build project as a global tool, packages that are bundled are not found.  
I think it is because of [this line](https://github.com/nuke-build/nuke/blob/589b9727c1e54e60ad67f164ade8479d9607bd40/source/Nuke.Common/Execution/BuildManager.cs#L58-L59).
I added `ToolPathResolver.ExecutingAssemblyDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);` to my `OnBuildInitialized()`, everything works fine now.

### Steps to reproduce

1. Include a tool in your build project (eg. ReportGenerator)
`<PackageDownload Include="ReportGenerator" Version="[4.7.1]" />`
2. Use it somewhere `ReportGenerator(_ => _.SetFramework("netcoreapp3.0")....)`
3. publish as Global tool
4. download and install
5. Error message:
```
Assertion failed: Could not find package 'ReportGenerator' using:
 - Embedded packages directory at ''
```
### Relevant log output

```
>&"C:\Gitlab\tools\build.exe" test-results --skip
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
NUKE Execution Engine version 0.24.11 (Windows,.NETCoreApp,Version=v2.1)
╬════════════════
║ TestResults
╬═══════
Assertion failed: Could not find package 'ReportGenerator' using:
 - Embedded packages directory at ''
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.ReportGenerator.ReportGeneratorTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.ReportGenerator.ReportGeneratorSettings.GetToolPath()
   at Nuke.Common.Tools.ReportGenerator.ReportGeneratorSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.ReportGenerator.ReportGeneratorTasks.ReportGenerator(ReportGeneratorSettings toolSettings)
   at Nuke.Common.Tools.ReportGenerator.ReportGeneratorTasks.ReportGenerator(Configure`1 configurator)
   at Build.<get_TestResults>b__88_1() in <>
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
Repeating warnings and errors:
Assertion failed: Could not find package 'ReportGenerator' using:
 - Embedded packages directory at ''
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Skipped         0:00
Compile            Skipped         0:00
Test               Skipped         0:00   // ((ProjectName != "Client") && (Parameters.TestProjectPath != null))
TestResults        Failed          0:00
───────────────────────────────────────
Total                              0:00
═══════════════════════════════════════
Build failed on 10/23/2020 10:10:12 AM. (╯°□°）╯︵ ┻━┻
```

Was already reported in https://github.com/nuke-build/nuke/issues/394#issuecomment-594387675

**Comment by tapika** [comment]
I had exactly the same issue, once you override OutputPath, for example like this:

```
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<OutputPath>../bin</OutputPath>
  </PropertyGroup>
```

I've fix this using code snippet like this:
```
protected override void OnBuildInitialized()
{
     NuGetToolPathResolver.NuGetAssetsConfigFile = <.csproj file path>.Parent / "obj" / "project.assets.json";
}
```
