### ISSUE TITLE
Unable to locate SonarQube global tools on Windows

### ISSUE THREAD

**Issue by KuraiAndras** [nuke-build/nuke#625]
Similarly to #603 the only way I can get the sonarscanner tasks to work is with manually setting the environment variable

```csharp
var path = ToolPathResolver.GetPackageExecutable("dotnet-sonarscanner", "SonarScanner.MSBuild.dll", framework: "net5.0");
Environment.SetEnvironmentVariable("SONARSCANNER_EXE", path);
```

**Comment by KuraiAndras** [comment]
why did you close this?

**Comment by matkoch** [comment]
As per contribution guidelines:

> No issues for additional CLT support or missing arguments. We expect pull-request instead as they can be easily declared using a specification file, and otherwise aren't affecting the core functionality.

Also, it seems that you didn't read the issue template.

**Comment by KuraiAndras** [comment]
If I adhere to the template will you reopen this?

**Comment by matkoch** [comment]
> No issues for additional CLT support or missing arguments. We expect pull-request instead as they can be easily declared using a specification file, and otherwise aren't affecting the core functionality.

**Comment by KuraiAndras** [comment]
### Description

Using the SonarScannerTasks.SonarScannerBegin and SonarScannerTasks.SonarScannerEnd methods does not work, as it will not find the tool.

Reproduced on Windows 10, Nuke 5.0.2, Net 5.0

### Steps to reproduce

1. Create Console project
2. Add Nuke Build project
3. Add Target which uses SonarScannerTasks.SonarScannerBegin
4. Reference sonar tool
```xml
<ItemGroup>
  <PackageDownload Include="dotnet-sonarscanner" Version="[5.0.4]" />
</ItemGroup>
```
5. Run nuke build

The project with the aplied fixes can be found at this [repository](https://github.com/KuraiAndras/NukeSonarSample)

### Relevant log output

```
PowerShell Desktop version 5.1.19041.610
Microsoft (R) .NET Core SDK version 5.0.101

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 5.0.2 (Windows,.NETCoreApp,Version=v2.1)


╬═══════════════
║ SonarBegin
╬══════

Assertion failed: Package executable SonarScanner.MSBuild.dll, or SonarScanner.MSBuild.exe [dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool] requires a framework:
 - net5.0
 - netcoreapp2.0
 - netcoreapp3.0
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.SonarScanner.SonarScannerBeginSettings.GetProcessToolPath()
   at Nuke.Common.Tools.SonarScanner.SonarScannerBeginSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.SonarScannerBegin(SonarScannerBeginSettings toolSettings)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.SonarScannerBegin(Configure`1 configurator)
   at Build.<>c.<get_SonarBegin>b__4_1() in D:\NukeSonarSample\Build\Build.cs:line 22
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass61_0`1.<Executes>b__0()
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)


Repeating warnings and errors:
Assertion failed: Package executable SonarScanner.MSBuild.dll, or SonarScanner.MSBuild.exe [dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool] requires a framework:
 - net5.0
 - netcoreapp2.0
 - netcoreapp3.0
```

If I use the following approach, the build works as expected
```csharp
Target SonarBegin => _ => _
    .DependentFor(Clean)
    .Executes(() =>
    {
        var path = ToolPathResolver.GetPackageExecutable("dotnet-sonarscanner", "SonarScanner.MSBuild.dll", framework: "net5.0");
        Environment.SetEnvironmentVariable("SONARSCANNER_EXE", path);

        return SonarScannerTasks
            .SonarScanner("begin ");
    });
```

### Question
Beacuse I'm new with Nuke am I doing this wrong or is this a bug?

**Comment by cmenzi** [comment]
You need to call

.SetFramework("netcoreapp3.0")

**Comment by KuraiAndras** [comment]
That fixed it, thank you
