### ISSUE TITLE
gitversions does not support .net5

### ISSUE THREAD

**Issue by oxffaa** [nuke-build/nuke#640]
### Description
I have an error when I try to use gitversions in nuke target on .net5. Looks like gitversion does not support .net5 and requires netcore3.1.

### Steps to reproduce

1. I run the simple target

```
    [Required] [GitVersion(NoFetch = true)] readonly GitVersion GitVersion;
...
    Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            DotNetBuild(s => s
                .SetProjectFile(Solution)
                .SetConfiguration(Configuration)
                .SetAssemblyVersion(GitVersion.AssemblySemVer)
                .SetFileVersion(GitVersion.AssemblySemFileVer)
                .SetInformationalVersion(GitVersion.InformationalVersion)
                .EnableNoRestore()
                .SetNoRestore(true)
            );
        });
```
2. ./builh.sh compile
3. Build failed.

### Relevant log output

```NUKE Execution Engine version 5.0.2 (Linux,.NETCoreApp,Version=v2.1)

 /home/runner/.dotnet/dotnet /home/runner/.nuget/packages/gitversion.tool/5.1.1/tools/netcoreapp3.0/any/GitVersion.dll /nofetch
Warning: Process 'dotnet' exited with code 150.
   /home/runner/.dotnet/dotnet /home/runner/.nuget/packages/gitversion.tool/5.1.1/tools/netcoreapp3.0/any/GitVersion.dll /nofetch
    /home/runner/work/lfe/lfe
Error output:
   It was not possible to find any compatible framework version
   The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
     - The following frameworks were found:
         5.0.0 at [/home/runner/.dotnet/shared/Microsoft.NETCore.App]
   
   You can resolve the problem by installing the specified framework and/or SDK.
   
   The specified framework can be found at:
     - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=ubuntu.18.04-x64

StackTrace:
   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
 /usr/bin/git status --short
Error: Member 'GitVersion' is required to be not null.
   at Nuke.Common.Execution.RequirementService.ValidateRequirements(NukeBuild build, IReadOnlyCollection`1 executingTargets)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

Error: Process completed with exit code 255.
```

### Versions
.net - 5.0.100
Nuke.Common - 5.0.2

**Comment by GeorgDangl** [comment]
I think you need to have a compatible .NET Core version installed for GitVersion to work. Essentially, Nuke just calls the CLI tool of GitVersion.

**Comment by oxffaa** [comment]
Yep. Installing .net core 3.1 can resolve the problem. But It is strange behavior. I have ci workflow based on github actions:

```
name: Regular master build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Setup GitVersions 
      run: dotnet tool install --global GitVersion.Tool

    - name: Test GitVersions setup
      run: dotnet-gitversion
    
    - name: Run nuke for publishing
      run: ./build.sh Publish --feed ${{ secrets.MYGETFEED }} --apikey ${{ secrets.MYGETAPIKEY }}
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.11
      with:
        directory: ./artifacts 

```

Step "Test GitVersions setup" works well but step "Run nuke for publishing" fails.

```
Run dotnet-gitversion
{
  "Major": 0,
  "Minor": 1,
  "Patch": 0,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": "",
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": 25,
  "BuildMetaDataPadded": "0025",
  "FullBuildMetaData": "25.Branch.master.Sha.237246b0b714c49d8f9f4418b0a90064ac06261f",
  "MajorMinorPatch": "0.1.0",
  "SemVer": "0.1.0",
  "LegacySemVer": "0.1.0",
  "LegacySemVerPadded": "0.1.0",
  "AssemblySemVer": "0.1.0.0",
  "AssemblySemFileVer": "0.1.0.0",
  "FullSemVer": "0.1.0+25",
  "InformationalVersion": "0.1.0+25.Branch.master.Sha.237246b0b714c49d8f9f4418b0a90064ac06261f",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "237246b0b714c49d8f9f4418b0a90064ac06261f",
  "ShortSha": "237246b",
  "NuGetVersionV2": "0.1.0",
  "NuGetVersion": "0.1.0",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "083442fa659b7fc3e9b86086afb30220b90b0758",
  "CommitsSinceVersionSource": 25,
  "CommitsSinceVersionSourcePadded": "0025",
  "UncommittedChanges": 0,
  "CommitDate": "2021-01-07"
}
```
 and

```
Run ./build.sh Publish --feed https://www.myget.org/F/oxffaa/api/v3/index.json --apikey ***
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Microsoft (R) .NET Core SDK version 5.0.100
Creating directory '/home/runner/work/lfe/lfe/.tmp'...

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 5.0.2 (Linux,.NETCoreApp,Version=v2.1)

> /usr/bin/git status --short
CalculateVersion

Repeating warnings and errors:
Assertion failed: Package executable GitVersion.dll, or GitVersion.exe [GitVersion.Tool|GitVersion.CommandLine] requires a framework:
 - netcoreapp3.0
 - netcoreapp2.1

════════════════════════════════════════
Target              Status      Duration
────────────────────────────────────────
CalculateVersion    Failed        < 1sec
Clean               NotRun              
Restore             NotRun              
Compile             NotRun              
Test                NotRun              
Pack                NotRun              
Publish             NotRun              
────────────────────────────────────────
Total                             < 1sec
════════════════════════════════════════

Build failed on 01/07/2021 11:57:43. (╯°□°）╯︵ ┻━┻
Error: Process completed with exit code 255.

```

I tried to use GitVersionTasks instead of GetVersionAttribute, but without any results:

```
    Target CalculateVersion => t => t
        .Executes(() =>
        {
            (CurrentVersion, _) = GitVersion(c => c
                .SetExecutable("dotnet-gitversion")
                .SetNoFetch(true)
            );
        });
```



Any ideas about why that happens?

**Comment by onelioubov** [comment]
You can also specify the framework directly to force it to use .NET 5 (granted you have a version of GitVersion that supports it):

`[GitVersion (Framework="net5.0", NoFetch = true)] readonly GitVersion GitVersion;`

This works for me if I'm using the latest version of GitVersion.Tool (in this case, 5.6.0, since it has .NET 5 support).

**Comment by oxffaa** [comment]
I found this workaround:

```
Target CalculateVersion => t => t
        .Executes(() =>
        {
            var process = ProcessTasks.StartProcess("dotnet-gitversion", workingDirectory: RootDirectory);
            process.WaitForExit();

            var output = String.Join("\r\n", process.Output.Select(o => o.Text));
            CurrentVersion = JsonSerializer.Deserialize<MyGitVersion>(output, new JsonSerializerOptions()
            {
                IgnoreNullValues = true,
                NumberHandling = JsonNumberHandling.WriteAsString
            });
        });
```

It works well with dotnet-gitverion and gitversion too. But it looks really bad for me...

**Comment by oxffaa** [comment]
> You can also specify the framework directly to force it to use .NET 5 (granted you have a version of GitVersion that supports it):
> 
> `[GitVersion (Framework="net5.0", NoFetch = true)] readonly GitVersion GitVersion;`
> 
> This works for me if I'm using the latest version of GitVersion.Tool (in this case, 5.6.0, since it has .NET 5 support).

I tried this without success.

```
[Required] [GitVersion(NoFetch = true, Framework = "net5.0")] GitVersion CurrentVersion2;
```
Error output:
```
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 5.0.2 (OSX,.NETCoreApp,Version=v2.1)

Assertion failed: Package executable GitVersion.dll, or GitVersion.exe [GitVersion.Tool|GitVersion.CommandLine] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.0
StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetProcessToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
Member 'CurrentVersion2' is required to be not null.
   at Nuke.Common.Execution.RequirementService.ValidateRequirements(NukeBuild build, IReadOnlyCollection`1 executingTargets)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

```

**Comment by onelioubov** [comment]
It looks like it's still not using the latest version. What version of GitVersion.Tool are you using?

If you have the latest, it may be worth cleaning/restoring the build project, or even opening a new terminal window if it needs to update a path in your profile.

**Comment by cmenzi** [comment]
You can/should use `[GitVersion (Framework="netcoreapp3.0", NoFetch = true)]`. Because this is just the folder where Nuke is looking for the exe/dll in the `tools` directory of the nuget. 

And as already by @GeorgDangl mentioned, GitVersion is just a CLI that is called. So, it does not need to match and installing another SDK version is also not needed. 

GitVersion just don't provide a .NET 5.0 version in their nuget.

**Comment by oxffaa** [comment]
Ok, l think I found the reason. 
class Nuke.Common.Tooling.ToolPathResolver and method GetPackageExecutable
```
            ControlFlow.Assert(packageId != null && packageExecutable != null, "packageId != null && packageExecutable != null");

            // returns for me /Users/oxffaa/.nuget/packages/gitversion.tool/5.1.1
            var packageDirectory = GetPackageDirectory(packageId.Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries), version);
...
```

My .nuget catalog looks like:
```
❯ ls /Users/oxffaa/.nuget/packages/gitversion.tool
5.1.1 5.5.1
```

Of course, gitversion 5.1.1 doesn't support .net5. That happens because _biuld.csproj refers old version directly:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace></RootNamespace>
    <NoWarn>CS0649;CS0169</NoWarn>
    <NukeRootDirectory>..</NukeRootDirectory>
    <NukeScriptDirectory>..</NukeScriptDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nuke.Common" Version="5.0.2" />
    <PackageDownload Include="GitVersion.Tool" Version="[5.1.1]" />
  </ItemGroup>

</Project>

```

I changed the version from 5.1.1 to 5.6.1 and that resolved the problem at least locally.

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/commit/d41ec4542efd7a3a0218bd71ed331658862c2a54

**Comment by oxffaa** [comment]
I created pr for bumping GitVersion.Tool version in Nuke.GlobalTool template. Github actions failed cause I made pr via fork and my fork doesn't have secrets.CodecovToken I guess...

**Comment by onelioubov** [comment]
About that PR. Does bumping the version and not specifying the framework where you call it in your Build.cs still work for you? I'm concerned it may need further changes than just bumping the version. I could be wrong though and need to explore it more for myself :)

**Comment by matkoch** [comment]
`GitVersionAttribute` has a `Framework` property that must be set.

**Comment by jetersen** [comment]
> `GitVersionAttribute` has a `Framework` property that must be set.

If it must be set then `nuke :setup` should be updated to include that in the template. I struggled finding this comment 😅
