### ISSUE TITLE
[GitHub Actions] configuration.ShortTriggers.Length == 0 || configuration.DetailedTriggers.Length == 0

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#642]
### Description
Exception occurred when running the `nuke --help` command.
### Steps to reproduce
Link to `Build.cs`: https://github.com/krok-lives-matter/CaffeMenuBot_Back-End/tree/main/build
### Relevant log output
```
D:\Studying projects\CaffeMenuBot>nuke --help
PowerShell Desktop version 5.1.17763.1490
Microsoft (R) .NET Core SDK version 5.0.101
Assertion failed: configuration.ShortTriggers.Length == 0 || configuration.DetailedTriggers.Length == 0
   at Nuke.Common.CI.GitHubActions.GitHubActionsAttribute.GetConfiguration(NukeBuild build, IReadOnlyCollection`1 relevantTargets)
   at Nuke.Common.CI.ConfigurationAttributeBase.Generate(NukeBuild build, IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.CI.GenerateBuildServerConfigurationsAttribute.OnBeforeLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

[1/1] ProcessException: Process 'dotnet.exe' exited with code -1.
   > "C:\Program Files\dotnet\dotnet.exe" "D:\Studying projects\CaffeMenuBot\build\bin\Debug\_build.dll" --generate-configuration GitHubActions_nuke --host GitHubActions
   @ D:\Studying projects\CaffeMenuBot

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.CI.InvokeBuildServerConfigurationGenerationAttribute.HasConfigurationChanged(IConfigurationGenerator generator)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by matkoch** [comment]
that's expected. you have to set an `On*` property.

**Comment by vova-lantsov-dev** [comment]
@matkoch
```c#
[GitHubActions(
    "nuke",
    GitHubActionsImage.Ubuntu1804,
    GitHubActionsImage.MacOs1014,
    GitHubActionsImage.WindowsServer2019,
    OnPushBranches = new[] {"main"},
    InvokedTargets = new[] {nameof(Test)},
    ImportGitHubTokenAs = nameof(GitHubToken),
    On = new[] {GitHubActionsTrigger.Push})]
```
I've set the `OnPushBranches` property, not enough?

**Comment by matkoch** [comment]
Only one of them. Remove the `On` in this case.
