### ISSUE TITLE
Cannot invoke .NET SDK when installed with Snap on Linux

### ISSUE THREAD

**Issue by andrii-litvinov** [nuke-build/nuke#653]
### Description
Nuke.build cannot invoke `dotnet` commands when .NET SDK installed with [Snap on Linux](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap).

### Steps to reproduce

1. Install .NET SDK with Snap on Linux
2. Invoke `DotNet("--info")` command in a build target.
3. Run build project `dotnet run --project Build.Project.Name -- Target`

### Relevant log output

```
NUKE Execution Engine version 5.0.0 (Linux,.NETCoreApp,Version=v2.1)


╬════════════
║ Target
╬═══

> /snap/bin/dotnet --info
ProcessException: Process 'dotnet' exited with code 134.
> /snap/bin/dotnet --info
ProcessException: Process 'dotnet' exited with code 134.
   > /snap/bin/dotnet --info
   @ /home/user/project

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNet(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Nullable`1 logTimestamp, String logFile, Func`2 outputFilter)
   at Build.CommonTasks.CreateSolution(AbsolutePath sln, AbsolutePath[] projectPaths) in /home/user/project/Build/CommonTasks.cs:line 95
   at Build.CustomBuild.<get_Compile>b__33_2(DotNetBuildSettings buildSettings) in /home/user/project/Build/Targets.cs:line 43
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetBuild(Configure`1 configurator)
   at Build.CustomBuild.<get_Compile>b__33_1() in /home/user/project/Build/Targets.cs:line 37
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass61_0`1.<Executes>b__0()
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```
When I run same build project from Rider all works just fine, but  I noticed that Rider resolves `dotnet` from `/snap/dotnet-sdk/current/dotnet` rather than `/snap/bin/dotnet` when starting the build. Invocation from shell resolves `dotnet` from `/snap/bin/dotnet`.

It likely relates to https://github.com/OmniSharp/omnisharp-vscode/issues/3077 and https://github.com/dotnet/sdk/issues/10373 and workaround 
```sh
sudo ln -sv /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet
```
solves the issue, but I guess it would be nice if Nuke could handle in on its own somehow. Or maybe at least it worth documenting this issue so that it's easy to find a solution when it happens.

**Comment by matkoch** [comment]
I have no plans to look into this (except maybe with sponsorship). A PR might work, but also can't promise on that. Workaround is to set `DOTNET_EXE`.

**Comment by phillipsj** [comment]
@matkoch If you want to reopen this and assign it to me. The best place is to probably do it in the bootstrappers and I have that ready to go.

**Comment by matkoch** [comment]
why is dotnet not in PATH when installed via snap?

**Comment by phillipsj** [comment]
It is in the path just not where you expect it. There is a symlink created that is "/snap/bin/dotnet" that points to "/snap/dotnet-sdk/current/dotnet". That makes the dotnet root "/snap/dotnet-sdk/current". Global tools don't detect that correctly. I wrote a blog post about it [here](https://www.phillipsj.net/posts/dotnet-global-tools-with-dotnet-snap/).  

I also submitted an update to the docs to identify that a snap install doesn't set the DOTNET_ROOT environment variable and MS investigated coming to the same conclusion. [Here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap#export-the-install-location) is that link.

**Comment by matkoch** [comment]
> You should configure the DOTNET_ROOT environment variable in your profile.

that doesn't sound like it should go in the build.sh/ps1 files

**Comment by matkoch** [comment]
A similar case is documented for ZSH: https://www.nuke.build/docs/getting-started/setup.html

Also no special handling in bootstrapping files...
