### ISSUE TITLE
Error generating TeamCity configuration

### ISSUE THREAD

**Issue by mortengjesing** [nuke-build/nuke#674]
### Description
Hi,

I am working on some templates, and want them to create TeamCity config files. But I get `InvalidOperationException: Sequence contains no matching element` error if I override a target in the template with a target that triggers another target in the template.

### Steps to reproduce

1. Update Build.cs with following content

```
using Nuke.Common;
using Nuke.Common.CI.TeamCity;

[TeamCity(TeamCityAgentPlatform.Unix,
    VcsTriggeredTargets = new[] { nameof(Target1) },
    NonEntryTargets = new[] { nameof(Target2) }
)]
class Build : Template
{
    public static int Main() => Execute<Build>(x => x.Target1);

    public override Target Target2 => _ => _
        .Triggers(Target3)
        .Executes(() =>
        {
        });
}

class Template : NukeBuild
{
    public virtual Target Target1 => _ => _
        .Triggers(Target2)
        .Executes(() =>
        {
        });

    public virtual Target Target2 => _ => _
        .Executes(() =>
        {
        });

    public virtual Target Target3 => _ => _
        .Executes(() =>
        {
        });
}
```

2. Run build.ps1

### Relevant log output
Running on Nuke 5.0.2

```
PowerShell Desktop version 5.1.19041.610
Microsoft (R) .NET Core SDK version 5.0.100

InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.CI.TeamCity.TeamCityAttribute.GetTriggers(ExecutableTarget executableTarget, LookupTable`2 buildTypes)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nuke.Common.CI.TeamCity.TeamCityAttribute.GetBuildTypes(NukeBuild build, ExecutableTarget executableTarget, TeamCityVcsRoot vcsRoot, LookupTable`2 buildTypes, IReadOnlyCollection`1 relevantTargets)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEachLazy[T](IEnumerable`1 enumerable, Action`1 action)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nuke.Common.CI.TeamCity.TeamCityAttribute.GetProject(NukeBuild build, IReadOnlyCollection`1 relevantTargets)
   at Nuke.Common.CI.TeamCity.TeamCityAttribute.GetConfiguration(NukeBuild build, IReadOnlyCollection`1 relevantTargets)
   at Nuke.Common.CI.ConfigurationAttributeBase.Generate(NukeBuild build, IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.CI.GenerateBuildServerConfigurationsAttribute.OnBeforeLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

[1/1] ProcessException: Process 'dotnet.exe' exited with code -1.
   > "C:\Program Files\dotnet\dotnet.exe" D:\GitHub\NukeTeamCity\build\bin\Debug\_build.dll --generate-configuration TeamCity --host TeamCity
   @ D:\GitHub\NukeTeamCity

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.CI.InvokeBuildServerConfigurationGenerationAttribute.HasConfigurationChanged(IConfigurationGenerator generator)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by matkoch** [comment]
Use `DependsOn` instead.

**Comment by mortengjesing** [comment]
I know there is workarounds, but I still think this is a bug. 
Spent a lot of time figuring out why this happens, so I think it should be fixed, so others avoids the problem.

**Comment by mortengjesing** [comment]
I can give a PR a go if you want help?

**Comment by matkoch** [comment]
It's not a bug, it's a configuration error. You can't mark `Target2` as non-entry for the same reason a `TargetB` with `DependsOn(TargetA)` cannot be marked as non-entry while being VCS-triggered. The latter doesn't throw an error, but the generated config isn't valid either.

**Comment by mortengjesing** [comment]
I don't understand why my case `Target1 (VCS) -> Target2 (Non) -> Target 3 (Non) ` is not a valid configuration. I want to everything to be build on a single agent, like described here https://github.com/nuke-build/nuke/issues/450 

Nuke also uses a similar method here `Pack (VCS) -> Compile -> Restore (Non)`
https://github.com/nuke-build/nuke/blob/65000352b980c18b000301b44c4685a9dd9b3257/build/Build.cs#L66-L71

**Comment by matkoch** [comment]
The original example doesn't declare `Target3` as non-entry.
