### ISSUE TITLE
Nuke IDE integration for Visual Studio Community 2019 fails to install

### ISSUE THREAD

**Issue by Cyberunner23** [nuke-build/nuke#697]
### Description
The nuke IDE integration available [here](https://marketplace.visualstudio.com/items?itemName=nuke.visualstudio) fails to install on Visual Studio Community 2019 (Version 16.9.0)

### Steps to reproduce

1. Install Visual Studio Community 2019 (Version 16.9.0)
2. Install the nuke IDE integration
3. Notice that the installation fails

### Relevant log output

```
3/7/2021 9:31:38 PM - Microsoft VSIX Installer
3/7/2021 9:31:38 PM - -------------------------------------------
3/7/2021 9:31:38 PM - vsixinstaller.exe version:
3/7/2021 9:31:38 PM - 16.9.1050
3/7/2021 9:31:38 PM - -------------------------------------------
3/7/2021 9:31:38 PM - Command line parameters:
3/7/2021 9:31:38 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ALEXFL~1\AppData\Local\Temp\Nuke.VisualStudio.vsix
3/7/2021 9:31:38 PM - -------------------------------------------
3/7/2021 9:31:38 PM - Microsoft VSIX Installer
3/7/2021 9:31:38 PM - -------------------------------------------
3/7/2021 9:31:41 PM - Initializing Install...
3/7/2021 9:31:41 PM - Extension Details...
3/7/2021 9:31:41 PM - 	Identifier         : Nuke.VisualStudio
3/7/2021 9:31:41 PM - 	Name               : NUKE Support
3/7/2021 9:31:41 PM - 	Author             : NUKE
3/7/2021 9:31:41 PM - 	Version            : 16.8.0
3/7/2021 9:31:41 PM - 	Description        : Task Runner integration for execution of targets and code snippets for authoring
3/7/2021 9:31:41 PM - 	Locale             : en-US
3/7/2021 9:31:41 PM - 	MoreInfoURL        : https://github.com/nuke-build/visualstudio
3/7/2021 9:31:41 PM - 	InstalledByMSI     : False
3/7/2021 9:31:41 PM - 	SupportedFrameworkVersionRange : [4.6,)
3/7/2021 9:31:41 PM - 
3/7/2021 9:31:41 PM - 	SignatureState     : Unsigned
3/7/2021 9:31:41 PM - 	Supported Products : 
3/7/2021 9:31:41 PM - 		Microsoft.VisualStudio.Community
3/7/2021 9:31:41 PM - 			Version : [16.8]
3/7/2021 9:31:41 PM - 		Microsoft.VisualStudio.Pro
3/7/2021 9:31:41 PM - 			Version : [16.8]
3/7/2021 9:31:41 PM - 		Microsoft.VisualStudio.Enterprise
3/7/2021 9:31:41 PM - 			Version : [16.8]
3/7/2021 9:31:41 PM - 
3/7/2021 9:31:41 PM - 	References         : 
3/7/2021 9:31:41 PM - 		-------------------------------------------------------
3/7/2021 9:31:41 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
3/7/2021 9:31:41 PM - 		Name         : Visual Studio MPF 14.0
3/7/2021 9:31:41 PM - 		Version      : [14.0]
3/7/2021 9:31:41 PM - 		MoreInfoURL  : 
3/7/2021 9:31:41 PM - 		Nested       : No
3/7/2021 9:31:41 PM - 
3/7/2021 9:31:41 PM - 	Prerequisites      : 
3/7/2021 9:31:41 PM - 		-------------------------------------------------------
3/7/2021 9:31:41 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/7/2021 9:31:41 PM - 		Name         : Visual Studio core editor
3/7/2021 9:31:41 PM - 		Version      : [15.0,)
3/7/2021 9:31:41 PM - 
3/7/2021 9:31:41 PM - Signature Details...
3/7/2021 9:31:41 PM - 	Extension is not signed.
3/7/2021 9:31:41 PM - 
3/7/2021 9:31:41 PM - Searching for applicable products...
3/7/2021 9:31:41 PM - Found installed product - Global Location
3/7/2021 9:31:41 PM - Found installed product - AtmelStudio
3/7/2021 9:31:41 PM - Found installed product - Visual Studio Community 2019
3/7/2021 9:31:42 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by sharpninja** [comment]
## My log 
 
```
3/16/2021 4:59:03 AM - Microsoft VSIX Installer
3/16/2021 4:59:03 AM - -------------------------------------------
3/16/2021 4:59:03 AM - vsixinstaller.exe version:
3/16/2021 4:59:03 AM - 16.10.10
3/16/2021 4:59:03 AM - -------------------------------------------
3/16/2021 4:59:03 AM - Command line parameters:
3/16/2021 4:59:03 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\kingd\Downloads\Nuke.VisualStudio.vsix
3/16/2021 4:59:03 AM - -------------------------------------------
3/16/2021 4:59:03 AM - Microsoft VSIX Installer
3/16/2021 4:59:03 AM - -------------------------------------------
3/16/2021 4:59:03 AM - Initializing Install...
3/16/2021 4:59:04 AM - Extension Details...
3/16/2021 4:59:04 AM - 	Identifier         : Nuke.VisualStudio
3/16/2021 4:59:04 AM - 	Name               : NUKE Support
3/16/2021 4:59:04 AM - 	Author             : NUKE
3/16/2021 4:59:04 AM - 	Version            : 16.8.0
3/16/2021 4:59:04 AM - 	Description        : Task Runner integration for execution of targets and code snippets for authoring
3/16/2021 4:59:04 AM - 	Locale             : en-US
3/16/2021 4:59:04 AM - 	MoreInfoURL        : https://github.com/nuke-build/visualstudio
3/16/2021 4:59:04 AM - 	InstalledByMSI     : False
3/16/2021 4:59:04 AM - 	SupportedFrameworkVersionRange : [4.6,)
3/16/2021 4:59:04 AM - 
3/16/2021 4:59:04 AM - 	SignatureState     : Unsigned
3/16/2021 4:59:04 AM - 	Supported Products : 
3/16/2021 4:59:04 AM - 		Microsoft.VisualStudio.Community
3/16/2021 4:59:04 AM - 			Version : [16.8]
3/16/2021 4:59:04 AM - 		Microsoft.VisualStudio.Pro
3/16/2021 4:59:04 AM - 			Version : [16.8]
3/16/2021 4:59:04 AM - 		Microsoft.VisualStudio.Enterprise
3/16/2021 4:59:04 AM - 			Version : [16.8]
3/16/2021 4:59:04 AM - 
3/16/2021 4:59:04 AM - 	References         : 
3/16/2021 4:59:04 AM - 		-------------------------------------------------------
3/16/2021 4:59:04 AM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
3/16/2021 4:59:04 AM - 		Name         : Visual Studio MPF 14.0
3/16/2021 4:59:04 AM - 		Version      : [14.0]
3/16/2021 4:59:04 AM - 		MoreInfoURL  : 
3/16/2021 4:59:04 AM - 		Nested       : No
3/16/2021 4:59:04 AM - 
3/16/2021 4:59:04 AM - 	Prerequisites      : 
3/16/2021 4:59:04 AM - 		-------------------------------------------------------
3/16/2021 4:59:04 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/16/2021 4:59:04 AM - 		Name         : Visual Studio core editor
3/16/2021 4:59:04 AM - 		Version      : [15.0,)
3/16/2021 4:59:04 AM - 
3/16/2021 4:59:04 AM - Signature Details...
3/16/2021 4:59:04 AM - 	Extension is not signed.
3/16/2021 4:59:04 AM - 
3/16/2021 4:59:04 AM - Searching for applicable products...
3/16/2021 4:59:04 AM - Found installed product - Global Location
3/16/2021 4:59:04 AM - Found installed product - Visual Studio Community 2019
3/16/2021 4:59:04 AM - Found installed product - Visual Studio Community 2019 Preview
3/16/2021 4:59:04 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Downloaded from Visual Studio Marketplace through the link in the comments of my _build project.

**Comment by vbornand** [comment]
Same with Visual Studio Professional 16.9.3 (latest non-preview version)

```
31.03.2021 16:33:51 - Microsoft VSIX Installer
31.03.2021 16:33:51 - -------------------------------------------
31.03.2021 16:33:51 - vsixinstaller.exe version:
31.03.2021 16:33:51 - 16.10.10
31.03.2021 16:33:51 - -------------------------------------------
31.03.2021 16:33:51 - Command line parameters:
31.03.2021 16:33:51 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ValentinBornand\Downloads\Nuke.VisualStudio (4).vsix
31.03.2021 16:33:51 - -------------------------------------------
31.03.2021 16:33:51 - Microsoft VSIX Installer
31.03.2021 16:33:51 - -------------------------------------------
31.03.2021 16:33:52 - Skipping product Microsoft.VisualStudio.Product.BuildTools (047787b6) since it does not support extensions
31.03.2021 16:33:52 - Initializing Install...
31.03.2021 16:33:52 - Extension Details...
31.03.2021 16:33:52 - 	Identifier         : Nuke.VisualStudio
31.03.2021 16:33:52 - 	Name               : NUKE Support
31.03.2021 16:33:52 - 	Author             : NUKE
31.03.2021 16:33:52 - 	Version            : 16.8.0
31.03.2021 16:33:52 - 	Description        : Task Runner integration for execution of targets and code snippets for authoring
31.03.2021 16:33:52 - 	Locale             : en-US
31.03.2021 16:33:52 - 	MoreInfoURL        : https://github.com/nuke-build/visualstudio
31.03.2021 16:33:52 - 	InstalledByMSI     : False
31.03.2021 16:33:52 - 	SupportedFrameworkVersionRange : [4.6,)
31.03.2021 16:33:52 - 
31.03.2021 16:33:52 - 	SignatureState     : Unsigned
31.03.2021 16:33:52 - 	Supported Products : 
31.03.2021 16:33:52 - 		Microsoft.VisualStudio.Community
31.03.2021 16:33:52 - 			Version : [16.8]
31.03.2021 16:33:52 - 		Microsoft.VisualStudio.Pro
31.03.2021 16:33:52 - 			Version : [16.8]
31.03.2021 16:33:52 - 		Microsoft.VisualStudio.Enterprise
31.03.2021 16:33:52 - 			Version : [16.8]
31.03.2021 16:33:52 - 
31.03.2021 16:33:52 - 	References         : 
31.03.2021 16:33:52 - 		-------------------------------------------------------
31.03.2021 16:33:52 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
31.03.2021 16:33:52 - 		Name         : Visual Studio MPF 14.0
31.03.2021 16:33:52 - 		Version      : [14.0]
31.03.2021 16:33:52 - 		MoreInfoURL  : 
31.03.2021 16:33:52 - 		Nested       : No
31.03.2021 16:33:52 - 
31.03.2021 16:33:52 - 	Prerequisites      : 
31.03.2021 16:33:52 - 		-------------------------------------------------------
31.03.2021 16:33:52 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
31.03.2021 16:33:52 - 		Name         : Visual Studio core editor
31.03.2021 16:33:52 - 		Version      : [15.0,)
31.03.2021 16:33:52 - 
31.03.2021 16:33:52 - Signature Details...
31.03.2021 16:33:52 - 	Extension is not signed.
31.03.2021 16:33:52 - 
31.03.2021 16:33:52 - Searching for applicable products...
31.03.2021 16:33:52 - Found installed product - Global Location
31.03.2021 16:33:52 - Found installed product - Visual Studio Professional 2019
31.03.2021 16:33:52 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by vbornand** [comment]
A simple workaround:
1) Download the Nuke.VisualStudio.vsix file
2) Rename it: Nuke.VisualStudio.zip
3) Unzip it
4) Edit the file extension.vsixmanifest (line 16,17,18) to authorize the versions 16.x (x >= 8):
```
    <InstallationTarget Version="[16.8,17.0)" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[16.8,17.0)" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[16.8,17.0)" Id="Microsoft.VisualStudio.Enterprise" />
```
5) Zip the file again
6) Rename it Nuke.VisualStudio.vsix 
7) Install it

The vsixmanifest file is not in this git, so we cannot do a PR.
There is maybe a good reason to allow only the version 16.8 but it seems to works well with the version 16.9.x.

**Comment by sharpninja** [comment]
If the manifest is the only problem then please just update the package and push it again.

**Comment by matkoch** [comment]
@sharpninja thanks for the advice

**Comment by matkoch** [comment]
Uploaded 16.9

**Comment by marcotod1410** [comment]
This issue is still happening on Visual Studio 2019 Enterprise for me. 
I tried to install the extension, but I get the very same error reported above. My VS version is 16.11.2 on Windows 10 x64.

Thanks to the help provided by @vbornand I was able to install it by replacing the `Version` attribute value in the manifest extension to `[16.9, 17.0)`, so allowing all minor and patch releases of Visual Studio, subsequent to 16.9 version, to be compatible with this extension. The latest extension update was reported only to be compatible with 16.9 version.

I may be wrong, but I think it's reasonable to assume that the extension will not break over subsequent minor releases of Visual Studio, so please consider to update the manifest accordingly.
