### ISSUE TITLE
InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#710]
### Description
Method `Main`, call to `Compile<Build>` with multiple expressions as default targets.

### Steps to reproduce

1. Clone the project locally: https://github.com/vlrpi/build
2. Run `nuke --help`

### Relevant log output

```
InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Execution.HelpTextService.GetParametersText(NukeBuild build)
   at Nuke.Common.Execution.HandleHelpRequestsAttribute.OnAfterLogo(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__ExecuteExtension|1[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by BusHero** [comment]
I'm still experiencing this issue.
