### ISSUE TITLE
Nuke 5.0.2 with GitVersion-Attribute requires .NET Framework 3.1/2.1 

### ISSUE THREAD

**Issue by mwenk** [nuke-build/nuke#731]
When you're using the GitVersionAttribute in any Nuke-Build, this requires a non .NET 5 Runtime.
I know there's a workaround by setting another framework version - but as I'm using a docker sdk5 image, this is no option.

Output without when using `[GitVersion] readonly GitVersion GitVersion;`  :

```
NUKE Execution Engine version 5.0.2 (Windows,.NETCoreApp,Version=v2.1)

Assertion failed: Package executable GitVersion.dll, or GitVersion.exe [GitVersion.Tool|GitVersion.CommandLine] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.1
StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetProcessToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
```

Output when using `[GitVersion(Framework = "netcoreapp3.1")] readonly GitVersion GitVersion;` :

```
NUKE Execution Engine version 5.0.2 (Linux,.NETCoreApp,Version=v2.1)
> /usr/bin/dotnet /root/.nuget/packages/gitversion.tool/5.5.1/tools/netcoreapp3.1/any/gitversion.dll
Process 'dotnet' exited with code 150.
   > /usr/bin/dotnet /root/.nuget/packages/gitversion.tool/5.5.1/tools/netcoreapp3.1/any/gitversion.dll
   @ /builds/mwenk/sailrace2021/backend/src/Sailrace
Error output:
   It was not possible to find any compatible framework version
   The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
     - The following frameworks were found:
         5.0.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
   
```

**Comment by GeorgDangl** [comment]
I think you can just upgrade to `GitVersion` 5.6.6, that should support `net5.0`.

**Comment by mwenk** [comment]
I don't have GitVersion installed, also can't find a nuget package with that name.

**Comment by mwenk** [comment]
I've added  GitVersion.CommandLine, Version="5.6.7 - this seems to work.
Thanks for the hint Georg!
