### ISSUE TITLE
Error occurred while calling 'nuke :setup' (version of Nuke: 5.1.0)

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#736]
### Description
I think that the space symbol is recognized as separator, not as part of path. But not sure.

### Relevant log output
```
NUKE Global Tool version 5.1.0 (Windows,.NETCoreApp,Version=v2.1)
How should the build project be named?
┐  _build
Where should the build project be located?
┐  ./build
Which NUKE version should be used?
┐  5.1.0 (latest release)
Which solution should be the default?
┐  Telegram.Bot.Helper.sln
Do you need help getting started with a basic build?
┐  Yes, get me started!
Restore, compile, pack using ...
┐  dotnet CLI
Source files are located in ...
┐  ./src
Move packages to ...
┐  ./output
Where do test projects go?
┐  ./tests
Do you use GitVersion?
┐  No, custom versioning
Creating directory 'D:\Studying projects\telegram-bot-helper\.nuke'...
ProcessException: Process 'git.exe' exited with code 128.
   > "C:\Program Files\Git\cmd\git.exe" add D:\Studying projects\telegram-bot-helper\.nuke\parameters.json
   @ D:\Studying projects\telegram-bot-helper
Error output:
   fatal: D:\Studying: 'D:\Studying' is outside repository at 'D:/Studying projects/telegram-bot-helper'

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in C:\projects\nuke-deployment\source\Nuke.Common\Tooling\ProcessExtensions.cs:line 35
   at Nuke.Common.Tools.Git.GitTasks.Git(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Nullable`1 logTimestamp, String logFile, Func`2 outputFilter) in C:\projects\nuke-deployment\source\Nuke.Common\Tools\Git\Git.Generated.cs:line 43
   at Nuke.GlobalTool.Program.WriteConfigurationFile(AbsolutePath rootDirectory, AbsolutePath solutionFile) in C:\projects\nuke-deployment\source\Nuke.GlobalTool\Program.Setup.cs:line 386
   at Nuke.GlobalTool.Program.Setup(String[] args, AbsolutePath rootDirectory, AbsolutePath buildScript) in C:\projects\nuke-deployment\source\Nuke.GlobalTool\Program.Setup.cs:line 204
```

**Comment by matkoch** [comment]
Thanks! Fixed in vnext

**Comment by vova-lantsov-dev** [comment]
@matkoch just sent a PR :) You can close it

**Comment by vova-lantsov-dev** [comment]
@matkoch and when do you plan to release 5.1.1?

**Comment by matkoch** [comment]
Monday probably :$
