### ISSUE TITLE
:setup fails if there are spaces in the project path

### ISSUE THREAD

**Issue by jeffreycoxdoosan** [nuke-build/nuke#741]
### Version

5.1.0 (latest release)

### Expected Behavior

* Launch a command prompt and execute the following commands:
>mkdir "my folder"
>cd "my folder"
>dotnet new console -o myApp
>cd "myApp"
>git init
>nuke :setup
* choose the defaults in the nuke setup

Expected: Setup succeeds.

### What actually happened?

Setup fails with the following exception:

```
ProcessException: Process 'git.exe' exited with code 128.
   > "C:\Program Files\Git\cmd\git.exe" add C:\Users\jcox\my folder\myApp\.nuke\parameters.json
   @ C:\Users\jcox\my folder\myApp
Error output:
   fatal: C:\Users\jcox\my: 'C:\Users\jcox\my' is outside repository at 'C:/Users/jcox/my folder/myApp'

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in C:\projects\nuke-deployment\source\Nuke.Common\Tooling\ProcessExtensions.cs:line 35
   at Nuke.Common.Tools.Git.GitTasks.Git(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Nullable`1 logTimestamp, String logFile, Func`2 outputFilter) in C:\projects\nuke-deployment\source\Nuke.Common\Tools\Git\Git.Generated.cs:line 43
   at Nuke.GlobalTool.Program.WriteConfigurationFile(AbsolutePath rootDirectory, AbsolutePath solutionFile) in C:\projects\nuke-deployment\source\Nuke.GlobalTool\Program.Setup.cs:line 386
   at Nuke.GlobalTool.Program.Setup(String[] args, AbsolutePath rootDirectory, AbsolutePath buildScript) in C:\projects\nuke-deployment\source\Nuke.GlobalTool\Program.Setup.cs:line 204
```

### Anything else we should know?

If the space is removed from "my folder" :setup succeeds

**Comment by jeffreycoxdoosan** [comment]
@matkoch  Duplicate of what though?
