### ISSUE TITLE
Multiple VCS Roots in Teamcity build config cause version calculation with OctoVersion to fail

### ISSUE THREAD

**Issue by cailyoung** [nuke-build/nuke#744]
### Version

5.1.0

### Relevant Code

```code
I believe it's happening while trying to run CalculateVersion
```

### Expected Behavior

Teamcity build configurations with multiple VCS roots should be able to calculate versions.

JetBrains says that build.vcs.number [isn't available](https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#Server+Build+Properties) when there are multiple VCS roots.

### Stacktrace

```code
KeyNotFoundException: The given key 'build.vcs.number' was not present in the dictionary.
05:20:12
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
05:20:12
     at Nuke.Common.CI.TeamCity.TeamCity.get_BuildVcsNumber()
05:20:12
     at Nuke.Common.CI.TeamCity.TeamCity.Nuke.Common.CI.IBuildServer.get_Commit()
05:20:12
     at Nuke.Common.Git.GitRepository.GetCommitFromCI()
05:20:12
     at Nuke.Common.Execution.ArgumentsFromCommitMessageAttribute.OnBuildCreated(NukeBuild build, IReadOnlyCollection`1 executableTargets)
05:20:12
     at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
05:20:12
     at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
05:20:12
     at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by matkoch** [comment]
sorry, but i don't consider this critical and will therefore close as per template notice
