### ISSUE TITLE
`ArgumentsFromCommitMessageAttribute` fails on non git repositories

### ISSUE THREAD

**Issue by batzen** [nuke-build/nuke#746]
### Version

5.1

### Relevant Code / Invocations

```code
`NukeBuild` has `ArgumentsFromCommitMessageAttribute` which does not work when using a non git repository.
As every `NukeBuild` is the base class it seems impossible to work around this issue.
Builds, in this case, only fail if the build runs in our CI system.
```

### Expected Behavior

`ArgumentsFromCommitMessageAttribute` should just do nothing if the current repo is not using git or it should work with other VCS systems.

### What actually happened?

```
[12:31:46]	Creating directory 'C:\buildagent\work\core\.nuke\temp'...
[12:31:47]	ProcessException: Process 'git.exe' exited with code 128.
[12:31:47]	   > "C:\Program Files\Git\cmd\git.exe" show -s --format=%B 185053
[12:31:47]	   @ C:\buildagent\work\core
[12:31:47]	Error output:
[12:31:47]	   fatal: not a git repository (or any of the parent directories): .git
[12:31:47]	
[12:31:47]	   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
[12:31:47]	   at Nuke.Common.Tools.Git.GitTasks.Git(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Nullable`1 logTimestamp, String logFile, Func`2 outputFilter)
[12:31:47]	   at Nuke.Common.Execution.ArgumentsFromCommitMessageAttribute.OnBuildCreated(NukeBuild build, IReadOnlyCollection`1 executableTargets)
[12:31:47]	   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
[12:31:47]	   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
[12:31:47]	   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### Anything else we should know?

`nuke :update` also failed in our case as it's also tied to git.

**Comment by Nefarion** [comment]
Had the same problem, i worked around it by undeclaring the Environment variable responsible for the commit detection   
(in my case [GitLab](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/CI/GitLab/GitLab.cs#L83)) , because it was not used in this specific instance anyways.

I 100% agree with you, this attribute should be opt-in maybe, not by default?
