### ISSUE TITLE
NerdbankGitVersion crash

### ISSUE THREAD

**Issue by laurentkempe** [nuke-build/nuke#757]
### Usage Information

5.1.2 / 5.0.202 / .NET 5.0 / Win 10 

### Relevant Code / Invocations

```code
Defining the following in Build.cs

    [NerdbankGitVersioning] readonly NerdbankGitVersioning GitVersion;
```

### Expected Behavior

Running [nbgv ](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md) should run and create the output file in json or text

### What actually happened?

Crashes due to the wrong casing passed to nbgv for the format parameter; nuke pass `--format Json` in place of the expected lower case `--format json`. The same apply to the text format.

### Stacktrace / Log

```code
Process 'dotnet.exe' exited with code 1.
     > "C:\Program Files\dotnet\dotnet.exe" C:\nuget\nbgv\3.4.205\tools\netcoreapp2.1\any\nbgv.dll get-version --format Json
     @ C:\BuildAgent\work\489da8d67f1132ce
  Error output:
     Argument 'Json' not recognized. Must be one of:
       'text'
       'json'
     
  
  StackTrace:
     at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
     at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningTasks.NerdbankGitVersioningGetVersion(NerdbankGitVersioningGetVersionSettings toolSettings)
     at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningTasks.NerdbankGitVersioningGetVersion(Configure`1 configurator)
     at Nuke.Common.Tools.NerdbankGitVersioning.NerdbankGitVersioningAttribute.GetValue(MemberInfo member, Object instance)
     at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
```

**Comment by matkoch** [comment]
See No. 6 in contribution guidelines.

**Comment by laurentkempe** [comment]
> No issues for additional CLT support or missing arguments.

@matkoch You already told me but my understanding was it was only for the generated one and as I was navigating to the code I did fail to check it was generated!
