### ISSUE TITLE
Telemetry looks for 'dotnet' even though telemetry is disabled

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#765]
### Usage Information

5.2.1 / .NET 5 / Windows/Linux

### Expected Behavior

Running a self-contained nuke compilation on a Linux environment with no dotnet installed and environment variable NUKE_TELEMETRY_OPTOUT=1 should lead to no exception since I intend to use Nuke to build non-dotnet code, dotnet should not be required to be available

### What actually happened?

Telemetry tries to get DotNetPath. Either Telemetry opt-out is broken, or Telemetry tries to collect data that it does not intend to use. 

### Stacktrace / Log

```code
Assertion failed: Could not find 'dotnet' via '/usr/bin/which'.
   at Nuke.Common.Tooling.ToolPathResolver.GetPathExecutable(String pathExecutable)
   at Nuke.Common.Tools.DotNet.DotNetTasks.get_DotNetPath()
   at Nuke.Common.Execution.Telemetry.GetCommonProperties(NukeBuild build)
   at Nuke.Common.Execution.Telemetry.BuildStarted(NukeBuild build)
   at Nuke.Common.Execution.TelemetryAttribute.OnBuildInitialized(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### Anything else we should know?

Placing a dummy 'dotnet' application in /usr/bin is a viable workaround.

**Comment by matkoch** [comment]
the opt-out works, it's just that the event will be created anyways
