### ISSUE TITLE
Jenkins Instance variable not set

### ISSUE THREAD

**Issue by fvaillancourt** [nuke-build/nuke#776]
### Usage Information

Nuke 5.3.0/.NET 5.0/.NET 5.0/Windows 10

### Relevant Code / Invocations

```code
Using Nuke 5.3.0
With NukeTelemetryVersion NOT set in project
With or without NUKE_TELEMETRY_OPTOUT set as environment variable
With all jenkins environment variables set (I dumped them out)
When building in Jenkins (No input keyboard/console)

We get this:
Telemetry v1
------------
NUKE collects anonymous usage data in order to help us improve your experience.
Read more about scope, data points, and opt-out: https://nuke.build/telemetry

Press <Enter> to set the 'NukeTelemetryVersion' property...
Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
StackTrace:
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Nuke.Common.Execution.Telemetry.WaitForEnter()
   at Nuke.Common.Execution.Telemetry.PrintDisclosure(String action)
   at Nuke.Common.Execution.Telemetry.CheckAwareness()

And from then, Jenkins.Instance is NOT set, even if it is building in Jenkins. Maybe the exception ends the initialization sequence early?
For the NUKE_TELEMETRY_OPTOUT I have less data but it seems like even though I do not get the prompt it does not work?
```

### Expected Behavior

The prompt for telemetry should not throw in CI, especially with NUKE_TELEMETRY_OPTOUT set

### Stacktrace / Log

```code
Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
StackTrace:
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Nuke.Common.Execution.Telemetry.WaitForEnter()
   at Nuke.Common.Execution.Telemetry.PrintDisclosure(String action)
   at Nuke.Common.Execution.Telemetry.CheckAwareness()
```

### Anything else we should know?

Reverting to 5.1.1 and everything works again.

**Comment by matkoch** [comment]
From the docs:

> For a build project, it will add the NukeTelemetryVersion property to the project file. Both the awareness cookie and project property are mandatory even when opting-out.
