### ISSUE TITLE
Doesn't works on docker windows 

### ISSUE THREAD

**Issue by oli-unreal** [nuke-build/nuke#799]
### Usage Information

Nuke version 5.3.0 / .net 5.0 / docker windows

### Relevant Code / Invocations

Nuke doesn't seems to work on docker windows. It works fine on docker linux and on a non-docker windows.

On an empty folder setup a new nuke build with `nuke :setup` with default value then create a dockerfile:
```code
FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR C:/build
SHELL ["pwsh", "-c"]
COPY ./ ./
RUN ./build.ps1 --target Clean
```

### Expected Behavior

The clean target is runned

### What actually happened?

The build fails.

### Stacktrace / Log

```code
docker build .
Sending build context to Docker daemon  24.58kB
Step 1/5 : FROM mcr.microsoft.com/dotnet/sdk:5.0
 ---> 322a4757e618
Step 2/5 : WORKDIR C:/build
 ---> Using cache
 ---> 80473ebefb1e
Step 3/5 : SHELL ["pwsh", "-c"]
 ---> Using cache
 ---> 0909d6da1f1a
Step 4/5 : COPY ./ ./
 ---> 0462fcd8aa86
Step 5/5 : RUN ./build.ps1 --target Clean
 ---> Running in cf59074fd586
PowerShell Core version 7.1.1
Microsoft (R) .NET Core SDK version 5.0.102
CSC : warning CS8032: An instance of analyzer Nuke.SourceGenerators.StronglyTypedSolutionGenerator cannot be created from C:\Users\ContainerUser\.nuget\packages\nuke.common\5.3.0\analyzers\dotnet\cs\Nuke.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\build\build\_build.csproj]
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception.
 ---> System.Exception: Assertion failed: Path '' must be rooted.
   at Nuke.Common.ControlFlow.Fail(String text, Exception exception)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.IO.AbsolutePath.op_Explicit(String path)
   at Nuke.Common.Constants.get_GlobalNukeDirectory()
   at Nuke.Common.Constants.TryGetRootDirectoryFrom(String startDirectory, Boolean includeLegacy)
   at Nuke.Common.NukeBuild.GetRootDirectory()
   at Nuke.Common.NukeBuild..cctor()
   --- End of inner exception stack trace ---
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions)
   at Build.Main() in C:\build\build\Build.cs:line 22
The command 'pwsh -c ./build.ps1 --target Clean' returned a non-zero code: 1
```

**Comment by matkoch** [comment]
I suppose there is something wrong with your mapping and it can't find the `.nuke` file/directory. For further questions I suggest asking in the Slack channel.
