### ISSUE TITLE
BenchmarkDotNet Error

### ISSUE THREAD

**Issue by satishviswanathan** [nuke-build/nuke#800]
### Usage Information

5.1.2

### Relevant Code / Invocations

```code
Target BenchMarkTests => _ => _
        
        .Executes(() =>
        {

            BenchmarkDotNetTasks.BenchmarkDotNet(settings =>
            {
                return settings.SetJob(BenchmarkDotNetJob.Medium)
                    .SetExporters(BenchmarkDotNetExporter.HTML)
                    .SetProcessWorkingDirectory(BenchMarkDirectory);


            });

           
        });
```

### Expected Behavior

Run BenchMarkDotnet and generate report

### What actually happened?

System.Exception
  HResult=0x80131500
  Message=Missing package reference/download.
Run one of the following commands:
  - nuke :add-package benchmarkdotnet.tool --version 0.12.1
  Source=Nuke.Common

### Stacktrace / Log

```code
StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text, Exception exception)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.BenchmarkDotNet.BenchmarkDotNetTasks.get_BenchmarkDotNetPath()
   at Nuke.Common.Tools.BenchmarkDotNet.BenchmarkDotNetTasks.BenchmarkDotNet(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Nullable`1 logTimestamp, String logFile, Func`2 outputFilter)
   at Build.<get_BenchMarkTests>b__1_1() in C:\GIT\myrepo\lib\dotnet\.build\Build.BenchMarkTests.cs:line 26
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)

Inner Exception 1:
Exception: Assertion failed: Could not find package 'benchmarkdotnet.tool' using:
 - Project assets file 'C:\GIT\myrepo\lib\dotnet\.build\obj\project.assets.json'
 - NuGet packages config 'C:\GIT\myrepo\lib\dotnet\.build\Build.csproj'
```

### Anything else we should know?

Appreciate if you can share a working sample code

**Comment by matkoch** [comment]
As far as I can see the exception message says exactly what to do. Also please note that the Slack workspace is meant for general questions.

**Comment by satishviswanathan** [comment]
@matkoch I was not able to use this package in dotnet 5 or dotnet core 3.1 project. Is there are any prerequisite that I'm missing.

**Comment by GeorgDangl** [comment]
You could reference it as a package download instead of a direct reference, like this: 
https://github.com/nuke-build/nuke/blob/105921727112e006e75ce19fa5313feb6cfa640a/build/_build.csproj#L57
