### ISSUE TITLE
Missing case for VS2022 in GetVersionFolder for MSBuildToolPathResolver.cs

### ISSUE THREAD

**Issue by itssimple** [nuke-build/nuke#820]
### Usage Information

6.0.0-beta0009 / .NET 5.0 / .NET 6.0 / Windows Server 2019

### Relevant Code / Invocations

```code
MSBuild(s => s
  .SetTargets("Rebuild")
  .SetTargetPath(_b.Solution)
  .SetConfiguration("Release")
  .SetMaxCpuCount(Math.Max(2, Environment.ProcessorCount / 4))
  .SetNodeReuse(nodeReuse)
  .SetVerbosity(verbosity)
);
```

### Expected Behavior

I expect the resolver to find the path to MSBuild in its default path (`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe`), and continue on with the build

### Stacktrace / Log

```code
Assertion failed: Could not find a suitable MSBuild instance.
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.Resolve(Nullable`1 msBuildVersion, Nullable`1 msBuildPlatform)
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.GetProcessToolPath()
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(MSBuildSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(Configure`1 configurator)
   at BuildTools.Actions.MsBuild(MSBuildVerbosity verbosity, Boolean nodeReuse) in B:\Builds\lo-cbcank0kepa3skyw\build\BuildTools\Actions.MsBuild.cs:line 22
   at BuildTools.BaseBuild.ExecuteCompileMsBuild() in B:\Builds\lo-cbcank0kepa3skyw\build\BuildTools\BaseBuild.cs:line 127
   at Build.<>n__4()
   at Build.ExecuteCompileMsBuild() in B:\Builds\lo-cbcank0kepa3skyw\build\Build.cs:line 153
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass62_0.<Executes>b__0()
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

**Comment by itssimple** [comment]
Suggested fix is simple to replace the switch like this:

https://github.com/itssimple/nuke/commit/285ae98e0e5cc1da0c44666fac126325dff95b75#diff-1221e4fd009cf443804b9dfedebcbde61ceb53fa41d1b86fad1847e61efde107L101-L108

**Comment by matkoch** [comment]
@itssimple thanks for catching this, and also thanks for your support! If you want I can add your company logo to our readme file.

**Comment by matkoch** [comment]
https://www.nuget.org/packages/Nuke.Common/6.0.0-beta0010

**Comment by itssimple** [comment]
> @itssimple thanks for catching this, and also thanks for your support! If you want I can add your company logo to our readme file.

Thanks for fixing this so quickly!

Nah, we don't need to be added to the readme, we just want to sponsor this lovely project, since we use it in our onprem CI solution. :)

**Comment by zvirja** [comment]
In case somebody is looking for a workaround without updating to latest version, I found an approach like this: https://github.com/zvirja/ReSharperHelpers/blob/19b500f11148cfddfb6f5e7e31774e69a5d00387/build/Build.cs#L114

**Comment by michaldivis** [comment]
I've had the same issue with Nuke.Common 5.1.3. Updating to version 6.0.1 resolved it.
