### ISSUE TITLE
MSBuildToolPathResolver.GetVersionFolder dont have option to VS2022

### ISSUE THREAD

**Issue by VladyslavLishchyna** [nuke-build/nuke#834]
### Usage Information

Nuke.Common 6.0.0-beta0001 / .Net Framework 4.7 / Windows

### Relevant Code / Invocations

```code
public Target BuildPackage => _ => _
      .TryAfter<ICanBuild>(x => x.Build)
      .TryBefore<ICanDeployConsul>(x => x.DeployConsul)
      .Executes(() =>
      {
        var pathsOptions = Get<PathsOptions>();

        MSBuild(_ => _
          .SetTargetPath(RootDirectory / "Portal/Api/Api.csproj")
          .SetMSBuildVersion(MSBuildVersion.VS2019)
          .SetTargets("Rebuild", "package")
          .SetConfiguration("Release")
          .SetProperty("OutputPath", "bin")
          .SetProperty("packagelocation", pathsOptions.BaseOutputDirectory)
          .SetProperty("PackageTempRootDir", pathsOptions.BaseOutputDirectory));
      });
```

### Expected Behavior

Msbuild didn't fail

### Stacktrace / Log

```code
Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'version')
Actual value was VS2022.

   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.GetVersionFolder(MSBuildVersion version)
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.GetFromVs2017Instance(MSBuildVersion version, MSBuildPlatform platform, String edition, SpecialFolders specialFolder)
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.<>c.<ResolveInternal>b__2_5(<>f__AnonymousType12`2 <>h__TransparentIdentifier2)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.ResolveInternal(Nullable`1 msBuildVersion, Nullable`1 msBuildPlatform)
   at Nuke.Common.Tools.MSBuild.MSBuildToolPathResolver.Resolve(Nullable`1 msBuildVersion, Nullable`1 msBuildPlatform)
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.GetProcessToolPath()
   at Nuke.Common.Tools.MSBuild.MSBuildSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(MSBuildSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(Configure`1 configurator)
   at Api.Nuke.Program.<>c.<get_BuildPackage>b__2_3() in D:\Plarium-Projects\portal-backend\tools\WebApi.Nuke\Program.cs:line 22
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

**Comment by VladyslavLishchyna** [comment]
I find PR for fix it https://github.com/nuke-build/nuke/pull/828 so close this report
