### ISSUE TITLE
Build crashes when multiple CI/CD configurations are generated

### ISSUE THREAD

**Issue by valadas** [nuke-build/nuke#857]
### Usage Information

Nuke 6.0.1 / SDK 6.0.100 / net6.0 / Windows 11

### Description

I intermittently get the below errors when using multiple CI attributes on the build class.
When that happens I can most of the time make it work by deleting the generated workflow yaml files, but not always, at times I have to do that many times or comment out the attributes, run a build and uncomment them. It is very intermittent and I have no accurate steps to make it happen on demand.

```
$ nuke
PowerShell Desktop version 5.1.22000.282
Microsoft (R) .NET Core SDK version 6.0.100
18:57:23 [ERR] Unhandled exception: One or more errors occurred. (Process 'dotnet.exe' exited with code -1.
   > C:\PROGRA~1\dotnet\dotnet.exe D:\websites\template\Website\DesktopModules\MyModule20220129\_build\bin\Debug\_build.dll --generate-configuration GitHubActions_Release --host GitHubActions
   @ D:\websites\template\Website\DesktopModules\MyModule20220129
)
System.AggregateException: One or more errors occurred. (Process 'dotnet.exe' exited with code -1.
   > C:\PROGRA~1\dotnet\dotnet.exe D:\websites\template\Website\DesktopModules\MyModule20220129\_build\bin\Debug\_build.dll --generate-configuration GitHubActions_Release --host GitHubActions
   @ D:\websites\template\Website\DesktopModules\MyModule20220129
)
 ---> Nuke.Common.Tooling.ProcessException: Process 'dotnet.exe' exited with code -1.
   > C:\PROGRA~1\dotnet\dotnet.exe D:\websites\template\Website\DesktopModules\MyModule20220129\_build\bin\Debug\_build.dll --generate-configuration GitHubActions_Release --host GitHubActions
   @ D:\websites\template\Website\DesktopModules\MyModule20220129

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.CI.InvokeBuildServerConfigurationGenerationAttribute.HasConfigurationChanged(IConfigurationGenerator generator, NukeBuild build)
   at Nuke.Common.CI.InvokeBuildServerConfigurationGenerationAttribute.<>c__DisplayClass0_0.<OnBuildCreated>b__1(IConfigurationGenerator x)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Nuke.Common.CI.InvokeBuildServerConfigurationGenerationAttribute.OnBuildCreated(NukeBuild build, IReadOnlyCollection`1 executableTargets)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### Reproduction Steps

With this for attributes:

```
[GitHubActions(
    "Release",
    GitHubActionsImage.WindowsLatest,
    EnableGitHubContext = true,
    OnPushBranches = new[] { "master", "main", "release/*" },
    InvokedTargets = new[] { nameof(Release) }
)]
[GitHubActions(
    "PR_Validation",
    GitHubActionsImage.WindowsLatest,
    EnableGitHubContext = true,
    OnPullRequestBranches = new[] { "master", "main", "develop", "development", "release/*" },
    InvokedTargets = new[] { nameof(Package) }
)]
[GitHubActions(
    "Build",
    GitHubActionsImage.WindowsLatest,
    EnableGitHubContext = true,
    OnPushBranches = new[] { "master", "develop", "release/*" },
    InvokedTargets = new[] { nameof(DeployGeneratedFiles) }
    )]
```

### Expected Behavior

Should be stable and not throw exceptions intermittently.

### Actual Behavior

Intermittently throws above exception.

### Regression?

I am not 100% sure but it kinda coincided with the change from `ImportGitHubToken` to `EnableGitHubContext = true`

### Known Workarounds

Most of the time, deleting the yaml files and re-running nuke fixes it. But not always.

Also commenting out the attributes and running build works, then uncommenting after a good build usually makes the bug disappear but only for some time, it comes back intermittently.

**Comment by ron-myers** [comment]
Confirmed this behavior on a Windows machine.

Then used a cloned copy to nuke, modified the source to output, added a project to the nuke project to test and this exception was fired:

```
23:26:55 [DBG] ::error::Unhandled exception: "The process cannot access the file 'C:\dev\oss\nuke-temp\nuke\.nuke\build.schema.json' because it is being used by another process."
23:26:55 [DBG] 23:26:55 [ERR] Unhandled exception: The process cannot access the file 'C:\dev\oss\nuke-temp\nuke\.nuke\build.schema.json' because it is being used by another process.
23:26:55 [DBG] System.IO.IOException: The process cannot access the file 'C:\dev\oss\nuke-temp\nuke\.nuke\build.schema.json' because it is being used by another process.
23:26:55 [DBG]    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
23:26:55 [DBG]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
23:26:55 [DBG]    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
23:26:55 [DBG]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
23:26:55 [DBG]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
23:26:55 [DBG]    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
23:26:55 [DBG]    at System.IO.File.WriteAllText(String path, String contents)
23:26:55 [DBG]    at Nuke.Common.Execution.SchemaUtility.WriteBuildSchemaFile(NukeBuild build) in C:\dev\oss\nuke-temp\nuke\source\Nuke.Common\Execution\SchemaUtility.cs:line 23
23:26:55 [DBG]    at Nuke.Common.Execution.HandleShellCompletionAttribute.OnBuildCreated(NukeBuild build, IReadOnlyCollection`1 executableTargets) in C:\dev\oss\nuke-temp\nuke\source\Nuke.Common\Execution\HandleShellCompletionAttribute.cs:line 25
23:26:55 [DBG]    at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in C:\dev\oss\nuke-temp\nuke\source\Nuke.Common\Utilities\Collections\Enumerable.ForEach.cs:line 17
23:26:55 [DBG]    at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
23:26:55 [DBG]    at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in C:\dev\oss\nuke-temp\nuke\source\Nuke.Common\Execution\BuildManager.cs:line 45
```

The simplest change is to remove the `AsParallel` call to the generation process.  

I think if the above issue is corrected there could be a few other issues to follow.  The output notes that the `.github\workflows` is created for each of the attributes when generating.

Happy to submit a PR if desired.

**Comment by valadas** [comment]
@matkoch I had no time to do it yet, but I had in my target the idea to make this work by consuming the github provided json file instead of taking in all the environment variables. Sooo, if you want to reopen this one and assign it to me, or another process, I'll try to sink my teeth into that soonish (like a week or two I guess)...

**Comment by valadas** [comment]
Oh wait, nevermind that last comment, I was confusing with another issue. I am not sure how to solve this one. Happy to contribute a block of hours in money if you want to tackle it though 😁
