### ISSUE TITLE
Logging Verbosity Not Respected Anymore

### ISSUE THREAD

**Issue by christianburgherr** [nuke-build/nuke#870]
### Usage Information

6.0.1 / 6.0.1 / .NET 6.0 / Windows 10

### Description

**Issue**: 
With new version 6.0.1 verbosity / logging levels are not respected as before.

### Reproduction Steps

**How to reproduce**: 
Run 
```
nuke --verbosity Normal
```
Log with 6.0.1
```
╬════════════
║ Compile
╬═══
​
15:11:33 [DBG] Normal C:\demo\Nuke_Issue\bmDemo.sln
15:11:33 [INF] Info C:\demo\Nuke_Issue\bmDemo.sln
15:11:33 [WRN] Warning!
15:11:33 [ERR] Error!
15:11:33 [ERR] Target Compile failed
System.NotSupportedException: Specified method is not supported.
   at Nuke.Common.Logger.Success(String text)
   at Build.<get_Compile>b__8_1() in C:\demo\Nuke_Issue\build\Build.cs:line 55
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
​
╬══════════════════════
║ Warnings & Errors
╬═════════════
​
[WRN] Compile: Warning!
[ERR] Compile: Error!
[ERR] Compile: Target Compile failed
​
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Succeeded     < 1sec
Compile            Failed        < 1sec   // NotSupportedException: Specified method is not supported.
───────────────────────────────────────
```
Log with version 5.1.4
```
╬════════════
║ Compile
╬═══

Normal C:\demo\Nuke_Issue\bmDemo.sln
Info C:\demo\Nuke_Issue\bmDemo.sln
Warning!
Error!
Finished.

Repeating warnings and errors:
Warning!
Error!

═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Succeeded     < 1sec
Compile            Succeeded     < 1sec
───────────────────────────────────────
Total                            < 1sec
═══════════════════════════════════════
```

**Code snippets to reproduce**:
File build.cs
```
using static Nuke.Common.Logger;

[Solution] readonly Solution Solution;

Trace($"Trace {Solution}");
Normal("Normal {0}", Solution);
Info($"Info {Solution}");

Warn("Warning!");
Error("Error!");
//Error(new Exception());

Success("Finished.");
```

### Expected Behavior

- Verbosity respected as in versions 5.x.x

### Actual Behavior

**Unexpected Behaviour/Findings**:
- verbosity not respected anymore - debug output is displayed (see [DBG]  above)
- exception with method Nuke.Common.Logger.Success(String text)

**Comment by matkoch** [comment]
works as designed. normal means everything from debug. verbose includes trace messages.

**Comment by christianburgherr** [comment]
okay - but e.g. how can debug output [dbg] be left away in order to reduce the logging amount?
