### ISSUE TITLE
Custom NuGet package folder breaks tool tasks

### ISSUE THREAD

**Issue by Werebunny** [nuke-build/nuke#88]
Nuke worked great for my project, but I encountered a few issues.

## Expected Behavior
Builds work with a Nuget.config file in the root directory containing:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value=".\artifacts\packages" />
  </config>
</configuration>
```

## Current Behavior
```c#
Assertion failed: Could not find package 'OpenCover' via 'C:\projects\createandfake\build\nuke\.Build\.Build.csproj'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable)
   at Nuke.Common.Tooling.ProcessManager.StartProcess(ToolSettings toolSettings, ProcessSettings processSettings)
   at Nuke.Common.Tools.OpenCover.OpenCoverTasks.OpenCover(Configure`1 configurator, ProcessSettings processSettings)
   at Build.<get_Coverage>b__19_2() in C:\projects\createandfake\build\nuke\.Build\Build.cs:line 100
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(IEnumerable`1 executionList)
   at Nuke.Common.Execution.BuildExecutor.Execute[T](Expression`1 defaultTargetExpression)
```

## Steps to Reproduce
1. Create project or clone [CreateAndFake](https://github.com/CreateAndFake/CreateAndFake).
2. Ensure your normal global package folder does not contain the package.
3. Run a build using a NuGet tool, such as './build/build Coverage' for CreateAndFake.

## Additional Information
It seems the build doesn't respect the Nuget.config, and just looks in the global folder. Either the Nuget.config file needs to be considered, or an option to specify a package directory is needed.

**Comment by matkoch** [comment]
This is a valid issue. We will look into this shortly.

**Comment by Werebunny** [comment]
Thanks.
