### ISSUE TITLE
The type initializer for 'Nuke.Common.ProjectModel.ProjectModelTasks' threw an exception. Jenkins in Docker

### ISSUE THREAD

**Issue by JoshClose** [nuke-build/nuke#892]
### Usage Information

6.0.1 / Only Linux dependencies installed / net6.0 / Docker container running Debian 11 (bullseye)

### Description

I'm receiving this error when running a build. None of the steps execute.

```
+ ./build.sh compile --configuration Release
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.200/dotnet-sdk-6.0.200-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.200/dotnet-sdk-6.0.200-linux-x64.tar.gz
dotnet-install: Binaries of dotnet can be found in /var/jenkins_home/workspace/ExpressCheckIn_jenkins/.nuke/temp/dotnet-unix
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
Microsoft (R) .NET Core SDK version 6.0.200

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 6.0.1 (Linux,.NETCoreApp,Version=v6.0)

20:14:53 [ERR] Unhandled exception: The type initializer for 'Nuke.Common.Execution.Telemetry' threw an exception.
System.TypeInitializationException: The type initializer for 'Nuke.Common.Execution.Telemetry' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Nuke.Common.ProjectModel.ProjectModelTasks' threw an exception.
 ---> System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at Nuke.Common.ProjectModel.ProjectModelTasks.Initialize()
   at Nuke.Common.ProjectModel.ProjectModelTasks..cctor()
   --- End of inner exception stack trace ---
   at Nuke.Common.ProjectModel.ProjectModelTasks.Initialize()
   at Nuke.Common.Execution.Telemetry..cctor()
   --- End of inner exception stack trace ---
   at Nuke.Common.Execution.Telemetry.BuildStarted(NukeBuild build)
   at Nuke.Common.Execution.TelemetryAttribute.OnBuildInitialized(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

╬══════════════════════
║ Warnings & Errors
╬═════════════

[ERR] : Unhandled exception: The type initializer for 'Nuke.Common.Execution.Telemetry' threw an exception.

═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            NotRun              
Compile            NotRun              
───────────────────────────────────────
Total                            < 1sec
═══════════════════════════════════════

Build failed on 03/17/2022 20:14:53. (╯°□°）╯︵ ┻━┻
script returned exit code 255
```

### Reproduction Steps

I'm doing this on a DigitalOcean droplet Docker template from their marketplace.

I'm following these instructions. https://www.jenkins.io/doc/book/installing/docker

Follow these steps on the machine that has docker installed.

Create the network.

```
sudo docker network create jenkins
```

Run the docker-in-docker image. This allows execution of docker commands inside jenkins.

```
sudo docker run --name jenkins-docker --detach \
  --privileged --network jenkins --network-alias docker \
  --env DOCKER_TLS_CERTDIR=/certs \
  --volume jenkins-docker-certs:/certs/client \
  --volume jenkins-data:/var/jenkins_home \
  --publish 2376:2376 \
  docker:dind --storage-driver overlay2
```

Create a Dockerfile that adds to jenkins. This includes dependencies for .NET on Debian 11 (bullseye). The second apt-get line is the .NET dependencies.

```
FROM jenkins/jenkins:2.332.1-jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release \
  libc6 libgcc1 libgssapi-krb5-2 libicu66 libssl1.1 libstdc++6 zlib1g
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.25.3 docker-workflow:1.28"
```

Build the docker image:

```
sudo docker build -t custom-jenkins-blueocean:2.339-1 .
```

Run the docker blue ocean container.

```
sudo docker run --name jenkins-blueocean --detach \
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
  --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 \
  --publish 8080:8080 --publish 50000:50000 \
  --volume jenkins-data:/var/jenkins_home \
  --volume jenkins-docker-certs:/certs/client:ro \
  custom-jenkins-blueocean:2.339-1
```

Open a browser to `<ipaddress>:8080`. Finish the Jenkins install. Use the recommended plugins selection.

Click the `Open Blue Ocean` link on the left. Create a new pipeline. Select GitHub. Choose your organization and then repository. This repository should have a Nuke build project with execution engine 6.0.1. Complete the pipeline creation.

Click on a node to configure it. Choose `Shell Script`. Add this script.

```
./build.sh compile --configuration Release
```

Save the pipeline and run it if it didn't automatically start.

### Expected Behavior

Should not error out before running.

### Actual Behavior

Errors out before running.

### Regression?

First time creating this CI build.

**Comment by SKProCH** [comment]
I have same problem on `centos:latest` docker image.

Is there any workaround?

**Comment by JoshClose** [comment]
My guess would be installing the .NET SDK would fix it, but that kinda defeats the purpose. I haven't tried yet to confirm though. It would be interesting if it still failed when the SDK is installed though.

**Comment by matkoch** [comment]
Can someone suggest a docker image that I can run with a mount point against a local repository? I.e., without jumping through the hoops of having Jenkins and a remote repository?

**Comment by JoshClose** [comment]
Try this.

Run the debian instance.
```
$ sudo docker run --name nuke-test --rm -d -it -v /local/path/to/repository:/app debian:bullseye /bin/bash -l
```
Get a command prompt inside the container you just created.
```
$ sudo docker exec -it nuke-test /bin/bash
```
Install the .NET dependencies for debian.
```
# apt-get update && apt-get install libc6 libgcc-s1 libgssapi-krb5-2 libicu67 libssl1.1 libstdc++6 zlib1g
```
Run the nuke build.
```
# cd /app
# ./build.sh
```

**Comment by matkoch** [comment]
Thanks, I can reproduce it now, but not sure about a fix yet. Is it a blocker?

**Comment by JoshClose** [comment]
Installing the .NET SDK works as a workaround. I set up a TeamCity build to try out and may end up going that road anyways.

**Comment by mdealer** [comment]
On our side it's not even docker, just plain OS X Monterey and Linux 18.04 both with same error. Same build works fine on our Windows nodes.

**Comment by Sam13** [comment]
I get the same exception in a Windows container based on _mcr.microsoft.com/dotnet/framework/sdk:4.8-20210511-windowsservercore-ltsc2019_.
.NET 5 / 6 SDKs installed, Nuke v6.0.3.

Nuke is called directly via _dotnet.exe_ no bootstrapping scripts involved.
_msbuild_ and _dotnet_ are in the path, can be called from anywhere in the shell.

It works for me when I remove the ```CheckBuildProjectConfigurations``` attribute from the Nuke build.
Subsequent invocations of MSBuild tasks work without problems (MSBuild is taken from VS build tools installation in Docker image).
