### ISSUE TITLE
SonarScannerTasks incompatible with .NET 6

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#899]
### Usage Information

6.0.1

### Description

NUKE's built in `SonarScannerTasks` does not support .NET 6 due to its path resolution/validation, although `dotnet-sonarscanner` supports .NET 6 in reality. 

[dotnet-sonarscanner](https://www.nuget.org/packages/dotnet-sonarscanner/) targets .NET 5, however, its `runtimeconfig.json` specifies `"rollForward": "LatestMajor"` to make it runnable under a .NET 6 runtime as well. This configuration seems not to be recognized by Nuke and execution is prevented. 

### Reproduction Steps

On a machine with only .NET 6 installed, use the following target:
```
    Target Sonar => _ => _
        .Executes(() =>
        {
            SonarScannerTasks.SonarScannerBegin();
        });
```

### Expected Behavior

SonarScanner describes that it supports .NET 6 and the CLI works on .NET6. Nuke should not prevent execution. 

### Actual Behavior

```
System.ArgumentException
  HResult=0x80070057
  Message=Package executable SonarScanner.MSBuild.dll or SonarScanner.MSBuild.exe [dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool] requires a framework:
 - net5.0
 - netcoreapp2.0
 - netcoreapp3.0
  Source=Nuke.Common
  StackTrace:
   at Nuke.Common.Assert.True(Boolean condition, String message, String argumentExpression)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.SonarScanner.SonarScannerBeginSettings.GetProcessToolPath()
   at Nuke.Common.Tools.SonarScanner.SonarScannerBeginSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.SonarScanner.SonarScannerTasks.SonarScannerBegin(SonarScannerBeginSettings toolSettings)
   at [redacted]
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

### Known Workarounds

```
    Target Sonar => _ => _
        .Executes(() =>
        {
            SonarScannerTasks.SonarScannerBegin(new CustomSonarScannerBeginSettings());
        });

    public class CustomSonarScannerBeginSettings : SonarScannerBeginSettings
    {
        public override string ProcessToolPath => GetToolPath("NET5.0");

        internal static string GetToolPath(string framework = null)
        {
            return ToolPathResolver.GetPackageExecutable(
                packageId: "dotnet-sonarscanner|MSBuild.SonarQube.Runner.Tool",
                packageExecutable: "SonarScanner.MSBuild.dll|SonarScanner.MSBuild.exe",
                framework: framework);
        }
    }
```

**Comment by matkoch** [comment]
Why not just use `SetFramework` in the invocation?

**Comment by tyb-dev** [comment]
There may be some other workarounds, but `dotnet-sonarscanner` advertises .NET 6 compatibility and works there in reality. The combination of .NET 6 and `dotnet-sonarscanner` seems a widely used one, shouldn't Nuke work out of the box? 
Could this be achieved with a custom override doing this `SetFramework` magic?

**Comment by matkoch** [comment]
To be clear, you just have to call `SetFramework("net5.0")`. As of now, I don't like the idea to automagically use whatever TFM would be the most appropriate.. It should be explicit.

**Comment by matkoch** [comment]
I'm closing this because I think this will fix it. Feel free to reopen.
