### ISSUE TITLE
PowerShell Core not detected as an alternative for Powershell in PowerShellTasks

### ISSUE THREAD

**Issue by lahma** [nuke-build/nuke#905]
### Usage Information

NUKE 6.0.1 / .NET SDK 6.0 Docker image / Linux

### Description

When running NUKE inside `mcr.microsoft.com/dotnet/sdk:6.0` docker container with Linux host, the PowerShell resolution fails with `System.ArgumentException: Could not find 'PowerShell' via '/usr/bin/which'`.

This is because the Linux SDK image only contains PowerShell Core. 

https://github.com/nuke-build/nuke/blob/fa9e92a57223ee7115d7f097a53e3ec4f5274da1/source/Nuke.Common/Tools/PowerShell/PowerShell.Generated.cs#L32-L34

### Reproduction Steps

Run NUKE inside MS dotnet container, I was using this kind of pipeline, unfortunately a bit hard to replicate locally. Please ask if further reproduction steps required. This is Bitbucket Pipelines YAML.

```yaml
image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - step:
        script:
          # this fixes the issue
         #  - export POWERSHELL_EXE="/usr/bin/pwsh"
          - ./build.sh clean compile test pack --configuration Release
```

### Expected Behavior

Ideally NUKE would fallback to trying also PowerShell Core, which is `pwsh`.

### Actual Behavior

When environment variable is not set and `powershell` command is not found, an exception is thrown.

```
08:47:11 [WRN] Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Could not find 'PowerShell' via '/usr/bin/which'. (Parameter 'locateProcess.Output
                .Select(x => x.Text)
                .Where(x => EnvironmentInfo.IsWin && Path.HasExtension(x) || EnvironmentInfo.IsUnix)
                .FirstOrDefault(File.Exists)')
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression)
   at Nuke.Common.Tooling.ToolPathResolver.GetPathExecutable(String pathExecutable)
   at Nuke.Common.Tooling.ToolResolver.GetPathTool(String name)
   at Nuke.Common.Tooling.PathExecutableAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Nuke.Common.ControlFlow.SuppressErrorsIf(Boolean condition, Delegate action, Object defaultValue, Boolean includeStackTrace, Boolean logWarning)
```

### Regression?

No, this is not a regression.

### Known Workarounds

I was able to work around the issue in Bitbucket Pipelines by adding script task `export POWERSHELL_EXE="/usr/bin/pwsh"`, which basically redirects the resolution that `PowerShellTasks` is doing.

**Comment by VolkmarR** [comment]
An option could be to check, if the current os is not windows. In that case, it must be the PowerShell core, because the standard PowerShell works only on windows.
