### ISSUE TITLE
NUKE Support plugin fails with Rider 2022.1.1

### ISSUE THREAD

**Issue by Sam13** [nuke-build/nuke#919]
### Usage Information

NUKE Support plugin 2022.1.0-eap05, Rider 2022.1.1, Windows 10

### Description

NUKE Support plugin 2022.1.0-eap05 fails with Rider 2022.1.1:
When I click on the Nuke button which is located left of a target an IDE error occurs:

```
Catch

java.lang.IllegalArgumentException: Collection contains more than one matching element.
	at com.jetbrains.rider.plugins.nuke.runConfigurations.NukeRunConfigurationUtilKt.createAndAddConfiguration(NukeRunConfigurationUtil.kt:62)
	at com.jetbrains.rider.plugins.nuke.runConfigurations.NukeRunConfigurationUtilKt.findOrCreateConfiguration(NukeRunConfigurationUtil.kt:21)
	at com.jetbrains.rider.plugins.nuke.runConfigurations.NukeRunConfigurationManager$1.invoke(NukeRunConfigurationManager.kt:18)
	at com.jetbrains.rider.plugins.nuke.runConfigurations.NukeRunConfigurationManager$1.invoke(NukeRunConfigurationManager.kt:16)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:72)
	at com.jetbrains.rd.platform.protocol.SwitchingScheduler.pumpProtocolQueue(SwitchingScheduler.kt:19)
	at com.jetbrains.rdclient.util.idea.ExtensionsKt.callSynchronously(Extensions.kt:140)
	at com.jetbrains.rdclient.util.idea.ExtensionsKt.callSynchronously$default(Extensions.kt:123)
	at com.jetbrains.rider.util.idea.ExtensionsKt.syncFromBackend(Extensions.kt:95)
	at com.jetbrains.rider.intentions.altEnter.ReSharperPopupModel.executeItem(ReSharperPopupModel.kt:135)
	at com.jetbrains.rider.intentions.altEnter.PopupModel$attachTo$2.invoke(PopupModel.kt:23)
	at com.jetbrains.rider.intentions.altEnter.PopupModel$attachTo$2.invoke(PopupModel.kt:9)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$initViewModel$3.invoke(DefaultPopupViewModel.kt:77)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$initViewModel$3.invoke(DefaultPopupViewModel.kt:16)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel$executeSelectedItem$executeDelegate$1.invoke(DefaultPopupListModel.kt:137)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel$executeSelectedItem$executeDelegate$1.invoke(DefaultPopupListModel.kt:15)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$sam$java_lang_Runnable$0.run(PopupListView.kt)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1538)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:179)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:172)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1535)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:798)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl.cancel(PopupViewImpl.kt:85)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:746)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1484)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl$2.invoke(PopupViewImpl.kt:61)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewImpl$2.invoke(PopupViewImpl.kt:35)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:298)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:279)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate$default(RLifetime.kt:253)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewHierarchy.V(PopupViewHierarchy.kt:155)
	at com.jetbrains.rider.services.popups.nova.ui.PopupViewHierarchy.closeAllViews(PopupViewHierarchy.kt:167)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$executeSelectedItem$1.invoke(PopupListView.kt:284)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView$executeSelectedItem$1.invoke(PopupListView.kt:34)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupListModel.executeSelectedItem(DefaultPopupListModel.kt:144)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.A(PopupListView.kt:278)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.handleReleased(PopupListView.kt:270)
	at com.jetbrains.rider.services.popups.nova.ui.MouseListenerEx$DefaultImpls.mouseReleased(MouseListenerEx.kt:13)
	at com.jetbrains.rider.services.popups.nova.ui.PopupListView.mouseReleased(PopupListView.kt:34)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:188)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$ModalContext.dispose(RiderModalPopupCookie.kt:63)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	at com.jetbrains.rider.services.popups.nova.impl.RiderModalPopupCookie$Companion.using(RiderModalPopupCookie.kt:99)
	at com.jetbrains.rider.services.popups.RiderPopupModelHost.showPopup(RiderPopupModelHost.kt:52)
	at com.jetbrains.rdclient.services.popups.FrontendPopupModelHost$1.invoke(FrontendPopupModelHost.kt:42)
	at com.jetbrains.rdclient.services.popups.FrontendPopupModelHost$1.invoke(FrontendPopupModelHost.kt:36)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:146)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:108)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:126)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.ViewableMap.put(ViewableMap.kt:29)
	at com.jetbrains.rd.framework.impl.RdMap.onWireReceived(RdMap.kt:143)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

### Reproduction Steps

Click on NUKE button which is located on left side of each target

### Expected Behavior

Nuke target runs

### Actual Behavior

IDE error happens

### Regression?

- Worked with earlier versions of Rider
- Unable to downgrade plugin since older versions not compatible with Rider 2022

### Known Workarounds

None

**Comment by matkoch** [comment]
https://plugins.jetbrains.com/plugin/10803-nuke-support/versions/stable/171953

**Comment by Sam13** [comment]
I confirm that your fix works.
Thanks a lot for the quick reaction 🥇
