### ISSUE TITLE
NullReferenceException Telemetry

### ISSUE THREAD

**Issue by FinalFortune** [nuke-build/nuke#947]
### Usage Information

6.10 / 6.0.203 / net6.0 / Microsoft Windows [Version 10.0.19044.1706]

### Description

Executing the build script results in a NullReferenceException.  Doesn't matter what's in my build.cs, not sure what I changed for it to do this, I've deleted obj/bin folders too.

### Reproduction Steps

Installed GitVersion with `nuke :add-package GitVersion.Tool`, doubt that is the problem.  By the looks of the error it's something to do with the telemetry

### Expected Behavior

Should run the script without error.

### Actual Behavior

```
V |                      | ArgumentsFromParametersFile.OnBuildCreated (150)
V |                      | InjectParameterValues.OnBuildCreated (100)
V |                      | HandleShellCompletion.OnBuildCreated (75)
V |                      | GenerateBuildServerConfigurations.OnBuildCreated (50)
V |                      | InvokeBuildServerConfigurationGeneration.OnBuildCreated (45)
V |                      | UpdateNotification.OnBuildCreated (10)
V |                      | UnsetVisualStudioEnvironmentVariables.OnBuildCreated (0)
V |                      | HandleVisualStudioDebugging.OnBuildCreated (0)
V |                      | HandleSingleFileExecution.OnBuildCreated (-50)
V |                      | EventInvoker.OnBuildCreated (-3.4028235E+38)
V |                      | HandleHelpRequests.OnBuildInitialized (5)
V |                      | Telemetry.OnBuildInitialized (0)
V |                      | Target-unrelated exception was thrown
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nuke.Common.Utilities.StringExtensions.ContainsOrdinalIgnoreCase(String str, String other) in /_/source/Nuke.Common/Utilities/String.StartsEndsContains.cs:line 17
   at Nuke.Common.Execution.Telemetry.<>c__DisplayClass19_0.<GetRepositoryProperties>b__1() in /_/source/Nuke.Common/Execution/Telemetry.Properties.cs:line 51
   at Nuke.Common.Execution.Telemetry.<>c.<GetRepositoryProperties>b__19_10(ValueTuple`2 x) in /_/source/Nuke.Common/Execution/Telemetry.Properties.cs:line 69
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Execution.Telemetry.GetRepositoryProperties(String directory) in /_/source/Nuke.Common/Execution/Telemetry.Properties.cs:line 67
   at Nuke.Common.Execution.Telemetry.BuildStarted(NukeBuild build) in /_/source/Nuke.Common/Execution/Telemetry.Events.cs:line 18
   at Nuke.Common.Execution.TelemetryAttribute.OnBuildInitialized(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan) in /_/source/Nuke.Common/Execution/TelemetryAttribute.cs:line 21
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/Execution/BuildManager.cs:line 58
V |                      | UpdateNotification.OnBuildFinished (10)
V |                      | SerializeBuildServerState.OnBuildFinished (0)
V |                      | EventInvoker.OnBuildFinished (-3.4028235E+38)

```

**Comment by matkoch** [comment]
#945
